---
permalink: a400/controller-replace-system-config-restore-and-verify.html 
sidebar: sidebar 
keywords: aff a400, restore and verify the system configuration, verify and set the ha state of the controller module 
summary: 'Verifique se a configuração de alta disponibilidade (HA) do controlador está ativa e funcionando corretamente no seu sistema de storage AFF A400 e confirme se as portas de storage do sistema listam todos os caminhos para os discos.' 
---
= Restaure e verifique a configuração do sistema - AFF A400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verifique se a configuração de alta disponibilidade (HA) do controlador está ativa e funcionando corretamente no seu sistema de storage AFF A400 e confirme se as portas de storage do sistema listam todos os caminhos para os discos.

Verifique as configurações de alta disponibilidade (HA) e a lista de discos antes de colocar o sistema em funcionamento novamente.

.Passos
. Arranque para o modo de manutenção:
+
`boot_ontap maint`

. Digite `y` quando você vir _continuar com boot?_.
+
Se você vir a mensagem de aviso _incompatibilidade de ID do sistema_, digite `y`.

. Introduza `sysconfig -v` e capture o conteúdo do visor.
+

NOTE: Se você vir _INCOMPATIBILIDADE DE PERSONALIDADE_, entre em Contato com o suporte ao cliente.

. Na `sysconfig -v` saída, compare as informações da placa adaptadora com as placas e localizações no controlador de substituição.
. Verifique se todos os componentes apresentam o `HA` mesmo estado:
+
`ha-config show`

+
O estado HA deve ser o mesmo para todos os componentes.

. Se o estado do sistema exibido no módulo controlador não corresponder à configuração do seu sistema, defina o `HA` Estado do módulo controlador:
+
`ha-config modify controller _ha-state_`

+
O valor para o estado HA pode ser um dos seguintes:

+
** `ha`
** `mcc`
** `mcc-2n`
** `mccip`
** `non-ha`


. Confirme se a definição foi alterada:
+
`ha-config show`

. Verifique se o adaptador lista os caminhos para todos os discos: `storage show disk -p`
+
Se você vir algum problema, verifique o cabeamento e recoloque os cabos.

. Sair do modo de manutenção: `halt`


.O que se segue?
Após restaurar e verificar a configuração do sistema AFF A400, você precisa link:controller-replace-recable-reassign-disks.html["devolva o controlador"].
