---
permalink: a90-key-specifications.html 
sidebar: sidebar 
keywords: AFF A90 specifications, AFF A90 specs, NetApp AFF A90, AFF A90 hardware 
summary: Especificações principais para o sistema de armazenamento AFF A90 
---
= Especificações principais do AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A seguir estão algumas especificações selecionadas para o AFF A90.  Visita https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) para uma lista completa das especificações do AFF A90 .  Esta página reflete um único par de alta disponibilidade.



=== Especificações principais do AFF A90

Configuração da plataforma: Par de chassis único AFF A90 HA

Capacidade máxima de matéria-prima: 6,6096 PB

Memória: 2048.0000 GB

Fator de forma: chassi 4U com 2 controladores HA e 48 slots de unidade

Versão ONTAP : b_startONTAP: 9.16.1P2b_end

Slots de expansão PCIe: 18

Versão mínima do ONTAP : ONTAP 9.15.1RC2



=== Máximos de Escalabilidade

* NAS: 12 pares HA, capacidade bruta de 79,3 PB / 70,4 PiB, memória máxima de 24576 GB
* SAN: 6 pares HA, capacidade bruta de 39,7 PB / 35,2 PiB, memória máxima de 12288 GB
* Par HA: 6,6 PB / 5,9 PiB de capacidade bruta, 2048.0000 GB de memória máxima




=== IO



==== IO integrado

Não há dados de E/S a bordo.



==== Total de IO

* Ethernet 200 Gbps: 24 portas
* Ethernet 100 Gbps: 36 portas
* Ethernet 25 Gbps: 56 portas
* Ethernet 10 Gbps: 56 portas
* FC 64 Gbps: 56 portas
* NVMe/FC 64 Gbps: 56 portas
* SAS 12 Gbps: 56 portas




==== Portas de Gestão

* Ethernet 1 Gbps: 2 portas
* RS-232 115 Kbps: 4 portas
* USB 600 Mbps: 2 portas




=== Rede de armazenamento suportada

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NFSv3/RDMA; NFSv4/RDMA; NVMe/FC; NVMe/TCP; S3; S3 com NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Especificações do ambiente do sistema

* Potência típica: 8304 BTU/h
* Pior cenário de potência: 10948 BTU/h
* Peso: 118,0 lbbr/53,5 kg
* Altura: 4U
* Largura: 19” compatível com rack IEC (17,6” 44,7 cm)
* Profundidade: 34,5”br/(36,6” com suporte para gerenciamento de cabos)
* Temperatura/Altitude/Umidade de operação: 10°C a 35°Cbr/50°F a br/95°F) atbr/= 3048mbr/= 10000 pés) de elevação; 8% a 80%br/umidade relativa, sem condensação
* Temperatura/Umidade fora de operação: -40°C a 70°C (-40°F a 158°F) até 12192m (40000 pés)<br/>10% a 95% de umidade relativa, sem condensação, no recipiente original
* Ruído acústico: Potência sonora declarada (LwAd): 8,6;br/Pressão sonora (LpAm) (posições de observação): 71,6 dB




=== Conformidade

* Certificações EMC/EMI: AMCA, FCC, ICES, KC, Marrocos, VCCI
* Certificações de segurança: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificações Segurança/EMC/EMI: EAC, UKRSEPRO
* Certificações Segurança/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normas EMC/EMI: BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normas de segurança: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilidade

Controlador de gerenciamento de placa base baseado em Ethernet (BMC) e interface de gerenciamento ONTAP ; Controladores redundantes de troca a quente; Fontes de alimentação redundantes de troca a quente; Gerenciamento SAS em banda por meio de conexões SAS para prateleiras externas;
