---
permalink: a70-90/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: aff a70, aff a90, replace the boot media 
summary: Verifique os requisitos antes de substituir a mídia de inicialização no seu sistema de armazenamento AFF A70 ou AFF A90 . 
---
= Requisitos para recuperação automatizada de mídia de inicialização - AFF A70 e AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de substituir a mídia de inicialização no seu sistema de armazenamento AFF A70 ou AFF A90 , verifique os requisitos, incluindo a funcionalidade da porta de cluster, a configuração do gerenciador de chaves e a compatibilidade com a versão do ONTAP .

O processo automatizado de recuperação da mídia de inicialização requer o ONTAP 9.17.1 ou posterior.  Se o seu sistema de armazenamento executar uma versão anterior do ONTAP, use olink:bootmedia-replace-workflow.html["procedimento de recuperação de inicialização manual"] .

Reveja os seguintes requisitos.

* Tem de substituir o suporte de arranque com falha por um suporte de arranque de substituição que recebeu do NetApp.
* As portas do cluster são usadas para comunicação entre os dois controladores durante o processo de recuperação de inicialização automatizada. Certifique-se de que as portas do cluster no controlador afetado estejam funcionando corretamente.
* Para o OKM, você precisa da senha de todo o cluster e também dos dados de backup.
* Para EKM, você precisa de cópias dos seguintes arquivos do nó do parceiro:
+
** /cfcard/kmip/servers.cfg
** /cfcard/kmip/certs/client.crt
** /cfcard/kmip/certs/client.key
** /cfcard/kmip/certs/CA.pem


* Compreenda a terminologia do controlador utilizada neste procedimento:
+
** O _controlador danificado_ é o controlador no qual você está executando a manutenção.
** O _controlador saudável_ é o parceiro HA do controlador prejudicado.




.O que vem a seguir
Depois de analisar os requisitos do suporte de arranque, pode link:bootmedia-shutdown-bmr.html["desligue o controlador"].
