---
permalink: a70-90/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff a70, aff a90,  verify and set HA state, complete the replacement process 
summary: Reinicie os controladores, verifique a integridade do sistema e devolva a peça com falha ao NetApp para concluir a etapa final no procedimento de substituição do chassi do AFF A70 e do AFF A90. 
---
= Complete a substituição do chassi - AFF A70 e AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Reinicie os controladores, verifique a integridade do sistema e devolva a peça com falha ao NetApp para concluir a etapa final no procedimento de substituição do chassi do AFF A70 e do AFF A90.



== Passo 1: Inicialize os controladores e execute o retorno.

Inicialize o ONTAP nos controladores e execute o comando `controller giveback` para devolver a propriedade do armazenamento.

.Passos
. Verifique a saída da consola:
+
.. Se o controlador inicializar no prompt Loader, reinicie o controlador com o `boot_ontap` comando.
.. Se o console for exibido `waiting for giveback` após a reinicialização, faça login no controlador parceiro e verifique se o controlador substituído está pronto para giveback com o `storage failover show` comando.


. Execute a giveback:
+
.. Conete o cabo do console ao controlador do parceiro.
.. Devolva o controlador com o `storage failover giveback -fromnode local` comando.






== Etapa 2: Verificar a integridade do sistema de armazenamento

Após a conclusão da devolução do controlador, verifique a integridade do sistema usando https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"] .  Corrija quaisquer problemas encontrados.



== Passo 3: Devolva a peça com falha ao NetApp

Devolva a peça com falha ao NetApp, conforme descrito nas instruções de RMA fornecidas com o kit. Consulte a https://mysupport.netapp.com/site/info/rma["Devolução de peças e substituições"] página para obter mais informações.
