---
permalink: a70-90/controller-replace-requirements.html 
sidebar: sidebar 
keywords: aff a70, aff a90, prerequisite, replace the controller module 
summary: Antes de substituir o controlador do seu sistema AFF A70 ou AFF A90, certifique-se de que cumpre os requisitos necessários para uma substituição bem-sucedida. Isso inclui verificar se todos os outros componentes do sistema estão funcionando corretamente, verificar se você tem o controlador de substituição correto e salvar a saída do console do controlador em um arquivo de log de texto. 
---
= Requisitos para substituir o controlador - AFF A70 e AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de substituir o controlador do seu sistema AFF A70 ou AFF A90, certifique-se de que cumpre os requisitos necessários para uma substituição bem-sucedida. Isso inclui verificar se todos os outros componentes do sistema estão funcionando corretamente, verificar se você tem o controlador de substituição correto e salvar a saída do console do controlador em um arquivo de log de texto.

Reveja os requisitos para substituir o módulo do controlador.

* Todas as gavetas de unidades devem estar funcionando corretamente.
* O controlador saudável deve ser capaz de assumir o controlador que está a ser substituído (referido neste procedimento como ""controlador deficiente"").
* Não utilize este procedimento para atualizações do controlador; em vez disso, consulte o https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["Escolha o procedimento de atualização do hardware do controlador"] para obter orientação.
* Se o sistema estiver em uma configuração do MetroCluster, você deverá revisar https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["Escolher o procedimento de recuperação correto"] para determinar se deve usar esse procedimento.
* Você deve substituir o componente com falha pela unidade substituível em campo (FRU) que você recebeu da NetApp.
* É necessário substituir um módulo controlador por um módulo controlador do mesmo tipo de modelo. Você não pode atualizar seu sistema apenas substituindo o módulo do controlador.
* Não é possível alterar nenhuma unidade ou compartimentos de unidades como parte deste procedimento.
* Como o dispositivo de inicialização está localizado no módulo Gerenciamento do sistema instalado na parte traseira do sistema, você não precisa mover o dispositivo de inicialização ao substituir um módulo controlador.
* É importante que você aplique os comandos nessas etapas nos sistemas corretos:
+
** O controlador _prejudicado_ é o controlador que está sendo substituído.
** O controlador _replacement_ é o novo controlador que está substituindo o controlador prejudicado.
** O controlador _Healthy_ é o controlador sobrevivente.


* Você deve sempre capturar a saída do console do controlador para um arquivo de log de texto.
+
Isso fornece um Registro do procedimento para que você possa solucionar qualquer problema que possa encontrar durante o processo de substituição.



.O que se segue?
Depois de analisar os requisitos para substituir o controlador AFF A70 ou AFF A90, é necessário link:controller-replace-shutdown.html["desligue o controlador desativado"].
