---
permalink: a70-90/drive-replace.html 
sidebar: sidebar 
keywords: aff a70, aff a90, replace the drives 
summary: Você deve substituir uma unidade quando a plataforma Registrar uma mensagem de aviso no console do sistema indicando que uma unidade falhou. Além disso, o LED de avaria no painel do visor do operador e o LED de avaria na unidade avariada acendem-se. 
---
= Substitua a unidade SSD - AFF A70 e AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead lead"]
Você pode substituir uma unidade SSD com falha sem interrupções enquanto a e/S estiver em andamento.

Quando uma unidade falha, a plataforma Registra uma mensagem de aviso no console do sistema indicando qual unidade falhou. Além disso, o LED de avaria no painel do visor do operador e o LED de avaria na unidade avariada acendem-se.

.Antes de começar
* Siga as práticas recomendadas e instale a versão atual do Pacote de Qualificação de disco (DQP) antes de substituir uma unidade.
* Identifique a unidade de disco com falha executando o `storage disk show -broken` comando a partir do console do sistema.
+
A unidade com falha aparece na lista de unidades com falha. Se isso não acontecer, você deve esperar, e então executar o comando novamente.

+

NOTE: Pode levar até várias horas para a unidade aparecer na lista de unidades com falha.

* Determine se a autenticação SED está ativada.
+
A forma como você substitui o disco depende de como a unidade de disco está sendo usada. Se a autenticação SED estiver ativada, você deverá usar as instruções de substituição SED no https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/home.html["Guia de alimentação de encriptação ONTAP 9 NetApp"]. Estas instruções descrevem etapas adicionais que você deve executar antes e depois de substituir um SED.

* Certifique-se de que a unidade de substituição é suportada pela sua plataforma. Consulte https://hwu.netapp.com["NetApp Hardware Universe"] .
* Certifique-se de que todos os outros componentes do sistema estão a funcionar corretamente; caso contrário, tem de contactar a assistência técnica.


.Sobre esta tarefa
O firmware da unidade é atualizado automaticamente (sem interrupções) em novas unidades com versões de firmware não atuais.

Ao substituir várias unidades de disco, você deve esperar 70 segundos entre a remoção de cada unidade de disco com falha e a inserção da unidade de disco de substituição para permitir que o sistema de armazenamento reconheça a existência de cada novo disco.

.Passos
. Aterre-se corretamente.
. Identifique fisicamente a unidade com falha.
+
Quando uma unidade falha, o sistema Registra uma mensagem de aviso no console do sistema indicando qual unidade falhou. Além disso, o LED atenção (âmbar) no painel de visualização do operador da prateleira de acionamento e a unidade com falha acendem-se.

+

NOTE: O LED de atividade (verde) em uma unidade com falha pode ser iluminado (sólido), o que indica que a unidade tem energia, mas não deve estar piscando, o que indica atividade de e/S. Uma unidade com falha não tem atividade de e/S.

. Remova a unidade com falha:
+
.. Prima o botão de libertação na superfície da unidade para abrir a pega do excêntrico.
.. Deslize a unidade para fora da prateleira usando a alça do came e apoiando a unidade com a outra mão.


. Aguarde, no mínimo, 70 segundos antes de inserir a unidade de substituição.
+
Isso permite que o sistema reconheça que uma unidade foi removida.

. Insira a unidade de substituição:
+
.. Com o manípulo do excêntrico na posição aberta, utilize as duas mãos para introduzir a transmissão de substituição.
.. Prima até a unidade parar.
.. Feche a pega do came de forma a que a unidade fique totalmente assente no plano médio e a pega encaixe no devido lugar.
+
Certifique-se de que fecha lentamente a pega do excêntrico de forma a que fique corretamente alinhada com a face da unidade.



. Verifique se o LED de atividade (verde) da unidade está aceso.
+
Quando o LED de atividade da unidade está sólido, significa que a unidade tem energia. Quando o LED de atividade da unidade está intermitente, significa que a unidade tem alimentação e e/S está em curso. Se o firmware da unidade estiver sendo atualizado automaticamente, o LED pisca.

. Se estiver substituindo outra unidade, repita as etapas 2 a 6.
. Devolva a peça com falha ao NetApp, conforme descrito nas instruções de RMA fornecidas com o kit.
+
Entre em Contato com o suporte técnico em https://mysupport.netapp.com/site/global/dashboard["Suporte à NetApp"], 888-463-8277 (América do Norte), 00-800-44-638277 (Europa) ou 800-800-80-800 (Ásia/Pacífico) se precisar do número de RMA ou de ajuda adicional com o procedimento de substituição.


