---
permalink: a70-90/install-complete.html 
sidebar: sidebar 
keywords: aff a70, a90, prepare installation 
summary: Depois de ativar o sistema de armazenamento AFF A70 ou AFF A90, você estará pronto para descobrir a rede de cluster e configurar um cluster ONTAP. 
---
= Configuração e configuração completas do sistema de storage - AFF A70 e AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de ativar o sistema de armazenamento AFF A70 ou AFF A90, você estará pronto para descobrir a rede de cluster e configurar um cluster ONTAP.



== Etapa 1: Reunir informações do cluster

Se ainda não o tiver feito, reúna as informações necessárias para configurar o cluster, como a porta da interface de gerenciamento de cluster e o endereço IP.

Utilize o https://docs.netapp.com/us-en/ontap/software_setup/index.html["folha de cálculo de configuração do cluster"^] para registar os valores de que necessita durante o processo de configuração do cluster. Se um valor padrão for fornecido, você pode usar esse valor ou então digitar o seu próprio.



== Passo 2: Descubra a rede de cluster

O processo de descoberta permite que você descubra os controladores do sistema de storage na rede.

[role="tabbed-block"]
====
.Opção 1: A deteção de rede está ativada
--
Se tiver a deteção de rede ativada no seu computador portátil, pode concluir a configuração e a configuração utilizando a deteção automática de cluster.

.Passos
. Ligue o computador portátil ao comutador de gestão e aceda aos computadores e dispositivos de rede.
. Selecione um ícone ONTAP listado para descobrir:
+
image::../media/drw_autodiscovery_controler_select_ieops-1849.svg[Como descobrir os controladores com o Explorador de ficheiros do Windows]

+
.. Abra o Explorador de ficheiros.
.. Clique em *rede* no painel esquerdo e clique com o botão direito do rato e selecione *atualizar*.
.. Clique duas vezes no ícone ONTAP e aceite quaisquer certificados exibidos na tela.
+

NOTE: XXXXX é o número de série do sistema de armazenamento para o nó de destino.



+
O System Manager é aberto.



--
.Opção 2: A deteção de rede não está ativada
--
Se a deteção de rede não estiver ativada no computador portátil, conclua a configuração e a configuração utilizando o assistente de configuração de cluster da interface de linha de comando (CLI) do ONTAP.

.Antes de começar
Verifique se o laptop está conetado à porta do console serial e se os controladores estão ligados. link:install-power-hardware.html#step-2-power-on-the-controllers["ligue o sistema de armazenamento"]Consulte para obter instruções.

.Passos
Atribua um endereço IP de gerenciamento de nó inicial a um dos nós.

[cols="1,2"]
|===
| Se a rede de gestão tiver DHCP... | Então... 


 a| 
Configurado
 a| 
Registre o endereço IP atribuído aos novos controladores.



 a| 
Não configurado
 a| 
. Abra uma sessão de console usando PuTTY, um servidor de terminal ou o equivalente para o seu ambiente.
+

NOTE: Verifique a ajuda on-line do seu laptop ou console se você não sabe como configurar o PuTTY.

. Conete-se ao console do primeiro nó.
+
O nó é inicializado e, em seguida, o assistente Configuração de cluster é iniciado no console.

. Insira o endereço IP de gerenciamento do nó quando solicitado pelo assistente Configuração do cluster.


|===
--
====


== Etapa 3: Configure seu cluster

A NetApp recomenda que você use o Gerenciador de sistemas para configurar novos clusters.  https://docs.netapp.com/us-en/ontap/task_configure_ontap.html["Configure o ONTAP em um novo cluster com o Gerenciador do sistema"^]Consulte para obter instruções de configuração.

O System Manager fornece um fluxo de trabalho simples e fácil para configuração e configuração de cluster, incluindo a atribuição de um endereço IP de gerenciamento de nós, a inicialização do cluster, a criação de um nível local, a configuração de protocolos e o provisionamento inicial do armazenamento anexado.

.O que se segue?
Depois que o cluster for inicializado, baixe e execute https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"] para confirmar a configuração.
