---
permalink: a70-90/io-module-overview.html 
sidebar: sidebar 
keywords: AFF A90, AFF A70, replace io module 
summary: Você pode substituir um módulo de e/S com falha em seu sistema de storage AFF A70 ou AFF A90 pelo mesmo tipo de módulo de e/S ou por um tipo diferente de módulo de e/S. Você também pode adicionar um módulo de e/S a um sistema com slots vazios. 
---
= Descrição geral de adicionar e substituir um módulo de e/S - AFF A70 e AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os sistemas AFF A70 e AFF A90 oferecem flexibilidade na expansão ou substituição de módulos de e/S para melhorar a conetividade e o desempenho da rede. Adicionar ou substituir um módulo de e/S é essencial ao atualizar recursos de rede ou endereçar um módulo com falha.

Você pode substituir um módulo de e/S com falha em seu sistema de storage AFF A70 ou AFF A90 pelo mesmo tipo de módulo de e/S ou por um tipo diferente de módulo de e/S. Você também pode adicionar um módulo de e/S a um sistema com slots vazios.

* link:io-module-add.html["Adicione um módulo de e/S."]
+
Adicionar módulos adicionais pode melhorar a redundância, ajudando a garantir que o sistema permaneça operacional mesmo que um módulo falhe.

* link:io-module-replace.html["Substitua um módulo de e/S."]
+
A substituição de um módulo de e/S com falha pode restaurar o sistema ao seu estado de funcionamento ideal.



.Numeração de slots de e/S.
Os slots de e/S nos controladores AFF A70 e AFF A90 estão numerados de 1 a 11, como mostrado na ilustração a seguir.

image::../media/drw_a1K_back_slots_labeled_ieops-2162.svg[Numeração de slots em controladores AFF A70 e AFF A90]
