---
permalink: afx-2k/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: afx 2k, shutdown the controller 
summary: Desligue o controlador do seu sistema de storage afx 2k para evitar perda de dados e garantir a estabilidade do sistema ao substituir o chassi. 
---
= Desligue o controlador para substituir o chassi - AFX 2K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Desligue o controlador do seu sistema de storage AFX 2K para evitar perda de dados e garantir a estabilidade do sistema ao substituir o chassi.

Assuma o controle e interrompa o controlador com defeito para que o controlador em bom estado continue a fornecer dados do armazenamento do controlador com defeito. Para fazer isso, você suprime a criação automática de casos em AutoSupport, desativa o giveback automático e leva o controlador com defeito ao prompt LOADER. O prompt LOADER é o estado de parada segura a partir do qual você pode substituir a FRU.

.Sobre esta tarefa
* Se você tiver um cluster com mais de quatro nós, ele deverá estar no quorum.  Para visualizar informações de cluster sobre seus nós, use o `cluster show` comando.  Para mais informações sobre o `cluster show` comando, vejalink:https://docs.netapp.com/us-en/ontap/system-admin/display-nodes-cluster-task.html["Exibir detalhes no nível do nó em um cluster ONTAP"^] .
* Se o cluster não estiver em quorum ou se a integridade ou elegibilidade de qualquer controlador (exceto o controlador com defeito) for mostrada como falsa, você deverá corrigir o problema antes de desligar o controlador com defeito. Ver link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Sincronize um nó com o cluster"^] .


.Passos
. Se o AutoSupport estiver ativado, suprimir a criação automática de casos invocando uma mensagem AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`

+
A seguinte mensagem AutoSupport suprime a criação automática de casos por duas horas:

+
`cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. Desabilitar o retorno automático do console do controlador prejudicado:
+
`storage failover modify -node impaired-node -auto-giveback-of false`

+

NOTE: Quando você vir _Deseja desabilitar o retorno automático?_, digite `y` .

. Leve o controlador prejudicado para o prompt Loader:
+
[cols="1,2"]
|===
| Se o controlador afetado estiver a apresentar... | Então... 


 a| 
O prompt Loader
 a| 
Vá para a próxima etapa.



 a| 
Prompt do sistema ou prompt de senha
 a| 
Assuma ou interrompa o controlador prejudicado do controlador saudável:
`storage failover takeover -ofnode _impaired_node_name_ -halt _true_`

O parâmetro _-halt true_ leva o nó prejudicado ao prompt do LOADER.

|===


.O que se segue?
Depois de desligar o controlador, é necessário link:chassis-replace-move-hardware.html["substitua o chassis"].
