---
permalink: a900/bootmedia_replace_overview.html 
sidebar: sidebar 
keywords: AFF A900 
summary: A mídia de inicialização armazena um conjunto primário e um secundário de arquivos de sistema que o sistema utiliza ao inicializar. Dependendo da sua configuração de rede, você pode realizar uma substituição sem interrupção ou com interrupção. 
---
= Substitua o suporte de arranque - AFF A900
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A Mídia de inicialização armazena um conjunto primário e secundário de arquivos do sistema (imagem de inicialização) que o sistema usa quando ele é inicializado. Dependendo da configuração da rede, você pode realizar uma substituição sem interrupções ou disruptiva.

[NOTE]
====
NetApp recomenda fortemente que você habilite o registro de logs no console nos dispositivos que estiver utilizando e execute as seguintes ações ao realizar este procedimento:

* Deixe AutoSupport ativado durante a sua manutenção. Isso permite que o suporte da NetApp receba informações de diagnóstico caso ocorram problemas.
* Habilite o registro de sessão para todas as sessões da CLI. Isso cria um registro completo de todos os comandos e da saída do sistema durante a atividade de manutenção. Para obter orientações sobre como habilitar o registro de sessão, consulte  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Como configurar o PuTTY para obter conectividade ideal com sistemas ONTAP"^].


====
Tem de ter uma unidade flash USB, formatada para FAT32, com a quantidade de armazenamento adequada para guardar o `image_xxx.tgz` ficheiro.

Você também deve copiar o `image_xxx.tgz` arquivo para a unidade flash USB para uso posterior neste procedimento.

* Os métodos sem interrupções e disruptivos para substituir uma Mídia de inicialização exigem que você restaure o `var` sistema de arquivos:
+
** Para substituição sem interrupções, o par de HA não requer conexão com uma rede para restaurar o `var` sistema de arquivos. O par de HA em um único chassi tem uma conexão e0S interna, que é usada para transferir `var` a configuração entre eles.
** Para a substituição disruptiva, não é necessário uma ligação de rede para restaurar o `var` sistema de ficheiros, mas o processo requer duas reinicializações.


* Você deve substituir o componente com falha por um componente FRU de substituição que você recebeu da NetApp.
* É importante que você aplique os comandos nestas etapas no controlador correto:
+
** O controlador _prejudicado_ é o controlador no qual você está realizando a manutenção.
** O controlador _Healthy_ é o parceiro de HA do controlador prejudicado.



