---
permalink: a900/controller_replace_overview.html 
sidebar: sidebar 
keywords: AFF A900 
summary: Tem de rever os pré-requisitos para o procedimento de substituição e selecionar o correto para a sua versão do sistema operativo ONTAP. 
---
= Substitua o módulo do controlador - AFF A900
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para substituir o módulo do controlador desativado, tem de desligar o controlador desativado, mover os componentes internos para o módulo do controlador de substituição, instalar o módulo do controlador de substituição e reiniciar o controlador de substituição.

.Antes de começar
Tem de rever os pré-requisitos para o procedimento de substituição e selecionar o correto para a sua versão do sistema operativo ONTAP.

[NOTE]
====
NetApp recomenda fortemente que você habilite o registro de logs no console nos dispositivos que estiver utilizando e execute as seguintes ações ao realizar este procedimento:

* Deixe AutoSupport ativado durante a sua manutenção. Isso permite que o suporte da NetApp receba informações de diagnóstico caso ocorram problemas.
* Habilite o registro de sessão para todas as sessões da CLI. Isso cria um registro completo de todos os comandos e da saída do sistema durante a atividade de manutenção. Para obter orientações sobre como habilitar o registro de sessão, consulte  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Como configurar o PuTTY para obter conectividade ideal com sistemas ONTAP"^].


====
* Todas as gavetas de unidades devem estar funcionando corretamente.
* Se o seu sistema tiver uma licença V_StorageAttach, você deve consultar as etapas adicionais necessárias antes de executar este procedimento.
* Se o seu sistema estiver em um par de HA, o controlador saudável deve ser capaz de assumir o controlador que está sendo substituído (referido neste procedimento como ""controlador prejudicado"").
* Se o sistema estiver em uma configuração do MetroCluster, você deverá revisar a seção https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["Escolher o procedimento de recuperação correto"] para determinar se deve usar esse procedimento.
+
Se esse for o procedimento que você deve usar, observe que o procedimento de substituição da controladora de um controlador em uma configuração de MetroCluster de quatro ou oito nós é o mesmo que em um par de HA. Nenhuma etapa específica do MetroCluster é necessária porque a falha é restrita a um par de HA e os comandos de failover de storage podem ser usados para fornecer operações sem interrupções durante a substituição.

* Você deve substituir o componente com falha por um componente FRU de substituição que você recebeu de seu provedor.
* Você deve estar substituindo um módulo de controlador por um módulo de controlador do mesmo tipo de modelo. Você não pode atualizar seu sistema apenas substituindo o módulo do controlador.
* Não é possível alterar nenhuma unidade ou compartimentos de unidades como parte deste procedimento.
* Neste procedimento, o dispositivo de inicialização é movido do controlador prejudicado para o controlador de substituição, de modo que o controlador de substituição será inicializado na mesma versão do ONTAP que o módulo do controlador antigo.
* É importante que você aplique os comandos nessas etapas nos sistemas corretos:
+
** O controlador prejudicado é o controlador que está a ser substituído.
** O controlador de substituição é o novo controlador que está substituindo o controlador prejudicado.
** O controlador saudável é o controlador sobrevivente.



