---
permalink: a900/overview.html 
sidebar: sidebar 
summary: Especificações principais para o grupo de plataformas A900 
---
= Especificações principais do AFF A900
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A seguir estão especificações selecionadas para o sistema de armazenamento AFF A900 em um único par de alta disponibilidade.  Visite o NetApp Hardware Universe (HWU) para obter as especificações completas deste sistema de armazenamento.



== Especificações principais do AFF A900

* Configuração da plataforma: Par de HA de chassi único AFF A900
* Capacidade Máxima de Bruto: 14.6880 PB
* Memória: 2048.0000 GB
* Fator de forma: chassi 8U com 2 controladores HA
* Versão ONTAP : ONTAP: 9.16.1P2
* Slots de expansão PCIe: 20
* Versão mínima do ONTAP : ONTAP 9.10.1RC2 == Máximos de escalonamento
* Tipo: NAS; Pares HA: 12; Capacidade bruta: 176,3 PB / 156,5 PiB; Memória máxima: 24576 GB
* Tipo: SAN; Pares HA: 6; Capacidade bruta: 88,1 PB / 78,3 PiB; Memória máxima: 12288 GB
* Tipo: Par HA; Capacidade bruta: 14,7 PB / 13,0 PiB; Memória máxima: 2048.0000




== E/S



=== E/S integradas

Não há dados de E/S integrados.



=== Total de E/S

* Protocolo: Ethernet 100 Gbps; Portas: 32
* Protocolo: Ethernet 25 Gbps; Portas: 64
* Protocolo: Ethernet 10 Gbps; Portas: 64
* Protocolo: FC 32 Gbps; Portas: 64
* Protocolo: NVMe/FC 32 Gbps; Portas: 64
* Portas: 0
* Protocolo: SAS 12 Gbps; Portas: 64




=== Portas de gerenciamento

* Protocolo: Ethernet 1 Gbps; Portas: 2
* Protocolo: RS-232 115 Kbps; Portas: 6
* Protocolo: USB 12 Mbps; Portas: 2




== Rede de armazenamento suportada

* CIFS
* FC
* iSCSI
* NFS v3
* NFS v4.0
* NFS v4.1
* NFS v4.2
* NVMe/FC
* NVMe/TCP
* S3
* S3 com NAS
* SMB 2.0
* SMB 2.1
* SMB 2.x
* SMB 3.0
* SMB 3.1
* SMB 3.1.1 == Especificações do ambiente do sistema
* Potência típica: 8004 BTU/h
* Pior cenário de potência: 9937 BTU/h
* Peso: 220,5 lb 100,0 kg
* Altura: 8U
* Largura: 19” compatível com rack IEC (17,7” 45,0 cm)
* Profundidade: 28,8” (36,8” com suporte de gerenciamento de cabos)
* Temperatura/Altitude/Umidade de operação: 10°C a 35°C (50°F a 95°F) a 3048 m (10000 pés) de altitude; 8% a 80% de umidade relativa, sem condensação
* Temperatura/Umidade fora de operação: -40°C a 70°C (-40°F a 158°F) até 12192m (40000 pés) 10% a 95% de umidade relativa, sem condensação, no recipiente original
* Ruído acústico: Potência sonora declarada (LwAd): 7,4 Pressão sonora (LpAm) (posições de observação): 65,0 dB




== Conformidade

* Certificações EMC/EMI: AMCA, FCC, ICES, KC, Marrocos, VCCI
* Certificações de segurança: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificações Segurança/EMC/EMI: EAC, UKRSEPRO
* Certificações Segurança/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normas EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normas de segurança: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




== Alta disponibilidade

* Controlador de gerenciamento de placa base baseado em Ethernet (BMC) e interface de gerenciamento ONTAP
* Controladores redundantes hot-swappable
* Fontes de alimentação redundantes com troca a quente
* Gerenciamento de banda SAS em conexões SAS

