---
permalink: asa800/overview.html 
sidebar: sidebar 
keywords: ASA A800 specifications, ASA A800 specs, NetApp ASA A800, ASA A800 hardware 
summary: Especificações principais para o sistema de armazenamento ASA A800 
---
= Especificações principais do ASA A800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A seguir estão algumas especificações selecionadas para o ASA A800.  Visita https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) para uma lista completa das especificações ASA A800 .  Esta página reflete um único par de alta disponibilidade.



=== Especificações principais do ASA A800

Configuração da plataforma: Par de HA de chassi único ASA A800

Capacidade máxima de matéria-prima: 6,6096 PB

Memória: 1280.0000 GB

Fator de forma: chassi 4U com 2 controladores HA e 48 slots de unidade

Versão ONTAP : b_startONTAP: 9.16.1P2b_end

Slots de expansão PCIe: 10

Versão mínima do ONTAP : ONTAP 9.13.1



=== Máximos de Escalabilidade

|===


| Tipo | Pares HA | Capacidade bruta | Memória Máxima 


| NAS |  |  |  


| SAN | 6 | 39,7 PB / 35,2 PiB | 7680 GB 


| Par HA |  | 6,6 PB / 5,9 PiB | 1280,0000 
|===


=== IO



==== IO integrado

|===


| Protocolo | Portos 


| Ethernet 100 Gbps | 4 
|===


==== Total de IO

|===


| Protocolo | Portos 


| Ethernet 100 Gbps | 20 


| Ethernet 25 Gbps | 16 


| Ethernet 10 Gbps | 32 


| FC 32 Gbps | 32 


| NVMe/FC 32 Gbps | 32 


|  | 0 


|  | 0 


| SAS 12 Gbps | 32 
|===


==== Portas de Gestão

|===


| Protocolo | Portos 


| Ethernet 1 Gbps | 4 


| RS-232 115 Kbps | 4 


| USB 12 Mbps | 4 
|===


=== Rede de armazenamento suportada

FC; iSCSI; NVMe/FC; NVMe/TCP;



=== Especificações do ambiente do sistema

Não há dados ambientais disponíveis.



=== Conformidade

* Certificações EMC/EMI: AMCA, FCC, ICES, KC, Marrocos, VCCI
* Certificações de segurança: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificações Segurança/EMC/EMI: EAC, UKRSEPRO
* Certificações Segurança/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normas EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normas de segurança: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilidade

Controlador de gerenciamento de placa de base baseado em Ethernet (BMC) e interface de gerenciamento ONTAP ; Controladores redundantes de troca a quente; Fontes de alimentação redundantes de troca a quente; Gerenciamento SAS em banda por meio de conexões SAS para prateleiras externas; [//] 2025-10-15 ontap-systems-internal/issues/1357
