---
permalink: a200/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: aff a200, nondisruptive, disruptive, replace the boot media, manual, manual boot recovery 
summary: A mídia de inicialização armazena um conjunto primário e um conjunto secundário de arquivos de imagem de inicialização do sistema que o sistema usa ao inicializar. Dependendo da sua configuração de rede, você pode realizar uma substituição sem interrupção ou com interrupção. O sistema AFF A200 suporta apenas procedimentos manuais de recuperação da mídia de inicialização. 
---
= Descrição geral da substituição do suporte de arranque - AFF A200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A mídia de inicialização armazena um conjunto primário e um conjunto secundário de arquivos de sistema (imagem de inicialização) que o sistema usa ao iniciar. Dependendo da configuração da sua rede, você pode realizar uma substituição sem interrupção ou com interrupção. O sistema AFF A200 suporta apenas procedimentos manuais de recuperação de mídia de inicialização. A recuperação automática de mídia de inicialização não é suportada.

[NOTE]
====
NetApp recomenda fortemente que você habilite o registro de logs no console nos dispositivos que estiver utilizando e execute as seguintes ações ao realizar este procedimento:

* Deixe AutoSupport ativado durante a sua manutenção. Isso permite que o suporte da NetApp receba informações de diagnóstico caso ocorram problemas.
* Habilite o registro de sessão para todas as sessões da CLI. Isso cria um registro completo de todos os comandos e da saída do sistema durante a atividade de manutenção. Para obter orientações sobre como habilitar o registro de sessão, consulte  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Como configurar o PuTTY para obter conectividade ideal com sistemas ONTAP"^].


====
.O que você vai precisar
Tem de ter uma unidade flash USB, formatada para FAT32, com a quantidade de armazenamento adequada para guardar o `image_xxx.tgz` ficheiro.

.Antes de começar
* Os métodos sem interrupções e disruptivos para substituir uma Mídia de inicialização exigem que você restaure o sistema de arquivos var:
+
** Para substituição sem interrupções, o par de HA deve ser conetado a uma rede para restaurar o sistema de arquivos var.
** Para a substituição disruptiva, não é necessário uma ligação de rede para restaurar o sistema de ficheiros var, mas o processo requer duas reinicializações.


* Você deve substituir o componente com falha por um componente FRU de substituição que você recebeu de seu provedor.
* É importante que você aplique os comandos nestas etapas no controlador correto:
+
** O controlador _prejudicado_ é o controlador no qual você está realizando a manutenção.
** O controlador _Healthy_ é o parceiro de HA do controlador prejudicado.



