---
permalink: a200/controller-replace-overview.html 
sidebar: sidebar 
keywords: aff a200, prerequisite, replace the controller module 
summary: Tem de rever os pré-requisitos para o procedimento de substituição e selecionar o correto para a sua versão do sistema operativo ONTAP. 
---
= Descrição geral da substituição do módulo do controlador - AFF A200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tem de rever os pré-requisitos para o procedimento de substituição e selecionar o correto para a sua versão do sistema operativo ONTAP.

.O que você vai precisar
* Todas as gavetas de unidades devem estar funcionando corretamente.
* Se o seu sistema estiver em um par de HA, o controlador saudável deve ser capaz de assumir o controlador que está sendo substituído (referido neste procedimento como o "'nó prejudicado'").


.Sobre esta tarefa
* Você deve substituir o componente com falha por um componente FRU de substituição que você recebeu de seu provedor.
* É necessário substituir um módulo controlador por um módulo controlador do mesmo tipo de modelo. Você não pode atualizar seu sistema apenas substituindo o módulo do controlador.
* Não é possível alterar nenhuma unidade ou compartimentos de unidades como parte deste procedimento.
* Neste procedimento, o dispositivo de inicialização é movido do controlador prejudicado para o nó _replacement_ de modo que o nó _replacement_ inicialize na mesma versão do ONTAP que o módulo controlador antigo.
* É importante que você aplique os comandos nessas etapas nos sistemas corretos:
+
** O nó _prejudicado_ é o controlador que está sendo substituído.
** O nó _replacement_ é o novo controlador que está substituindo o controlador prejudicado.
** O nó _Healthy_ é o controlador sobrevivente.


* Você deve sempre capturar a saída do console do controlador para um arquivo de texto.
+
Isso fornece um Registro do procedimento para que você possa solucionar qualquer problema que possa encontrar durante o processo de substituição.


