---
permalink: a220/chassis-replace-overview.html 
sidebar: sidebar 
keywords: aff a220, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap 
summary: Substituir um chassis com deficiência o novo chassis do mesmo modelo que o chassis com deficiência. 
---
= Analise os requisitos antes de substituir o chassi AFF A220
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de substituir o chassi do seu AFF A220, revise os requisitos para uma substituição bem-sucedida. O procedimento de substituição do chassi transfere todas as fontes de alimentação, unidades de disco e módulos de controle do chassi com problema para o chassi de substituição e é um processo disruptivo.

Para substituir o chassi, você deve mover as fontes de alimentação, os discos rígidos e o módulo ou módulos do controlador do chassi com deficiência para o novo chassi e trocar o chassi com deficiência do rack de equipamentos ou do gabinete do sistema pelo novo chassi do mesmo modelo que o chassi com deficiência.

Todos os outros componentes do sistema devem estar funcionando corretamente; caso contrário, você deve entrar em Contato com o suporte técnico.

* Pode utilizar este procedimento com todas as versões do ONTAP suportadas pelo seu sistema.
* Este procedimento é escrito com a suposição de que você está movendo todas as unidades e módulos de controladora ou módulos para o novo chassi e que o chassi é um novo componente da NetApp.
* Este procedimento é disruptivo. Para um cluster de duas controladoras, você terá uma interrupção de serviço completa e uma interrupção parcial em um cluster de vários nós.

