---
settings:
  name: Install and maintain
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de sistemas de hardware ONTAP
    url: "/index.html"
  - title: Notas de lançamento
    entries:
    - title: Novidades para os sistemas de hardware ONTAP
      url: "/whats-new.html"
    - title: Compatibilidade de hardware e software ONTAP
      url: "/supported-platforms.html"
    - title: Fim do suporte
      url: "/eoa-hardware.html"
  - title: Início rápido
    url: "/get-up-and-run.html"
  - title: Sistemas AFF
    url: "/aff-landing/index.html"
    entries:
    - title: Sistemas a-Series
      url: "/aff-aseries/index.html"
      entries:
      - section: a1k
      - section: a70-90
      - section: a20-30-50
      - section: a150
      - section: a250
      - section: a400
      - section: a800
      - section: a900
    - title: Sistemas C-Series
      url: "/aff-cseries/index.html"
      entries:
      - section: c30-60
      - section: c80
      - section: c250
      - section: c400
  - title: Sistemas AFX
    url: "/afx/index.html"
    entries:
    - title: Instalar e configurar
      url: "/afx/afx-install-setup.html"
    - title: Manutenção
      pdf-filename: Manutenção AFX
      url: "/afx-landing-maintain/index.html"
      entries:
      - title: Visão geral da manutenção
        url: "/afx-1k/maintain-overview.html"
      - title: Suporte de arranque
        pdf-filename: Mídia de inicialização AFX 1K
        entries:
        - title: Fluxo de trabalho de substituição de Mídia de inicialização
          url: "/afx-1k/bootmedia-replace-workflow.html"
        - title: Rever os requisitos
          url: "/afx-1k/bootmedia-replace-requirements.html"
        - title: Desligue o controlador
          url: "/afx-1k/bootmedia-shutdown.html"
        - title: Substitua o suporte de arranque
          url: "/afx-1k/bootmedia-replace.html"
        - title: Restaurar mídia de inicialização
          url: "/afx-1k/bootmedia-recovery-image-boot.html"
        - title: Devolver artigo com falha ao NetApp
          url: "/afx-1k/bootmedia-complete-rma.html"
      - title: Chassis
        pdf-filename: Chassi AFX A1K
        entries:
        - title: Fluxo de trabalho de substituição do chassis
          url: "/afx-1k/chassis-replace-workflow.html"
        - title: Rever os requisitos
          url: "/afx-1k/chassis-replace-requirements.html"
        - title: Prepare-se para substituir
          url: "/afx-1k/chassis-replace-prepare.html"
        - title: Desligue o controlador
          url: "/afx-1k/chassis-replace-shutdown.html"
        - title: Substitua o chassi
          url: "/afx-1k/chassis-replace-move-hardware.html"
        - title: Substituição completa do chassis
          url: "/afx-1k/chassis-replace-complete-system-restore-rma.html"
      - title: Controlador
        pdf-filename: Controlador AFX 1K
        entries:
        - title: Fluxo de trabalho de substituição do controlador
          url: "/afx-1k/controller-replace-workflow.html"
        - title: Rever os requisitos
          url: "/afx-1k/controller-replace-requirements.html"
        - title: Desligue o controlador desativado
          url: "/afx-1k/controller-replace-shutdown.html"
        - title: Substitua o controlador
          url: "/afx-1k/controller-replace-move-hardware.html"
        - title: Restaure a configuração do sistema
          url: "/afx-1k/controller-replace-system-config-restore-and-verify.html"
        - title: Devolver o controlador
          url: "/afx-1k/controller-replace-recable-reassign-disks.html"
        - title: Substituição completa do controlador
          url: "/afx-1k/controller-replace-restore-system-rma.html"
      - title: DIMM
        url: "/afx-1k/dimm-replace.html"
      - title: Ventoinha
        url: "/afx-1k/fan-replace.html"
      - title: NVRAM
        url: "/afx-1k/nvram-replace.html"
      - title: Bateria NV
        url: "/afx-1k/nvdimm-battery-replace.html"
      - title: Módulo de e/S.
        pdf-filename: Módulo AFX 1K IO
        entries:
        - title: Descrição geral do módulo I/O.
          url: "/afx-1k/io-module-overview.html"
        - title: Adicionar módulo de e/S.
          url: "/afx-1k/io-module-add.html"
        - title: Módulo de E/S substituição a quente
          url: "/afx-1k/io-module-hotswap.html"
        - title: Substitua o módulo de e/S.
          url: "/afx-1k/io-module-replace.html"
      - title: Fonte de alimentação
        url: "/afx-1k/power-supply-replace.html"
      - title: Bateria de relógio em tempo real
        url: "/afx-1k/rtc-battery-replace.html"
      - title: Módulo de gestão do sistema
        url: "/afx-1k/system-management-replace.html"
  - title: Sistemas ASA
    url: "/allsan-landing/index.html"
    entries:
    - section: asa150
    - section: asa250
    - section: asa400
    - section: asa800
    - section: asa900
  - title: Sistemas ASA R2
    url: "/asa-r2/index.html"
    entries:
    - title: Instalar e configurar
      url: "/asa-r2/asa-r2-install-setup.html"
    - title: Manutenção
      url: "/asa-r2-landing-maintain/index.html"
      entries:
      - section: asa-r2-a1k-maintain
      - section: asa-r2-a70-90-maintain
      - section: asa-r2-a20-30-50-maintain
      - section: asa-r2-c30-maintain
    - section: asa-r2-key-specifications
  - title: Sistemas FAS
    url: "/fas/index.html"
    entries:
    - section: fas50
    - section: fas-70-90
    - section: fas2700
    - section: fas2800
    - section: fas8300
    - section: fas9500
  - title: Sistemas de fim de disponibilidade
    url: "/endofavail/index.html"
    entries:
    - section: a200
    - section: a220
    - section: a300
    - section: a320
    - section: a700
    - section: a700s
    - section: asa-c250
    - section: asa-c400
    - section: asa-c800
    - section: c190
    - section: c800
    - section: fas2600
    - section: fas500f
    - section: fas8200
    - section: fas9000
    - title: Outros modelos
      url: "/other/other-models.html"
  - title: Compartimentos de unidades
    url: "/drive-shelves/index.html"
    entries:
    - section: ns224
    - section: nx224
    - section: sas3
  - title: Kits de gabinete e trilho
    entries:
    - title: Kit SuperRail
      url: "/platform-supplemental/superrail-install.html"
    - title: Kit de calha de duas colunas AFF A700/FAS9000
      url: "/platform-supplemental/telco-installation-instructions.html"
    - title: Armário de sistema de 42U 1280 mm
      entries:
      - title: Prepare-se para instalar o gabinete
        entries:
        - title: Caraterísticas do gabinete
          url: "/platform-supplemental/42u-1280mm-features.html"
        - title: Ferramentas/equipamento necessários
          url: "/platform-supplemental/42u-1280mm-required-tools.html"
        - title: Requisitos de espaço e dimensões do gabinete
          url: "/platform-supplemental/42u-1280mm-space-and-dimensions.html"
        - title: Tipos e especificações de PDU suportados
          url: "/platform-supplemental/42u-1280mm-supported-pdu-types-and-specifications.html"
      - title: Desembale o gabinete do sistema
        url: "/platform-supplemental/42u-1280mm-unpack.html"
      - title: Instale o gabinete
        entries:
        - title: Visão geral
          url: "/platform-supplemental/42u-1280mm-install.html"
        - title: Instale o kit de interconexão do gabinete
          url: "/platform-supplemental/42u-1280mm-install-cabinet-interconnect-kit.html"
        - title: Instale o kit de aparafusar
          url: "/platform-supplemental/42u-1280mm-install-bolt-down-kit.html"
        - title: Instale os trilhos de suporte
          url: "/platform-supplemental/42u-1280mm-install-additional-rails.html"
        - title: Instale o equipamento
          url: "/platform-supplemental/42u-1280mm-install-equipment.html"
        - title: Ligue o gabinete
          url: "/platform-supplemental/42u-1280mm-power-on.html"
      - title: Substitua as PDUs
        url: "/platform-supplemental/42u-1280mm-replace-pdus.html"
      - title: Porta dianteira do armário de marcha-atrás
        entries:
        - title: O que você precisa
          url: "/platform-supplemental/42u-1280mm-reverse-front-door.html"
        - title: Retire o emblema iluminado
          url: "/platform-supplemental/42u-1280mm-remove-illuminated-badge.html"
        - title: Remova a porta do armário
          url: "/platform-supplemental/42u-1280mm-remove-door.html"
        - title: Mova a fonte de alimentação e o cabeamento do emblema
          url: "/platform-supplemental/42u-1280mm-move-badge-ps-and-cabling.html"
        - title: Dobradiça da porta de marcha-atrás e trinco de bloqueio
          url: "/platform-supplemental/42u-1280mm-reverse-hinge-and-lock.html"
        - title: Reinstale a porta e o emblema iluminado
          url: "/platform-supplemental/42u-1280mm-reinstall-door-and-badge.html"
  - title: Procedimentos de substituição por componente
    url: "/fru-reference/index.html"
    entries:
    - title: Suporte de arranque
      url: "/fru-reference/bootmedia-fru-links.html"
    - title: Módulo de armazenamento em cache
      url: "/fru-reference/caching-module-fru-links.html"
    - title: Chassis
      url: "/fru-reference/chassis-fru-links.html"
    - title: Controlador
      url: "/fru-reference/controller-fru-links.html"
    - title: Módulo de potência DCPM
      url: "/fru-reference/dcpm-power-fru-links.html"
    - title: DIMM
      url: "/fru-reference/dimm-fru-links.html"
    - title: Condução
      url: "/fru-reference/drive-fru-links.html"
    - title: Ventoinha
      url: "/fru-reference/fan-fru-links.html"
    - title: Módulo de e/S.
      url: "/fru-reference/io-module-fru-links.html"
    - title: Módulo LED
      url: "/fru-reference/led-module-fru-links.html"
    - title: Mezanino
      url: "/fru-reference/mezzanine-fru-links.html"
    - title: NVDIMM
      url: "/fru-reference/nvdimm-fru-links.html"
    - title: Bateria NVMEM/ NVRAM
      url: "/fru-reference/nvmem-battery-fru-links.html"
    - title: Módulo NVRAM
      url: "/fru-reference/nvram-module-fru-links.html"
    - title: NSM
      url: "/fru-reference/nsm-fru-links.html"
    - title: Placas PCI e risers
      url: "/fru-reference/pci-cards-fru-links.html"
    - title: Fonte de alimentação
      url: "/fru-reference/power-supply-fru-links.html"
    - title: Bateria RTC
      url: "/fru-reference/rtc-battery-fru-links.html"
    - title: Módulo de gestão do sistema
      url: "/fru-reference/system-management-fru-links.html"
  - title: Avisos legais
    url: "/legal-notices.html"
product-family:
  name: ONTAP hardware systems
  repo: ontap-systems-family
