---
settings:
  name: Install and maintain
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de sistemas de hardware ONTAP
    url: "/index.html"
  - title: Notas de lançamento
    entries:
    - title: Novidades para os sistemas de hardware ONTAP
      url: "/whats-new.html"
    - title: Compatibilidade de hardware e software ONTAP
      url: "/supported-platforms.html"
    - title: Fim do suporte
      url: "/eoa-hardware.html"
  - title: Comece agora
    url: "/get-up-and-run.html"
  - title: Sistemas AFF
    url: "/aff-landing/index.html"
    entries:
    - title: Sistemas a-Series
      url: "/aff-aseries/index.html"
      entries:
      - section: a1k
      - section: a70-90
      - section: a20-30-50
      - section: a150
      - section: a250
      - section: a400
      - section: a800
      - section: a900
    - title: Sistemas C-Series
      url: "/aff-cseries/index.html"
      entries:
      - section: c30-60
      - section: c80
      - section: c250
      - section: c400
      - section: c800
  - title: Sistemas ASA
    url: "/allsan-landing/index.html"
    entries:
    - title: Sistemas a-Series
      url: "/allsan-a-series/index.html"
      entries:
      - section: asa150
      - section: asa250
      - section: asa400
      - section: asa800
      - section: asa900
    - title: Sistemas C-Series
      url: "/allsan-c-series/index.html"
      entries:
      - section: asa-c250
      - section: asa-c-400
      - section: asa-c800
  - title: Sistemas ASA R2
    url: "/asa-r2/index.html"
    entries:
    - title: Instalar e configurar
      url: "/asa-r2/asa-r2-install-setup.html"
    - title: Manutenção
      url: "/asa-r2-landing-maintain/index.html"
      entries:
      - section: asa-r2-a1k-maintain
      - section: asa-r2-a70-90-maintain
  - title: Sistemas FAS
    url: "/fas/index.html"
    entries:
    - section: fas-70-90
    - section: fas2700
    - section: fas2800
    - section: fas8300
    - section: fas9500
  - title: Sistemas de fim de disponibilidade
    url: "/endofavail/index.html"
    entries:
    - section: a200
    - section: a220
    - section: a300
    - section: a320
    - section: a700
    - section: a700s
    - section: c190
    - section: fas2600
    - section: fas500f
    - section: fas8200
    - section: fas9000
    - title: Outros modelos
      url: "/other/other-models.html"
  - title: Compartimentos de unidades
    url: "/drive-shelves/index.html"
    entries:
    - section: ns224
    - section: sas3
  - title: Kits de gabinete e trilho
    entries:
    - title: Kit SuperRail
      url: "/platform-supplemental/superrail-install.html"
    - title: Kit de calha de duas colunas AFF A700/FAS9000
      url: "/platform-supplemental/telco-installation-instructions.html"
    - title: Armário de sistema de 42U 1280 mm
      entries:
      - title: Prepare-se para instalar o gabinete
        entries:
        - title: Caraterísticas do gabinete
          url: "/platform-supplemental/42u-1280mm-features.html"
        - title: Ferramentas/equipamento necessários
          url: "/platform-supplemental/42u-1280mm-required-tools.html"
        - title: Requisitos de espaço e dimensões do gabinete
          url: "/platform-supplemental/42u-1280mm-space-and-dimensions.html"
        - title: Tipos e especificações de PDU suportados
          url: "/platform-supplemental/42u-1280mm-supported-pdu-types-and-specifications.html"
      - title: Desembale o gabinete do sistema
        url: "/platform-supplemental/42u-1280mm-unpack.html"
      - title: Instale o gabinete
        entries:
        - title: Visão geral
          url: "/platform-supplemental/42u-1280mm-install.html"
        - title: Instale o kit de interconexão do gabinete
          url: "/platform-supplemental/42u-1280mm-install-cabinet-interconnect-kit.html"
        - title: Instale o kit de aparafusar
          url: "/platform-supplemental/42u-1280mm-install-bolt-down-kit.html"
        - title: Instale os trilhos de suporte
          url: "/platform-supplemental/42u-1280mm-install-additional-rails.html"
        - title: Instale o equipamento
          url: "/platform-supplemental/42u-1280mm-install-equipment.html"
        - title: Ligue o gabinete
          url: "/platform-supplemental/42u-1280mm-power-on.html"
      - title: Substitua as PDUs
        url: "/platform-supplemental/42u-1280mm-replace-pdus.html"
      - title: Porta dianteira do armário de marcha-atrás
        entries:
        - title: O que você precisa
          url: "/platform-supplemental/42u-1280mm-reverse-front-door.html"
        - title: Retire o emblema iluminado
          url: "/platform-supplemental/42u-1280mm-remove-illuminated-badge.html"
        - title: Remova a porta do armário
          url: "/platform-supplemental/42u-1280mm-remove-door.html"
        - title: Mova a fonte de alimentação e o cabeamento do emblema
          url: "/platform-supplemental/42u-1280mm-move-badge-ps-and-cabling.html"
        - title: Dobradiça da porta de marcha-atrás e trinco de bloqueio
          url: "/platform-supplemental/42u-1280mm-reverse-hinge-and-lock.html"
        - title: Reinstale a porta e o emblema iluminado
          url: "/platform-supplemental/42u-1280mm-reinstall-door-and-badge.html"
  - title: Avisos legais
    url: "/legal-notices.html"
product-family:
  name: ONTAP hardware systems
  repo: ontap-systems-family
