---
sidebar: sidebar 
permalink: supported-platforms.html 
keywords: new, features, asa r2, aff, asa, fas 
summary: Saiba mais sobre a versão com suporte do ONTAP para sua plataforma ou prateleira. 
---
= Compatibilidade de hardware e software ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Os sistemas de storage ONTAP são compatíveis com várias versões do software ONTAP. Saiba mais sobre as versões do ONTAP que seus sistemas de storage e compartimentos de unidades dão suporte.

O suporte completo à configuração e as limitações para sistemas de hardware ONTAP estão disponíveis no  https://hwu.netapp.com["NetApp Hardware Universe"]. Detalhes sobre problemas conhecidos, limitações e avisos de atualização no software ONTAP 9 estão disponíveis no https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 Notas de versão"].

[role="tabbed-block"]
====
.Sistemas AFF
--
Os sistemas AFF A-Series e AFF C-Series oferecem uma plataforma robusta, com escalabilidade horizontal, adaptada para ambientes virtualizados. Eles podem ser implantados como sistemas autônomos ou como camadas de alta performance nas configurações do NetApp ONTAP. link:https://www.netapp.com/data-storage/all-flash-san-storage-array["Saiba mais sobre os sistemas AFF"].

Os sistemas AFF A-Series e AFF C-Series são compatíveis com as seguintes versões do ONTAP.

ONTAP 9.16,1::
+
--
* AFF A20
* AFF A30
* AFF A50
* AFF C30
* AFF C60
* AFF C80


--
ONTAP 9.15,1::
+
--
* AFF A1K
* AFF A70
* AFF A90


--
ONTAP 9.12.1P1::
+
--
* AFF A150
* AFF C250
* AFF C400
* AFF C800


--
ONTAP 9.10,1::
+
--
* AFF A900


--
ONTAP 9,8::
+
--
* AFF A250


--
ONTAP 9,7::
+
--
* AFF A400
* AFF A800


--


--
.Sistemas ASA R2
--
Os sistemas ASA R2 fornecem uma solução unificada de hardware e software que cria uma experiência simplificada específica para as necessidades dos clientes somente de SAN. link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Saiba mais sobre os sistemas ASA R2"].

Os sistemas ASA R2 são compatíveis com as seguintes versões do ONTAP.

ONTAP 9.16,0::
+
--
* ASA A1K
* ASA A70
* ASA A90


--


--
.Sistemas ASA
--
Os sistemas ASA A-Series e ASA C-Series oferecem uma experiência de SAN simplificada e dedicada que fornece disponibilidade de dados contínua para bancos de dados empresariais essenciais e outros workloads SAN que usam o protocolo FCP ou iSCSI. link:https://www.netapp.com/data-storage/all-flash-san-storage-array["Saiba mais sobre os sistemas ASA"].

Os sistemas ASA são compatíveis com as seguintes versões do ONTAP.

ONTAP 9.13.1P1::
+
--
* ASA C250
* ASA C400
* ASA C800


--
ONTAP 9.13,1::
+
--
* ASA A150
* ASA A250
* ASA A400
* ASA A900


--
ONTAP 9,8::
+
--
* ASA AFF A250
* ASA AFF A800


--
ONTAP 9,7::
+
--
* ASA AFF A400


--


--
.Sistemas FAS
--
Os sistemas FAS oferecem storage secundário eficiente e seguro, a melhor solução para disposição em camadas, backup e recuperação de desastres. link:https://www.netapp.com/data-storage/fas/["Saiba mais sobre os sistemas FAS"].

Os sistemas FAS são compatíveis com as seguintes versões do ONTAP.

ONTAP 9.15,1::
+
--
* FAS70
* FAS90


--
ONTAP 9.13,1::
+
--
* FAS2820


--
ONTAP 9.11,1::
+
--
* FAS9500


--
ONTAP 9.10.1P3::
+
--
* FAS9500


--
ONTAP 9,7::
+
--
* FAS2750
* FAS8300
* FAS8700


--


--
.Compartimentos de unidades
--
Os compartimentos de unidades são projetados especificamente para sistemas NetApp AFF, ASA e FAS e ajudam a fornecer a performance, resiliência e flexibilidade necessárias para a transformação digital.

Os compartimentos de unidades estão disponíveis a partir dos seguintes lançamentos da ONTAP.

ONTAP 9.16,1:: NS224 com NSM100B módulos
ONTAP 9,6:: NS224 gaveta com NSM100 módulos


--
====