---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, features, asa r2, aff, asa, fas, legacy, end-of-support 
summary: Saiba mais sobre os novos recursos para sistemas de hardware ONTAP. 
---
= Novidades para os sistemas de hardware ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Saiba mais sobre os novos recursos para sistemas de hardware ONTAP.

Para obter detalhes sobre problemas conhecidos, limitações e advertências de atualização nas versões do ONTAP 9, consulte o https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 Notas de versão"]. Você deve entrar com sua conta do NetApp ou criar uma conta para acessar as Notas de versão.



== Suporte de plataforma

[cols="2*"]
|===
| Plataformas | Disponível a partir do início 


 a| 
https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Sistemas ASA R2"]

* ASA A1K
* ASA A70
* ASA A90

 a| 
ONTAP 9.16,0



 a| 
https://www.netapp.com/data-storage/fas/["FAS70 e FAS90"]
 a| 
ONTAP 9.15,1



 a| 
* https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["AFF A1K"]
* https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["AFF A70"]
* https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["AFF A90"]

 a| 
ONTAP 9.15,1



 a| 
https://www.netapp.com/data-storage/all-flash-san-storage-array/["ASA C250"]
 a| 
ONTAP 9.13.1P1



 a| 
https://www.netapp.com/data-storage/all-flash-san-storage-array/["ASA C400"]
 a| 
ONTAP 9.13.1P1



 a| 
https://www.netapp.com/data-storage/all-flash-san-storage-array/["ASA C800"]
 a| 
ONTAP 9.13.1P1



 a| 
https://hwu.netapp.com/ProductSpecs/Index["FAS2820"]
 a| 
ONTAP 9.13,1



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A150"]
 a| 
ONTAP 9.13,1



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A250"]
 a| 
ONTAP 9.13,1



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A400"]
 a| 
ONTAP 9.13,1



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A900"]
 a| 
ONTAP 9.13,1



 a| 
* https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["AFF C250"]
* https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["AFF C400"]
* https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["AFF C800"]

 a| 
ONTAP 9.12.1P1

ONTAP 9.13,1 GA e versões posteriores do ONTAP

[NOTE]
====
Essas plataformas não são suportadas com o ONTAP 9.13,1 RC1.

====


 a| 
https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["AFF A150"]

[NOTE]
====
Não tente instalar ou inicializar o sistema de storage AFF A150 com uma versão não suportada do ONTAP. Se você tentar instalar ou inicializar seu sistema com uma versão não suportada do ONTAP, o ONTAP permitirá isso (o ONTAP não bloqueará a tentativa). A consequência é que o seu sistema de armazenamento AFF A150 será criado como um sistema de armazenamento FAS2750.

==== a| 
ONTAP 9.13,1 e versões posteriores do ONTAP

ONTAP 9.12.1P1

ONTAP 9.11.1P8

ONTAP 9.10.1P12



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS9500"]
 a| 
ONTAP 9.11,1

ONTAP 9.10.1P3



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF A900"]
 a| 
ONTAP 9.10,1



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF A250/AFF ASA A250"]
 a| 
ONTAP 9,8



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS500f"]
 a| 
ONTAP 9,8



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF ASA A800"]
 a| 
ONTAP 9,8



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS8300"]
 a| 
ONTAP 9,7



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS8700"]
 a| 
ONTAP 9,7



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF A400"]
 a| 
ONTAP 9,7



 a| 
https://www.netapp.com/pdf.html?item=/media/17190-na-382.pdf["AFF ASA A220"]
 a| 
ONTAP 9,7



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF ASA A700"]
 a| 
ONTAP 9,7



 a| 
https://www.netapp.com/pdf.html?item=/media/7623-ds-3989.pdf["AFF C190"^]
 a| 
ONTAP 9,6



 a| 
https://www.netapp.com/pdf.html?item=/media/17190-na-382.pdf["AFF A320"]
 a| 
ONTAP 9,6

|===


== Suporte do interrutor

[cols="20,65,15"]
|===
| Interrutores | Descrição | Disponível a partir do início 


 a| 
https://hwu.netapp.com/Switch/Index["Switch NVIDIA IP SN2100"]
 a| 
O switch de storage NVIDIA IP SN2100 é compatível com configurações MetroCluster IP que usam as plataformas A900/FAS9500.
 a| 
ONTAP 9.12,1



 a| 
https://hwu.netapp.com/Switch/Index["Switch NVIDIA IP SN2100 (X190006)"]
 a| 
O switch de armazenamento NVIDIA IP SN2100 é compatível com configurações IP do MetroCluster que usam as seguintes plataformas:

* FAS500f/AFF A250
* FAS8300/AFF A400
* FAS8700
* FAS9000/AFF A700
* AFF A800

 a| 
ONTAP 9.10.1P3



 a| 
https://hwu.netapp.com/Switch/Index["Switch Cisco de 36 portas de 100 GbE (X190200)"]
 a| 
Dá suporte a uma infraestrutura compartilhada (cluster, HA e storage conectado a switch) no mesmo par de switches Cisco Nexus 9336C-FX2, incluindo suporte para configurações IP MetroCluster.
 a| 
ONTAP 9.9,1



 a| 
https://hwu.netapp.com/Switch/Index["Switch Cisco de 36 portas de 100 GbE (X190200 e X190210)"]
 a| 
Switch de interconexão de cluster Cisco Nexus 9336C-FX2X compatível com switch de storage e switch de storage para controladores AFF/FAS, bem como para conectividade de dados de front-end.
 a| 
ONTAP 9,8



 a| 
https://hwu.netapp.com/Switch/Index["Switch Broadcom BES-53248 (X190005 e X190005R)"]
 a| 
Suporte ao switch de interconexão de cluster BES-53248 Broadcom para controladores AFF/FAS com portas de 40 GbE/100GbE GbE.
 a| 
ONTAP 9,8



 a| 
https://hwu.netapp.com/Switch/Index["Switch Cisco de 36 portas de 100 GbE (X190200)"] https://hwu.netapp.com/Switch/Index["Switch Cisco de 32 portas de 100 GbE (X190100 e X190100R)"]
 a| 
O switch Cisco Nexus 100 GbE pode ser usado como um switch de storage dedicado para conectar gavetas de unidade NVMe NS224 às seguintes plataformas:

* AFF A800/AFF ASA A800
* AFF A700/AFF ASA A700
* AFF A400/AFF ASA A400
* AFF A320

 a| 
ONTAP 9,8



 a| 
https://hwu.netapp.com/Switch/Index["Switch Broadcom BES-53248 (X190005 e X190005R)"]
 a| 
Suporte ao switch de interconexão de cluster BES-53248 Broadcom para controladores AFF/FAS com portas de 10 GbE/25GbE GbE.
 a| 
ONTAP 9.5P8

|===


== Suporte da prateleira

[cols="2*"]
|===
| Compartimentos | Disponível a partir do início 


 a| 
NS224
 a| 
ONTAP 9,6

|===


== Atualizações de hardware

[cols="25h,~,~"]
|===
| Funcionalidade | Descrição e onde saber mais | Disponível a partir do início 


 a| 
Interrutor de interconexão de vários clusters
 a| 
As configurações de vários clusters permitem que vários clusters compartilhem o mesmo switch de cluster, fornecido por meio de dois novos arquivos de configuração de referência para configurações de nó 4x4 e 2x8.
 a| 
ONTAP 9.14,1



 a| 
Suporte expandido para plataforma para NS224 compartimentos de unidades
 a| 
As plataformas a seguir são compatíveis com NS224 gavetas de unidades:

* AFF A800/AFF ASA A800
* AFF A700/AFF ASA A700
* AFF A250/AFF ASA A250
* FAS500f

 a| 
ONTAP 9,8



 a| 
Adição dinâmica de 12GB gavetas SAS a 6Gb stacks de storage SAS
 a| 
Agora é compatível com uma transição de velocidade única de 6Gb Gbps para 12GB Gbps em uma pilha de storage SAS. Isso permite a expansão de storage de 6Gb stacks existentes com 12GB gavetas.

https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-mix-hotadd/home.html["Gavetas de adição dinâmica com IOM12 módulos para uma stack de gavetas com IOM6 módulos"]
 a| 
ONTAP 9.7P4

ONTAP 9.6P9

ONTAP 9.5P14

|===