---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, features, asa r2, aff, asa, fas 
summary: Saiba mais sobre as novas plataformas para sistemas de hardware ONTAP. 
---
= Novidades para os sistemas de hardware ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Saiba o que há de novo para os sistemas de hardware ONTAP.



== Abril de 2025



=== FAS50

O sistema FAS50 oferece o menor custo por Gigabyte para storage secundário e link:https://docs.netapp.com/us-en/netapp-solutions/cyber-vault/ontap-cyber-vault-overview.html["cofre cibernético seguro"], além de maior desempenho para workloads secundários com backups mais rápidos, IOPS mais alto e baixa latência de 5 a 10ms.

link:https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["Saiba mais sobre os sistemas FAS"].



== Fevereiro de 2025



=== ASA A20, ASA A30 e ASA A50

Os sistemas ASA A20 e ASA A30 e A50 midrange de nível básico disponibilizam storage de bloco para empresas de todos os tamanhos para aplicações essenciais, como bancos de dados e máquinas virtuais.

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Saiba mais sobre os sistemas ASA R2"].



== Dezembro de 2024



=== AFF A20, AFF A30 e AFF A50

Os novos sistemas de hardware AFF A20, A30 e A50 estendem recursos de gerenciamento de dados abrangentes, inteligentes e de alto desempenho para mais clientes e workloads.

Os sistemas oferecem detecção de ransomware baseada EM ML em tempo real, integração otimizada com a nuvem e performance incomparável para workloads essenciais, incluindo IA, VMware, bancos de dados e análises, com suporte para storage de bloco, arquivo e objetos.

link:https://www.netapp.com/data-storage/aff-a-series/["Saiba mais sobre os sistemas AFF A-Series"].



=== AFF C30, AFF C60 e AFF C80

Os novos sistemas de hardware AFF C30, AFF C60 e AFF C80 tornam os ganhos de performance e eficiência de flash mais acessíveis às empresas, fornecendo um 1,5PB TB de capacidade de storage líder do setor em implantações de dois rack.

A solução oferece densidade excepcional com unidades de 60TB TB, maior desempenho e maior flexibilidade de e/S.

link:https://www.netapp.com/data-storage/aff-c-series/["Saiba mais sobre os sistemas AFF série C."].



=== Compartimento de unidades de NS224 TB com módulos de compartimento de NSM100B U.

Aprimore as funcionalidades do data center com o NS224 e o novo módulo de expansão de storage NVMe de NSM100B GB. Projetado como um substituto direto para o módulo NSM100, o novo módulo de prateleira NSM100B se integra perfeitamente à sua configuração existente. Ele dá suporte a configurações de conexão direta e conexão a switch de NS224 gavetas, oferecendo flexibilidade excepcional para otimizar a eficiência e a escalabilidade do seu sistema de storage.



== Setembro de 2024



=== Sistemas ASA R2

Os novos sistemas de hardware ASA R2 (ASA A1K, ASA A70 e ASA A90) fornecem uma solução unificada de hardware e software que cria uma experiência simplificada específica para as necessidades dos clientes somente de SAN.

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Saiba mais sobre os sistemas ASA R2"].



=== FAS70 e FAS90

Os novos sistemas de hardware FAS70 e FAS90 oferecem storage de backup econômico, mas de alta performance, permitindo um cofre cibernético seguro para recuperação de ataques de ransomware.

link:https://www.netapp.com/data-storage/fas/["Saiba mais sobre os sistemas FAS"].
