---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, features, asa r2, aff, asa, fas 
summary: Saiba mais sobre as novas plataformas para sistemas de hardware ONTAP. 
---
= Novidades para os sistemas de hardware ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Saiba o que há de novo para os sistemas de hardware ONTAP.



== Dezembro de 2024



=== AFF A20, AFF A30 e AFF A50

Os novos sistemas de hardware AFF A20, A30 e A50 estendem recursos de gerenciamento de dados abrangentes, inteligentes e de alto desempenho para mais clientes e workloads.

Os sistemas oferecem detecção de ransomware baseada EM ML em tempo real, integração otimizada com a nuvem e performance incomparável para workloads essenciais, incluindo IA, VMware, bancos de dados e análises, com suporte para storage de bloco, arquivo e objetos.

link:https://www.netapp.com/data-storage/aff-a-series/["Saiba mais sobre os sistemas AFF A-Series"].



=== AFF C30, AFF C60 e AFF C80

Os novos sistemas de hardware AFF C30, AFF C60 e AFF C80 tornam os ganhos de desempenho e eficiência do flash mais acessíveis às empresas, fornecendo um 1,5PB TB de capacidade de storage líder do setor em implantações de dois rack.

A solução oferece densidade excepcional com unidades de 60TB TB, maior desempenho e maior flexibilidade de e/S.

link:https://www.netapp.com/data-storage/aff-c-series/["Saiba mais sobre os sistemas AFF série C."].



== Setembro de 2024



=== Sistemas ASA R2

Os novos sistemas de hardware ASA R2 (ASA A1K, ASA A70 e ASA A90) fornecem uma solução unificada de hardware e software que cria uma experiência simplificada específica para as necessidades dos clientes somente SAN.

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Saiba mais sobre os sistemas ASA R2"].



=== FAS70 e FAS90

Os novos sistemas de hardware FAS70 e FAS90 oferecem storage de backup econômico, mas de alta performance, permitindo um cofre cibernético seguro para recuperação de ataques de ransomware.

link:https://www.netapp.com/data-storage/fas/["Saiba mais sobre os sistemas FAS"].
