---
permalink: asa400/bootmedia-recovery-image-boot.html 
sidebar: sidebar 
keywords: asa a400, asa, a400, procedure, boot, impair, controller, recovery, image, system, two-node, metrocluster, configuration, boot the recovery image 
summary: O procedimento para inicializar o controlador prejudicado a partir da imagem de recuperação depende se o sistema está em uma configuração de MetroCluster de dois nós. 
---
= Inicialize a imagem de recuperação no seu sistema ASA A400 usando o processo de recuperação de inicialização manual
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de instalar o novo dispositivo multimédia de arranque no seu sistema, pode arrancar a imagem de recuperação a partir de uma unidade USB e restaurar a configuração a partir do nó do parceiro.

Se o seu sistema de armazenamento estiver executando o ONTAP 9.17.1 ou posterior, use olink:bootmedia-replace-workflow-bmr.html["procedimento automatizado de recuperação de inicialização"] .  Se o seu sistema estiver executando uma versão anterior do ONTAP, você deverá usar o procedimento de recuperação de inicialização manual.

.Antes de começar
* Certifique-se de que seu console esteja conectado ao controle com defeito.
* Verifique se a interface e0S (porta de chave inglesa e0M) no controlador com defeito não está com falha.
* Verifique se você possui um pen drive com a imagem de recuperação.
* Verifique se o seu sistema utiliza criptografia.  Você precisará selecionar a opção apropriada na etapa 3, dependendo se a criptografia está ativada ou não.


.Passos
. A partir do prompt LOADER no controlador com defeito, inicialize a imagem de recuperação a partir da unidade flash USB:
+
`boot_recovery`

+
A imagem de recuperação é baixada da unidade flash USB.

. Quando solicitado, digite o nome da imagem ou pressione *Enter* para aceitar a imagem padrão exibida entre colchetes.
. Restaure o sistema de ficheiros var:
+
[cols="1,2"]
|===
| Se o seu sistema tem... | Então... 


 a| 
Uma conexão de rede e está executando ONTAP 9.16.0 ou anterior
 a| 
Conclua as seguintes etapas no controlador incapacitado e no controlador parceiro:

.. *No controlador com defeito:* Pressione `Y` quando você vê `Do you want to restore the backup configuration now?`
.. *No controlador com defeito:* Se solicitado, pressione `Y` para sobrescrever _/etc/ssh/ssh_host_ecdsa_key_.
.. *No controlador parceiro:* Defina o controlador com problemas para o nível de privilégio avançado:
+
`set -privilege advanced`

.. *No controlador parceiro:* Execute o comando de restauração de backup:
+
`system node restore-backup -node local -target-address _impaired_node_IP_address_`

+

NOTE: Se você vir qualquer mensagem diferente de uma restauração bem-sucedida, entre em contato com o Suporte da NetApp .

.. *No controlador de parceiros:* Retornar ao nível de administrador:
+
`set -privilege admin`

.. *No controlador com defeito:* Pressione `Y` quando você vê `Was the restore backup procedure successful?`
.. *No controlador com defeito:* Pressione `Y` quando você vê `...would you like to use this restored copy now?`
.. *No controlador com defeito:* Pressione `Y` Quando solicitado a reiniciar, pressione `Ctrl-C` quando você vir o Menu de Inicialização.
.. *No controlador inoperante:* Faça um dos seguintes procedimentos:
+
*** Se o sistema não usar criptografia, selecione _Opção 1 Inicialização Normal_ no Menu de Inicialização.
*** Se o sistema usar criptografia, acesselink:bootmedia-encryption-restore.html["Restaure a criptografia"] .






 a| 
Uma conexão de rede e está executando ONTAP 9.16.1 ou posterior
 a| 
Conclua os seguintes passos no controlador comprometido:

.. Pressione `Y` quando solicitado para restaurar a configuração de backup.
+
Após o procedimento de restauração ser concluído com sucesso, esta mensagem é exibida: `syncflash_partner: Restore from partner complete`

.. Imprensa `Y` quando solicitado a confirmar que a restauração do backup foi bem-sucedida.
.. Imprensa `Y` quando solicitado a usar a configuração restaurada.
.. Imprensa `Y` quando solicitado a reiniciar o nó.
.. Imprensa `Y` Quando solicitado a reiniciar novamente, pressione `Ctrl-C` quando você vir o Menu de Inicialização.
.. Execute um dos seguintes procedimentos:
+
*** Se o sistema não usar criptografia, selecione _Opção 1 Inicialização Normal_ no Menu de Inicialização.
*** Se o sistema usar criptografia, acesselink:bootmedia-encryption-restore.html["Restaure a criptografia"] .






 a| 
Sem ligação à rede
 a| 
.. Pressione  `N` quando solicitado para restaurar a configuração de backup.
.. Reinicie o sistema quando solicitado pelo sistema.
.. Selecione a opção *Update flash from backup config* (Sync flash) no menu exibido.
+
Se for solicitado que você continue com a atualização, pressione  `Y`.

.. Pressione  `Ctrl-C`quando você vir o Menu de Inicialização.
.. Execute um dos seguintes procedimentos:
+
*** Se o sistema não usar criptografia, selecione _Opção 1 Inicialização Normal_ no Menu de Inicialização.
*** Se o sistema usar criptografia, acesselink:bootmedia-encryption-restore.html["Restaure a criptografia"] .






 a| 
Sem conexão de rede e está em uma configuração IP MetroCluster
 a| 
.. Pressione  `N` quando solicitado para restaurar a configuração de backup.
.. Reinicie o sistema quando solicitado pelo sistema.
.. Aguarde que as ligações de armazenamento iSCSI se liguem.
+
Você pode prosseguir depois de ver as seguintes mensagens:

+
[listing]
----
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_auxiliary, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_partner, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_auxiliary, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_partner, address: ip-address).
----
.. Selecione a opção *Update flash from backup config* (Sync flash) no menu exibido.
+
Se for solicitado que você continue com a atualização, pressione  `Y`.

.. Pressione  `Ctrl-C`quando você vir o Menu de Inicialização.
.. Execute um dos seguintes procedimentos:
+
*** Se o sistema não usar criptografia, selecione _Opção 1 Inicialização Normal_ no Menu de Inicialização.
*** Se o sistema usar criptografia, acesselink:bootmedia-encryption-restore.html["Restaure a criptografia"] .




|===
. Conete o cabo do console ao controlador do parceiro.
. Volte a colocar o controlador em funcionamento normal, devolvendo o respetivo armazenamento:
+
`storage failover giveback -fromnode local`

. Se você desativou a devolução automática, reative-a:
+
`storage failover modify -node local -auto-giveback true`

. Se o AutoSupport estiver ativado, restaure a criação automática de casos:
+
`system node autosupport invoke -node * -type all -message MAINT=END`


