---
permalink: c80/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: aff c80, replace the boot media 
summary: Antes de substituir o suporte de arranque no sistema AFF C80, certifique-se de que tem o dispositivo de arranque de substituição correto, acesso ao firmware do sistema e ao software ONTAP e uma cópia de segurança dos dados de configuração essenciais. 
---
= Requisitos de substituição do suporte de arranque - AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de substituir o suporte de arranque no sistema AFF C80, certifique-se de que tem o dispositivo de arranque de substituição correto, acesso ao firmware do sistema e ao software ONTAP e uma cópia de segurança dos dados de configuração essenciais.

Reveja os seguintes requisitos.

* Tem de ter uma unidade flash USB, formatada para FAT32, com a quantidade de armazenamento adequada para guardar o `image_xxx.tgz` ficheiro.
* Você deve copiar o `image_xxx.tgz` arquivo para a unidade flash USB para uso posterior neste procedimento.
* Você deve substituir o componente com falha por um componente FRU de substituição que você recebeu de seu provedor.
* É importante que você aplique os comandos nestas etapas no controlador correto:
+
** O controlador _prejudicado_ é o controlador no qual você está realizando a manutenção.
** O controlador _Healthy_ é o parceiro de HA do controlador prejudicado.



