---
permalink: c80/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: c80, shutdown the controllers 
summary: Para substituir o chassi, você deve desligar os controladores. 
---
= Desligue os controladores - AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Desligue os controladores para que possa efetuar a manutenção no chassis.

Este procedimento destina-se a sistemas com duas configurações de nós. Se tiver um sistema com mais de dois nós, https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_perform_a_graceful_shutdown_and_power_up_of_one_HA_pair_in_a_4__node_cluster["Como executar um desligamento eficiente e ligar um par de HA em um cluster de quatro nós"^] consulte .

.Antes de começar
* Impedir que todos os clientes/hosts acessem dados no sistema NetApp.
* Suspender trabalhos de cópia de segurança externos.
* Certifique-se de que tem as permissões e credenciais necessárias:
+
** Credenciais de administrador local para o ONTAP.
** Senha do NetApp Onboard Key Management (OKM) em todo o cluster se estiver usando criptografia de storage ou NVE/NAE.
** BMC accessability para cada controlador.


* Certifique-se de que tem as ferramentas e o equipamento necessários para a substituição.
* Como uma prática recomendada antes do desligamento, você deve:
+
** Execute mais https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["verificações de integridade do sistema"].
** Atualize o ONTAP para uma versão recomendada para o sistema.
** Resolva qualquer https://activeiq.netapp.com/["Alertas e riscos de bem-estar do Active IQ"]. Tome nota de quaisquer avarias atualmente no sistema, tais como LEDs nos componentes do sistema.




.Passos
. Faça login no cluster através de SSH ou faça login de qualquer nó no cluster usando um cabo de console local e um laptop/console.
. Desligue o AutoSupport e indique quanto tempo espera que o sistema fique offline:
+
`system node autosupport invoke -node * -type all -message "MAINT=8h Power Maintenance"`

. Identifique o endereço SP/BMC de todos os nós:
+
`system service-processor show -node * -fields address`

. Saia do shell do cluster: `exit`
. Faça login no SP/BMC via SSH usando o endereço IP de qualquer um dos nós listados na saída da etapa anterior.
+
Se você estiver usando um console/laptop, faça login no controlador usando as mesmas credenciais de administrador de cluster.

+

NOTE: Abra uma sessão SSH para cada conexão SP/BMC para que você possa monitorar o progresso.

. Parar os dois nós localizados no chassi com deficiência:
+
`system node halt -node <node1>,<node2> -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true`

+

NOTE: Para clusters que usam o SnapMirror síncrono operando no modo StrictSync: `system node halt -node <node1>,<node2>  -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true -ignore-strict-sync-warnings true`

. Digite *y* para cada controlador no cluster quando você vir `_Warning: Are you sure you want to halt node "cluster <node-name> number"?
{y|n}:_`
. Aguarde que cada controlador pare e exiba o prompt Loader.

