---
permalink: c80/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: c80, how to recable the system, teboot the system 
summary: Retorne o controle dos recursos de armazenamento ao controlador de substituição para que seu sistema AFF C80 possa retomar a operação normal. 
---
= Devolver o controlador - AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Retorne o controle dos recursos de armazenamento ao controlador de substituição para que seu sistema AFF C80 possa retomar a operação normal. O procedimento de devolução varia de acordo com o tipo de criptografia usado pelo seu sistema: sem criptografia ou criptografia Onboard Key Manager (OKM).

[role="tabbed-block"]
====
.Sem criptografia
--
Volte a colocar o controlador afetado em funcionamento normal, devolvendo o respetivo armazenamento.

.Passos
. No prompt Loader, digite `boot_ontap`.
. Pressione <enter> quando as mensagens do console pararem.
+
** Se você vir o prompt _login_, vá para a próxima etapa no final desta seção.
** Se você vir _aguardando giveback_, pressione a tecla <enter>, faça login no nó do parceiro e vá para a próxima etapa no final desta seção.


. Volte a colocar o controlador afetado em funcionamento normal, devolvendo o respetivo armazenamento: `storage failover giveback -ofnode _impaired_node_name_`
. Se a giveback automática foi desativada, reative-a: `storage failover modify -node local -auto-giveback _true_`
. Se o AutoSupport estiver ativado, restaurar/anular a criação automática de casos: `system node autosupport invoke -node * -type all -message MAINT=END`


--
.Criptografia integrada (OKM)
--
Redefina a criptografia integrada e retorne o controlador à operação normal.

.Passos
. No prompt Loader, digite `boot_ontap maint`.
. Inicie no menu ONTAP a partir do prompt Loader `boot_ontap menu` e selecione a opção 10.
. Introduza a frase-passe OKM.
+

NOTE: Você é solicitado duas vezes para a senha.

. Insira os dados da chave de backup quando solicitado.
. No menu de inicialização, insira a opção `1` para inicialização normal.
. Pressione <enter> quando _Waiting for giveback_ for exibido.
. Mova o cabo do console para o nó do parceiro e faça login como `admin`.
. Devolver apenas os agregados CFO (o agregado raiz): `storage failover giveback -fromnode local -only-cfo-aggregates _true_`
+
** Se encontrar erros, https://support.netapp.com["Suporte à NetApp"] contacte .


. Aguarde 5 minutos após a conclusão do relatório de giveback e verifique o status de failover e o status de giveback `storage failover show`: E `storage failover show-giveback`.
. Sincronize e verifique o status das chaves:
+
.. Volte a colocar o cabo da consola no controlador de substituição.
.. Sincronizar chaves em falta: `security key-manager onboard sync`
+

NOTE: Você é solicitado a fornecer a senha de OKM para o cluster.

.. Verifique o status das chaves: `security key-manager key query -restored _false_`
+
A saída não deve mostrar resultados quando devidamente sincronizada.

+
Se a saída apresentar resultados (as IDs das chaves que não estão presentes na tabela de chaves internas do sistema), contacte https://support.netapp.com["Suporte à NetApp"].



. Volte a colocar o controlador afetado em funcionamento normal, devolvendo o respetivo armazenamento: `storage failover giveback -ofnode _impaired_node_name_`
. Se a giveback automática foi desativada, reative-a: `storage failover modify -node local -auto-giveback _true_`
. Se o AutoSupport estiver ativado, restaurar/anular a criação automática de casos: `system node autosupport invoke -node * -type all -message MAINT=END`


--
====
.O que se segue?
Depois de transferir a propriedade dos recursos de armazenamento de volta para o controlador de substituição, você precisa link:controller-replace-restore-system-rma.html["complete a substituição do controlador"]fazer o procedimento.
