---
sidebar: sidebar 
permalink: c80/install-requirements.html 
keywords: c80, install, setup, cautions 
summary: Reveja o equipamento necessário e as precauções de elevação para o seu sistema de armazenamento e prateleiras. 
---
= Requisitos de instalação - AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Reveja o equipamento necessário e as precauções de elevação para o seu sistema de armazenamento AFF C80 e prateleiras de armazenamento.



== Equipamento necessário para instalação

.O que se segue?
Para instalar seu sistema de storage, você precisa dos seguintes equipamentos e ferramentas.

* Acesso a um navegador da Web para configurar o sistema de armazenamento
* Fita de descarga eletrostática (ESD)
* Lanterna
* Computador portátil ou console com conexão USB/serial
* Clipe de papel ou caneta esferográfica de ponta estreita para definir NS224 IDs de prateleira de armazenamento
* Chave de fendas Phillips nº 2




== Precauções de elevação

Os sistemas de armazenamento e as prateleiras são pesados. Tenha cuidado ao levantar e mover estes itens.



=== Peso do sistema de armazenamento

Tome as precauções necessárias ao mover ou elevar o sistema de armazenamento.

O sistema de armazenamento pode pesar até 151,68 lbs (68,8 kg). Para levantar o sistema de armazenamento, utilize quatro pessoas ou um elevador hidráulico.

image::../media/drw_a70-90_weight_icon_ieops-1730.svg[AFF A90]



=== Peso da prateleira

Tome as precauções necessárias ao mover ou levantar a prateleira.

Uma prateleira de NS224 kg pode pesar até 66,78 lbs (30,29 kg). Para levantar a prateleira, use duas pessoas ou um elevador hidráulico. Mantenha todos os componentes na prateleira (dianteira e traseira) para evitar desequilibrar o peso da prateleira.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 NSM100 precaução de elevação]

.Informações relacionadas
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Informações de segurança e avisos regulamentares"^]


Depois de analisar os requisitos de hardware, você link:install-prepare.html["Prepare-se para instalar o sistema de storage AFF C80"].
