---
permalink: c80/io-module-overview.html 
sidebar: sidebar 
keywords: AFF C80, replace io module 
summary: Você pode substituir um módulo de e/S com falha em seu sistema de storage AFF C80 pelo mesmo tipo de módulo de e/S ou por um tipo diferente de módulo de e/S. Você também pode adicionar um módulo de e/S a um sistema com slots vazios. 
---
= Descrição geral de adicionar e substituir um módulo de e/S - AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O sistema AFF C80 oferece flexibilidade na expansão ou substituição de módulos de e/S para melhorar a conetividade e o desempenho da rede. Adicionar ou substituir um módulo de e/S é essencial ao atualizar recursos de rede ou endereçar um módulo com falha.

Você pode substituir um módulo de e/S com falha em seu sistema de storage AFF C80 pelo mesmo tipo de módulo de e/S ou por um tipo diferente de módulo de e/S. Você também pode adicionar um módulo de e/S a um sistema com slots vazios.

* link:io-module-add.html["Adicione um módulo de e/S."]
+
Adicionar módulos adicionais pode melhorar a redundância, ajudando a garantir que o sistema permaneça operacional mesmo que um módulo falhe.

* link:io-module-hotswap.html["Substituição a quente de um módulo de E/S"]
+
A substituição a quente de um módulo de E/S permite substituir um módulo com defeito sem desligar o sistema, minimizando o tempo de inatividade e mantendo a disponibilidade do sistema.

* link:io-module-replace.html["Substitua um módulo de e/S."]
+
A substituição de um módulo de e/S com falha pode restaurar o sistema ao seu estado de funcionamento ideal.



.Numeração de slots de e/S.
Os slots de e/S nos controladores AFF C80 são numerados de 1 a 11, como mostrado na ilustração a seguir.

image::../media/drw_a1K_back_slots_labeled_ieops-2162.svg[Numeração de slots em um controlador AFF C80]
