---
permalink: c80/overview.html 
sidebar: sidebar 
keywords: AFF C80 specifications, AFF C80 specs, NetApp AFF C80, AFF C80 hardware 
summary: Especificações principais para o sistema de armazenamento AFF C80 
---
= Especificações principais do AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A seguir estão algumas especificações selecionadas para o AFF C80.  Visita https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) para uma lista completa das especificações do AFF C80.  Esta página reflete um único par de alta disponibilidade.



=== Especificações principais do AFF C80

Configuração da plataforma: Par de HA de chassi único AFF C80

Capacidade Máxima de Bruto: 14.7360 PB

Memória: 512.0000 GB

Fator de forma: chassi 4U com 2 controladores HA e 48 slots de unidade

Versão ONTAP : b_startONTAP: 9.16.1P2b_end

Slots de expansão PCIe: 18

Versão mínima do ONTAP : ONTAP 9.16.1RC1



=== Máximos de Escalabilidade

|===


| Tipo | Pares HA | Capacidade bruta | Memória Máxima 


| NAS | 12 | 176,8 PB / 157,0 PiB | 6144 GB 


| SAN | 6 | 88,4 PB / 78,5 PiB | 3072 GB 


| Par HA |  | 14,7 PB / 13,1 PiB | 512,0000 
|===


=== IO



==== IO integrado

Não há dados de E/S a bordo.



==== Total de IO

|===


| Protocolo | Portos 


| Ethernet 200 Gbps | 24 


| Ethernet 100 Gbps | 36 


| Ethernet 25 Gbps | 56 


| Ethernet 10 Gbps | 56 


| FC 64 Gbps | 56 


| NVMe/FC 64 Gbps | 56 


|  | 0 
|===


==== Portas de Gestão

|===


| Protocolo | Portos 


| Ethernet 1 Gbps | 2 


| RS-232 115 Kbps | 4 


| USB 600 Mbps | 2 
|===


=== Rede de armazenamento suportada

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NFSv3/RDMA; NFSv4/RDMA; NVMe/FC; NVMe/TCP; S3; S3 com NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Especificações do ambiente do sistema

Não há dados ambientais disponíveis.



=== Conformidade

* Certificações EMC/EMI: AMCA, FCC, ICES, KC, Marrocos, VCCI
* Certificações de segurança: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificações Segurança/EMC/EMI: EAC, UKRSEPRO
* Certificações Segurança/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normas EMC/EMI: BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normas de segurança: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilidade

Controlador de gerenciamento de placa base baseado em Ethernet (BMC) e interface de gerenciamento ONTAP ; Controladores redundantes de troca a quente; Fontes de alimentação redundantes de troca a quente;
