---
permalink: fas2700/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: fas2700, aff a220, replace, boot, media, image, nondisruptive, disruptive, replacement, fat32, usb, manual, manual boot recovery 
summary: 'Saiba mais sobre a substituição da mídia de inicialização em um sistema FAS2700 e entenda os diferentes métodos de substituição. A mídia de inicialização armazena arquivos de imagem de inicialização primários e secundários que o sistema usa durante a inicialização. Dependendo da configuração da sua rede, você pode realizar uma substituição sem interrupção (par HA conectado à rede) ou uma substituição com interrupção (requer duas reinicializações).' 
---
= Visão geral da substituição da mídia de inicialização - FAS2700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Saiba mais sobre a substituição da mídia de inicialização em um sistema FAS2700 e entenda os diferentes métodos de substituição.

A mídia de inicialização armazena arquivos de imagem de inicialização primários e secundários que o sistema usa durante a inicialização. Dependendo da configuração da sua rede, você pode realizar uma substituição sem interrupção (par HA conectado à rede) ou uma substituição com interrupção (requer duas reinicializações).

A Mídia de inicialização armazena um conjunto primário e secundário de arquivos do sistema (imagem de inicialização) que o sistema usa quando ele é inicializado. Dependendo da configuração da rede, você pode realizar uma substituição sem interrupções ou disruptiva.

Tem de ter uma unidade flash USB, formatada para FAT32, com a quantidade de armazenamento adequada para guardar o `image_xxx.tgz` ficheiro.

Você também deve copiar o `image_xxx.tgz` arquivo para a unidade flash USB para uso posterior neste procedimento.

* Os métodos sem interrupções e disruptivos para substituir uma Mídia de inicialização exigem que você restaure o `var` sistema de arquivos:
+
** Para substituição sem interrupções, o par de HA deve estar conetado a uma rede para restaurar o `var` sistema de arquivos.
** Para a substituição disruptiva, não é necessário uma ligação de rede para restaurar o `var` sistema de ficheiros, mas o processo requer duas reinicializações.


* Você deve substituir o componente com falha por um componente FRU de substituição que você recebeu de seu provedor.
* É importante que você aplique os comandos nessas etapas no nó correto:
+
** O nó _prejudicado_ é o nó no qual você está realizando a manutenção.
** O nó _Healthy_ é o parceiro de HA do nó prejudicado.



