---
sidebar: sidebar 
permalink: fru-reference/io-module-fru-links.html 
keywords: I/O module, field replaceable units, FRU, I/O module replacement 
summary: Encontre procedimentos de substituição de módulos de E/S para seu sistema de armazenamento NetApp organizados por família de plataformas.  Esta referência fornece links diretos para fluxos de trabalho de substituição de módulos de E/S passo a passo para sistemas AFF, ASA e FAS para ajudar você a localizar rapidamente o procedimento correto para seu modelo específico. 
---
= Procedimentos de substituição de módulos de E/S por família de plataforma
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Encontre procedimentos de substituição de módulos de E/S para seu sistema de armazenamento NetApp organizados por família de plataformas.  Esta referência fornece links diretos para fluxos de trabalho de substituição de módulos de E/S passo a passo para sistemas AFF, ASA e FAS para ajudar você a localizar rapidamente o procedimento correto para seu modelo específico.

[role="tabbed-block"]
====
.Sistemas AFF
--
* link:../a1k/io-module-replace.html["AFF A1K"]
* link:../a20-30-50/io-module-replace.html["AFF A20/30/50"]
* link:../a70-90/io-module-replace.html["AFF A70/90"]
* link:../c30-60/io-module-replace.html["AFF C30/60"]
* link:../c80/io-module-replace.html["AFF C80"]


--
.Sistemas ASA
--
* link:../asa-r2-a1k/io-module-replace.html["ASA A1K"]
* link:../asa-r2-a20-30-50/io-module-replace.html["ASA A20/30/50"]
* link:../asa-r2-70-90/io-module-replace.html["ASA 70/90"]
* link:../asa-r2-c30/io-module-replace.html["ASA C30"]


--
.Sistemas FAS
--
* link:../fas50/io-module-replace.html["FAS50"]
* link:../fas-70-90/io-module-replace.html["FAS70/90"]


--
====