---
sidebar: sidebar 
permalink: fru-reference/nvram-module-fru-links.html 
keywords: NVRAM module, field replaceable units, FRU, NVRAM module replacement 
summary: Encontre procedimentos de substituição de módulo NVRAM para seu sistema de armazenamento NetApp organizados por família de plataforma.  Esta referência fornece links diretos para fluxos de trabalho de substituição de módulo NVRAM passo a passo para sistemas AFF, ASA e FAS para ajudar você a localizar rapidamente o procedimento correto para seu modelo específico. 
---
= Procedimentos de substituição do módulo NVRAM por família de plataforma
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Encontre procedimentos de substituição de módulo NVRAM para seu sistema de armazenamento NetApp organizados por família de plataforma.  Esta referência fornece links diretos para fluxos de trabalho de substituição de módulo NVRAM passo a passo para sistemas AFF, ASA e FAS para ajudar você a localizar rapidamente o procedimento correto para seu modelo específico.

[role="tabbed-block"]
====
.Sistemas AFF
--
* link:../a1k/nvram-replace.html["AFF A1K"]
* link:../a70-90/nvram-replace.html["AFF A70/90"]
* link:../a700/nvram-module-or-nvram-dimm-replacement.html["AFF A700"]
* link:../a700s/nvram-or-nvram-dimm-replacement.html["AFF A700s"]
* link:../a900/nvram_module_or_nvram_dimm_replacement.html["AFF A900"]
* link:../c80/nvram-replace.html["AFF C80"]


--
.Sistemas ASA
--
* link:../asa900/nvram_module_or_nvram_dimm_replacement.html["ASA A900"]
* link:../asa-r2-a1k/nvram-replace.html["ASA A1K"]
* link:../asa-r2-70-90/nvram-replace.html["ASA 70/90"]


--
.Sistemas FAS
--
* link:../fas-70-90/nvram-replace.html["FAS70/90"]
* link:../fas9000/nvram-module-or-nvram-dimm-replacement.html["FAS9000"]
* link:../fas9500/nvram_module_or_nvram_dimm_replacement.html["FAS9500"]


--
====