---
permalink: platform-supplemental/42u-1280mm-remove-door.html 
sidebar: sidebar 
keywords: remove, system, cabinet, door, side, panel, illuminate, badge, component, reverse, door, remove the system cabinet door 
summary: É necessário remover a porta do armário do sistema e os painéis laterais para mover o emblema e os componentes iluminados e para inverter a porta. 
---
= Retire a porta do armário do sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É necessário remover a porta do armário do sistema e os painéis laterais para mover o emblema e os componentes iluminados e para inverter a porta.

. Abra a porta do armário do sistema se ainda não estiver aberta.
. Execute a ação apropriada dependendo se seus gabinetes estão conetados ao kit de interconexão.
+
[cols="1,2"]
|===
| Se o seu gabinete do sistema é... | Então... 


 a| 
Não ligado a outro armário do sistema
 a| 
Vá para a próxima etapa.



 a| 
Conetado a outro gabinete do sistema com um kit de interconexão
 a| 
Retire todos os quatro suportes do kit de interligação e coloque os suportes e parafusos num local seguro.

|===
. Desbloqueie ambos os painéis laterais, desligue os fios de ligação à terra dos painéis laterais e, em seguida, retire-os e coloque-os de lado.
. Desconete o fio de aterramento da pá de aterramento localizada na parte superior da porta.
. Desaperte o conjunto do cabo e da patilha de ligação à terra da estrutura do armário do sistema e coloque-o de lado.
. Desaperte o conjunto da patilha de ligação à terra da porta do armário do sistema e coloque-o de lado.
. Levante o pino da dobradiça superior até que ele saia da parte inferior da dobradiça.
. Incline cuidadosamente a parte superior da porta para longe da estrutura do armário do sistema e, em seguida, solte o pino da dobradiça.
. Levante a porta da dobradiça inferior e coloque-a de lado.

