---
permalink: platform-supplemental/42u-1280mm-features.html 
sidebar: sidebar 
keywords: system, cabinet, side, panel, front, rear, door, bolt-down, kit, optional, interconnect, pdu, equipment, integrate, cable, management, system, feature, system cabinet feature 
summary: O gabinete do sistema é composto por painéis laterais, portas dianteiras e traseiras, um kit opcional de parafusos, um kit opcional de interconexão, PDUs para o seu equipamento e um sistema integrado de gerenciamento de cabos. 
---
= Recursos do gabinete do sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O gabinete do sistema é composto por painéis laterais, portas dianteiras e traseiras, um kit opcional de parafusos, um kit opcional de interconexão, PDUs para o seu equipamento e um sistema integrado de gerenciamento de cabos.

[cols="1,2"]
|===
| Recurso | Descrição 


 a| 
Painéis laterais
 a| 
Os armários do sistema têm painéis laterais trancáveis, removíveis e intercambiáveis.



 a| 
Portas dianteiras e traseiras perfuradas
 a| 
Os armários do sistema têm portas dianteiras e traseiras removíveis com um mecanismo de liberação rápida. A porta dianteira é reversível e as portas traseiras estão divididas. Ambas as portas são perfuradas para refrigeração.



 a| 
Chave comum
 a| 
Esta chave destranca as portas dianteiras, as portas traseiras e os painéis laterais.



 a| 
Kit de peças sobressalentes
 a| 
Este kit está dentro do gabinete do sistema, anexado à porta do gabinete. Contém os seguintes componentes:

* Quatro parafusos Phillips de 10-32 x 0,75 polegadas
* Quatro porcas de gaiola 10-32
* Uma ferramenta de inserção de porca de gaiola
* Duas cópias de chave mestra




 a| 
Acesso a cabo
 a| 
As passagens de cabos são incorporadas na parte superior e inferior do gabinete, bem como entre a parte inferior da porta traseira e a estrutura.



 a| 
Gerenciamento de cabos
 a| 
O gancho de gerenciamento de cabos e as cintas de loop são fixados à estrutura do gabinete do sistema em intervalos iguais.



 a| 
Suportes de montagem
 a| 
O número de trilhos de suporte que você recebe depende de sua configuração. O gabinete do sistema vazio é enviado sem trilhos de suporte instalados.

* Para gabinetes de sistema configurados, um kit de trilho fixo é fornecido com o gabinete do sistema para suportar os suportes de fixação traseiros 80xx, FAS8200 e DS4486.
* Os armários de sistema de envio rápido não incluem o kit de trilho fixo adicional.




 a| 
Tampas de limpeza
 a| 
O número e o tamanho dos painéis de supressão que você recebe dependem de sua configuração. O gabinete do sistema vazio é enviado sem painéis obturadores instalados.



 a| 
Kit de parafusos
 a| 
Este kit opcional permite que você proteja o gabinete do sistema ao piso do data center. O kit não se destina à estabilidade sísmica.

* Quatro suportes aparafusados
* Quatro suportes espaçadores
* Seis parafusos sextavados e anilhas M8x20 mm




 a| 
Kit de interligação
 a| 
Este kit opcional permite que você conete vários gabinetes de sistema um ao outro.

* Suportes de interconexão
+
** Um conjunto de quatro suportes de interconexão para conetar os gabinetes do sistema com painéis laterais
** Um conjunto de quatro suportes de interconexão para conetar os gabinetes do sistema com os painéis laterais desligados


* Quatro parafusos M12x20 Torx-30 usados no gabinete do sistema com painéis laterais.
* Oito parafusos Torx-30 escareados M6x10 usados no gabinete do sistema com painéis laterais desligados.




 a| 
Kit de calha de suporte
 a| 
Se você pediu trilhos de suporte adicionais com seu gabinete do sistema, cada kit contém um trilho de suporte esquerdo e um direito.


NOTE: Os trilhos de suporte e o kit são projetados para caber somente o gabinete do sistema NetApp de 42U 1280 mm. Não use os trilhos ou um kit de trilho de outros gabinetes do sistema porque eles não foram projetados para uso no gabinete do sistema de 42U 1280 mm.

* Uma calha de suporte esquerda e direita
* Dois parafusos por trilho para fixar o trilho na estrutura do gabinete do sistema




 a| 
Chave crescente
 a| 
A chave crescente é utilizada para remover os suportes de fixação na palete de embalagem, ajustar os pés de nivelamento do armário do sistema e instalar os suportes do kit de parafusos, se tiverem sido encomendados.

|===