---
permalink: a320/chassis-replace-overview.html 
sidebar: sidebar 
keywords: aff, a320, aff a320, replace, chassis, fan, controller, module, impair, model, shut, down, replacing, remove, move, equipment, rack, complete, replacement, process, replace the chassis, shut down the controllers when replacing a chassis, remove the controller modules, move the fans, replace a chassis from within the equipment rack or system cabinet, install the controller modules, complete the replacement process 
summary: Substituir um chassis com deficiência o novo chassis do mesmo modelo que o chassis com deficiência. 
---
= Descrição geral da substituição do chassis - AFF A320
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para substituir o chassis, tem de mover as ventoinhas e os módulos do controlador do chassis afetado para o novo chassis do mesmo modelo que o chassis danificado.

Todos os outros componentes do sistema devem estar funcionando corretamente; caso contrário, você deve entrar em Contato com o suporte técnico.

* Pode utilizar este procedimento com todas as versões do ONTAP suportadas pelo seu sistema.
* Este procedimento é escrito com a suposição de que você está movendo os módulos do controlador para o novo chassi e que o chassi é um novo componente do NetApp.
* Este procedimento é disruptivo. Para um cluster de dois nós, você terá uma interrupção de serviço completa e uma interrupção parcial em um cluster de vários nós.

