---
permalink: fas500f/bootmedia-encryption-restore.html 
sidebar: sidebar 
keywords: fas500f, post boot media replacement steps for okm, nse, and nve 
summary: 'Uma vez que as variáveis de ambiente estejam marcadas, você deve concluir etapas específicas para sistemas que tenham o Gerenciador de chaves integrado (OKM), a criptografia de armazenamento NetApp (NSE) ou a criptografia de volume NetApp (NVE) ativada.' 
---
= Restaure OKM, NSE e NVE conforme necessário - FAS500f
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois que as variáveis de ambiente estiverem marcadas, você deverá concluir etapas específicas para sistemas que tenham o Gerenciador de chaves integrado (OKM), a criptografia de armazenamento NetApp (NSE) ou a criptografia de volume NetApp (NVE) habilitados.

. Determine qual seção você deve usar para restaurar suas configurações OKM, NSE ou NVE: Se o NSE ou NVE estiverem ativados junto com o Gerenciador de chaves integrado, você deverá restaurar as configurações capturadas no início deste procedimento.
+
** Se o NSE ou NVE estiverem ativados e o Gerenciador de chaves integrado estiver habilitado, vá para <<Restaure o NVE ou o NSE quando o Gerenciador de chaves integrado estiver habilitado>>.
** Se o NSE ou NVE estiverem ativados para o ONTAP 9.6, vá para <<Restaure o NSE/NVE em sistemas executando o ONTAP 9.6 e posterior>>.






== Restaure o NVE ou o NSE quando o Gerenciador de chaves integrado estiver habilitado

.Passos
. Conete o cabo do console ao controlador de destino.
. Use o `boot_ontap` comando no prompt Loader para inicializar o controlador.
. Verifique a saída da consola:
+
[cols="1,2"]
|===
| *Se o console exibir...* | *Então...* 


 a| 
O prompt Loader
 a| 
Inicialize o controlador no menu de inicialização: `boot_ontap menu`



 a| 
Esperando por giveback
 a| 
.. Digite `Ctrl-C` no prompt
.. Na mensagem: Você deseja interromper esse nó em vez de esperar [y/n]? , introduza: `y`
.. No prompt Loader, digite o `boot_ontap menu` comando.


|===
. No Menu de inicialização, digite o comando oculto `recover_onboard_keymanager` e responda `y` no prompt
. Introduza a frase-passe para o gestor de chaves integrado que obteve do cliente no início deste procedimento.
. Quando solicitado a inserir os dados de backup, cole os dados de backup capturados no início deste procedimento, quando solicitado. Cole a saída do `security key-manager backup show` comando OU `security key-manager onboard show-backup`
+

NOTE: Os dados são emitidos a partir de qualquer um dos `security key-manager backup show` comandos ou `security key-manager onboard show-backup`.

+
Exemplo de dados de backup:

+
[]
====
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA . . . AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

--------------------------------------------------------------

====
. No menu Boot (Inicialização), selecione a opção para normal Boot (Inicialização normal).
+
O sistema arranca para aguardar o prompt de espera para giveback...

. Confirme se o controlador de destino está pronto para giveback com o `storage failover show` comando.
. Giveback apenas o CFO agrega com o `storage failover giveback -fromnode local -only-cfo-aggregates true` comando.
+
** Se o comando falhar por causa de um disco com falha, desengate fisicamente o disco com falha, mas deixe o disco no slot até que uma substituição seja recebida.
** Se o comando falhar devido a sessões CIFS abertas, verifique com o cliente como fechar sessões CIFS.
+

NOTE: Encerrar CIFS pode causar perda de dados.

** Se o comando falhar porque o parceiro "não está pronto", aguarde 5 minutos para que os NVMEMs sincronizem.
** Se o comando falhar por causa de um processo NDMP, SnapMirror ou SnapVault, desative o processo. Consulte o Centro de Documentação apropriado para obter mais informações.


. Uma vez que o giveback seja concluído, verifique o status de failover e giveback com os `storage failover show` comandos e ``storage failover show`-giveback.
+
Apenas os agregados CFO (agregados de raiz e agregados de dados de estilo CFO) serão mostrados.

. Mova o cabo do console para o controlador de destino.
+
.. Se você estiver executando o ONTAP 9.6 ou posterior, execute a sincronização integrada do gerenciador de chaves de segurança:
.. Execute o `security key-manager onboard sync` comando e insira a senha quando solicitado.
.. Digite o `security key-manager key query` comando para ver uma exibição detalhada de todas as chaves armazenadas no gerenciador de chaves integrado e verifique se a `Restored` coluna é `yes/true` para todas as chaves de autenticação.
+

NOTE: Se a `Restored` coluna for diferente `yes/true` do , contacte o apoio ao Cliente.

.. Aguarde 10 minutos para que a chave seja sincronizada no cluster.


. Mova o cabo do console para o controlador do parceiro.
. Devolva o controlador de destino usando o `storage failover giveback -fromnode local` comando.
. Verifique o status da giveback, 3 minutos após a conclusão do relatório, usando o `storage failover show` comando.
+
Se a giveback não estiver concluída após 20 minutos, contacte o apoio ao Cliente.

. No prompt do clustershell, digite o `net int show -is-home false` comando para listar as interfaces lógicas que não estão em seu controlador principal e porta.
+
Se alguma interface estiver listada como `false`, reverta essas interfaces de volta para sua porta inicial usando o `net int revert -vserver Cluster -lif _nodename_` comando.

. Mova o cabo do console para o controlador de destino e execute o `version -v` comando para verificar as versões do ONTAP.
. Restaure o giveback automático se você o desativou usando o `storage failover modify -node local -auto-giveback true` comando.




== Restaure o NSE/NVE em sistemas executando o ONTAP 9.6 e posterior

.Passos
. Conete o cabo do console ao controlador de destino.
. Use o `boot_ontap` comando no prompt Loader para inicializar o controlador.
. Verifique a saída da consola:
+
|===


| *Se o console exibir...* | *Então...* 


 a| 
O aviso de início de sessão
 a| 
Avance para o passo 7.



 a| 
A aguardar pela giveback...
 a| 
.. Faça login no controlador do parceiro.
.. Confirme se o controlador de destino está pronto para giveback com o `storage failover show` comando.


|===
. Mova o cabo do console para o controlador parceiro e devolva o armazenamento do controlador de destino usando o `storage failover giveback -fromnode local -only-cfo-aggregates true local` comando.
+
** Se o comando falhar por causa de um disco com falha, desengate fisicamente o disco com falha, mas deixe o disco no slot até que uma substituição seja recebida.
** Se o comando falhar devido a sessões CIFS abertas, verifique com o cliente como fechar sessões CIFS.
+

NOTE: Encerrar CIFS pode causar perda de dados.

** Se o comando falhar porque o parceiro "não está pronto", aguarde 5 minutos para que os NVMEMs sincronizem.
** Se o comando falhar por causa de um processo NDMP, SnapMirror ou SnapVault, desative o processo. Consulte o Centro de Documentação apropriado para obter mais informações.


. Aguarde 3 minutos e verifique o status do failover com o `storage failover show` comando.
. No prompt do clustershell, digite o `net int show -is-home false` comando para listar as interfaces lógicas que não estão em seu controlador principal e porta.
+
Se alguma interface estiver listada como `false`, reverta essas interfaces de volta para sua porta inicial usando o `net int revert -vserver Cluster -lif _nodename_` comando.

. Mova o cabo do console para o controlador de destino e execute o `version -v` comando para verificar as versões do ONTAP.
. Restaure o giveback automático se você o desativou usando o `storage failover modify -node local -auto-giveback true` comando.
. Use o `storage encryption disk show` prompt at the clustershell, para revisar a saída.
. Use o `security key-manager key query` comando para exibir as IDs de chave das chaves de autenticação armazenadas nos servidores de gerenciamento de chaves.
+
** Se a `Restored` coluna `yes/true` estiver concluída, pode concluir o processo de substituição.
** Se a `Key Manager type` `external` `Restored` coluna for diferente `yes/true` de , use o `security key-manager external restore` comando para restaurar os IDs de chave das chaves de autenticação.
+

NOTE: Se o comando falhar, entre em Contato com o suporte ao Cliente.

** Se a `Key Manager type` `onboard` `Restored` coluna for diferente `yes/true` de , use o `security key-manager onboard sync` comando para sincronizar novamente o tipo Gerenciador de chaves.
+
Use o `security key-manager key query` comando para verificar se a `Restored` coluna é `yes/true` para todas as chaves de autenticação.



. Conete o cabo do console ao controlador do parceiro.
. Devolva o controlador usando o `storage failover giveback -fromnode local` comando.
. Restaure o giveback automático se você o desativou usando o `storage failover modify -node local -auto-giveback true` comando.

