---
permalink: fas500f/chassis-replace-prepare.html 
sidebar: sidebar 
keywords: fas500f, replace the chassis 
summary: Prepare-se para substituir o chassi com defeito em seu sistema FAS500f, identificando o chassi com defeito, verificando os componentes de substituição e etiquetando os cabos e módulos do controlador. 
---
= Prepare-se para substituir o chassi - FAS500f
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prepare-se para substituir o chassi com defeito em seu sistema FAS500f, identificando o chassi com defeito, verificando os componentes de substituição e etiquetando os cabos e módulos do controlador.

.Passos
. Conete-se à porta do console serial à interface e monitore o sistema.
. Ligue o LED de localização do controlador:
+
.. Use o `system controller location-led show` Comando para exibir o estado atual do LED de localização.
.. Ligue o LED de localização:
+
`system controller location-led modify -node _node1_ -state on`

+
O LED de localização permanece aceso durante 30 minutos.



. Antes de abrir a embalagem, examine o rótulo e verifique o seguinte:
+
** Número da peça do componente
** Descrição da peça
** Quantidade na caixa


. Retire o conteúdo da embalagem e guarde-a para devolver o componente com defeito à NetApp.
. Identifique todos os cabos conectados ao sistema de armazenamento.  Isso garante a correta recablagem posteriormente neste procedimento.
. Conecte-se com a terra, caso ainda não esteja conectado.


.O que se segue?
Após se preparar para substituir o hardware do chassi do seu FAS500f, você precisa link:chassis-replace-shutdown.html["desligue os controladores"].
