---
permalink: c400/overview.html 
sidebar: sidebar 
keywords: AFF C400 specifications, AFF C400 specs, NetApp AFF C400, AFF C400 hardware 
summary: Especificações principais para o sistema de armazenamento AFF C400 
---
= Especificações principais do AFF C400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A seguir estão algumas especificações selecionadas para o AFF C400.  Visita https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) para uma lista completa das especificações do AFF C400 .  Esta página reflete um único par de alta disponibilidade.



=== Especificações principais do AFF C400

Configuração da plataforma: Par de HA de chassi único AFF C400 , pacote Ethernet

Capacidade Máxima de Bruto: 2,9472 PB

Memória: 256.0000 GB

Fator de forma: chassi 4U com 2 controladores HA

Versão ONTAP : b_startONTAP: 9.16.1P2b_end

Slots de expansão PCIe: 10

Versão mínima do ONTAP : ONTAP 9.10.1P15



=== Máximos de Escalabilidade

|===


| Tipo | Pares HA | Capacidade bruta | Memória Máxima 


| NAS | 12 | 35,4 PB / 31,4 PiB | 3072 GB 


| SAN | 6 | 17,7 PB / 15,7 PiB | 1536 GB 


| Par HA |  | 2,9 PB / 2,6 PiB | 256,0000 
|===


=== IO



==== IO integrado

|===


| Protocolo | Portos 


| Ethernet 100 Gbps | 4 


| Ethernet 25 Gbps | 12 
|===


==== Total de IO

|===


| Protocolo | Portos 


| Ethernet 100 Gbps | 24 


| Ethernet 25 Gbps | 28 


| Ethernet 10 Gbps | 32 


| FC 32 Gbps | 40 


| NVMe/FC 32 Gbps | 40 


|  | 0 
|===


==== Portas de Gestão

|===


| Protocolo | Portos 


| Ethernet 1 Gbps | 2 


| RS-232 115 Kbps | 4 


| USB 12 Mbps | 4 
|===


=== Rede de armazenamento suportada

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NFSv3/RDMA; NFSv4/RDMA; NVMe/FC; NVMe/TCP; S3; S3 com NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Especificações do ambiente do sistema

* Potência típica: 4209 BTU/h
* Pior cenário de potência: 5215 BTU/h
* Peso: 110,0 lbbr/49,9 kg
* Altura: 4U
* Largura: 19” compatível com rack IEC (17,6” 44,7 cm)
* Profundidade: 32,6”br/(34,7” com suporte de gerenciamento de cabos)
* Temperatura/Altitude/Umidade de operação: 10°C a 35°Cbr/50°F a br/95°F) atbr/= 3048mbr/= 10000 pés) de elevação; 8% a 80%br/umidade relativa, sem condensação
* Temperatura/Umidade fora de operação: -40°C a 70°C (-40°F a 158°F) até 12192m (40000 pés)<br/>10% a 95% de umidade relativa, sem condensação, no recipiente original
* Ruído acústico: Potência sonora declarada (LwAd): 8,5;br/Pressão sonora (LpAm) (posições de observação): 67,2 dB




=== Conformidade

* Certificações EMC/EMI: AMCA, FCC, ICES, KC, Marrocos, VCCI
* Certificações de segurança: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificações Segurança/EMC/EMI: EAC, UKRSEPRO
* Certificações Segurança/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normas EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normas de segurança: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilidade

Controlador de gerenciamento de placa base baseado em Ethernet (BMC) e interface de gerenciamento ONTAP ; Controladores redundantes de troca a quente; Fontes de alimentação redundantes de troca a quente; Gerenciamento SAS em banda por meio de conexões SAS; [//] 2025-10-15 ontap-systems-internal/issues/1357
