---
permalink: asa-c800/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: asa c800, shutdown the controllers 
summary: Para substituir o chassi, você deve desligar os controladores. 
---
= Desligue os controladores - ASA C800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Desligue os controladores do seu sistema de armazenamento ASA C800 para evitar perda de dados e garantir a estabilidade do sistema ao substituir o chassi.

Este procedimento destina-se a sistemas com duas configurações de nós. Para obter mais informações sobre o desligamento normal ao fazer manutenção de um cluster, https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/What_is_the_procedure_for_graceful_shutdown_and_power_up_of_a_storage_system_during_scheduled_power_outage["Desligue e ligue o seu sistema de armazenamento de dados - base de dados de Conhecimento da NetApp"] consulte .

.Antes de começar
* Certifique-se de que tem as permissões e credenciais necessárias:
+
** Credenciais de administrador local para o ONTAP.
** BMC accessability para cada controlador.


* Certifique-se de que tem as ferramentas e o equipamento necessários para a substituição.
* Como uma prática recomendada antes do desligamento, você deve:
+
** Execute mais https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["verificações de integridade do sistema"].
** Atualize o ONTAP para uma versão recomendada para o sistema.
** Resolva qualquer https://activeiq.netapp.com/["Alertas e riscos de bem-estar do Active IQ"]. Tome nota de quaisquer avarias atualmente no sistema, tais como LEDs nos componentes do sistema.




.Passos
. Faça login no cluster através de SSH ou faça login de qualquer nó no cluster usando um cabo de console local e um laptop/console.
. Impedir que todos os clientes/hosts acessem dados no sistema NetApp.
. Suspender trabalhos de cópia de segurança externos.
. Se o AutoSupport estiver ativado, suprimir a criação de casos e indicar quanto tempo espera que o sistema esteja offline:
+
`system node autosupport invoke -node * -type all -message "MAINT=2h Replace chassis"`

. Identifique o endereço SP/BMC de todos os nós de cluster:
+
`system service-processor show -node * -fields address`

. Saia do shell do cluster:
+
`exit`

. Faça login no SP/BMC via SSH usando o endereço IP de qualquer um dos nós listados na saída da etapa anterior para monitorar o progresso.
+
Se você estiver usando um console/laptop, faça login no controlador usando as mesmas credenciais de administrador de cluster.

. Parar os dois nós localizados no chassi com deficiência:
+
`system node halt -node <node1>,<node2> -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true`

+

NOTE: Para clusters que usam o SnapMirror síncrono operando no modo StrictSync: `system node halt -node <node1>,<node2>  -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true -ignore-strict-sync-warnings true`

. Digite *y* para cada controlador no cluster quando você vir:
+
`Warning: Are you sure you want to halt node _<node_name>_? {y|n}:`

. Aguarde que cada controlador pare e exiba o prompt Loader.


.O que se segue?
Após desligar os controladores,link:chassis-replace-move-hardware.html["substitua o chassis"] .
