---
permalink: asa-c800/maintain-overview.html 
sidebar: sidebar 
keywords: asa C800 maintenance, maintenance, repairing C800, repairing asa C800, replace asa C800 components, replace asa C800 components 
summary: Mantenha o hardware ASA C800 
---
= Manter o hardware do ASA C800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para o sistema de armazenamento ASA C800, pode executar procedimentos de manutenção nos seguintes componentes.



== Suporte de arranque

A Mídia de inicialização armazena um conjunto primário e secundário de arquivos de imagem de inicialização que o sistema usa quando ele é inicializado.



== Chassis

O chassi é o gabinete físico que abriga todos os componentes do controlador, como a unidade controladora/CPU, fonte de alimentação e e/S.



== Controlador

Um controlador consiste em uma placa, firmware e software. Controla as unidades e implementa as funções do ONTAP.



== DIMM

Você deve substituir um DIMM (módulo de memória dual in-line) quando houver uma incompatibilidade de memória ou se tiver um DIMM com falha.



== Condução

Uma unidade é um dispositivo que fornece a Mídia de armazenamento físico para dados.



== Ventoinha

A ventoinha arrefece o controlador.



== NVDIMM

O NVDIMM (módulo de memória em linha dupla não volátil) gerencia a transferência de dados da memória volátil para o armazenamento não volátil e mantém a integridade dos dados em caso de perda de energia ou desligamento do sistema.



== Bateria NVDIMM

Uma bateria NVDIMM é responsável por manter a energia do módulo NVDIMM.



== Placa PCIe

Uma placa PCIe (Peripheral Component Interconnect Express) é uma placa de expansão que se coneta ao slot PCIe da placa-mãe.



== Fonte de alimentação

Uma fonte de alimentação fornece uma fonte de alimentação redundante em um compartimento de controladora.



== Bateria de relógio em tempo real

Uma bateria de relógio em tempo real preserva as informações de data e hora do sistema se a energia estiver desligada.
