---
permalink: asa-r2-c30/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa c30, replace the boot media 
summary: 'Antes de substituir a mídia de inicialização no seu sistema de armazenamento ASA C30, certifique-se de atender aos requisitos e considerações necessários para uma substituição bem-sucedida. Isso inclui verificar se você possui a mídia de inicialização de substituição correta, confirmar se a porta e0S (chave e0M) no controlador danificado está funcionando corretamente e determinar se o Gerenciador de Chaves Onboard (OKM) ou o Gerenciador de Chaves Externo (EKM) está habilitado.' 
---
= Requisitos para substituir o suporte de arranque - ASA C30
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de substituir a mídia de inicialização no seu sistema de armazenamento ASA C30, certifique-se de atender aos requisitos e considerações necessários para uma substituição bem-sucedida. Isso inclui verificar se você possui a mídia de inicialização de substituição correta, confirmar se a porta e0S (chave e0M) no controlador danificado está funcionando corretamente e determinar se o Gerenciador de Chaves Onboard (OKM) ou o Gerenciador de Chaves Externo (EKM) está habilitado.

* Você deve substituir o componente com falha por um componente FRU de substituição da mesma capacidade que recebeu do NetApp.
* A porta e0S (chave inglesa e0M) é usada para comunicação entre os dois controladores durante o processo de recuperação de inicialização automatizada. Certifique-se de que a porta e0S do controlador com defeito esteja funcionando corretamente.
* Para OKM, você precisa do conteúdo do arquivo de senha OKM.
* Para EKM, você precisa de cópias dos seguintes arquivos do nó do parceiro:
+
** arquivo /cfcard/kmip/servers.cfg.
** arquivo /cfcard/kmip/certs/client.crt.
** arquivo /cfcard/kmip/certs/client.key.
** Arquivo /cfcard/kmip/certs/CA.pem.


* É fundamental aplicar os comandos ao controlador correto ao substituir a mídia de inicialização danificada:
+
** O _controlador danificado_ é o controlador no qual você está executando a manutenção.
** O _controlador saudável_ é o parceiro HA do controlador prejudicado.




.O que vem a seguir
Depois de analisar os requisitos do suporte de arranque, pode link:bootmedia-shutdown-bmr.html["desligue o controlador"].
