---
permalink: asa-r2-c30/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa c30, replace the boot media 
summary: Antes de substituir a mídia de inicialização no seu ASA C30 sistema de storage, certifique-se de atender aos requisitos e considerações necessários para uma substituição bem-sucedida. Isso inclui verificar se você possui a mídia de inicialização de substituição correta, confirmar se a porta e0M wrench no controlador com defeito está funcionando corretamente e determinar se o Onboard Key Manager ou o External Key Manager está habilitado. 
---
= Requisitos para substituir o suporte de arranque - ASA C30
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de substituir a mídia de inicialização no seu sistema de armazenamento ASA C30, certifique-se de atender aos requisitos e considerações necessários para uma substituição bem-sucedida.  Isso inclui verificar se você tem a mídia de inicialização de substituição correta, confirmar se a porta e0M (chave inglesa) no controlador danificado está funcionando corretamente e determinar se o Onboard Key Manager (OKM) ou o External Key Manager (EKM) está habilitado.

[NOTE]
====
NetApp recomenda fortemente que você habilite o registro de logs no console nos dispositivos que estiver utilizando e execute as seguintes ações ao realizar este procedimento:

* Deixe AutoSupport ativado durante a sua manutenção. Isso permite que o suporte da NetApp receba informações de diagnóstico caso ocorram problemas.
* Habilite o registro de sessão para todas as sessões da CLI. Isso cria um registro completo de todos os comandos e da saída do sistema durante a atividade de manutenção. Para obter orientações sobre como habilitar o registro de sessão, consulte  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Como configurar o PuTTY para obter conectividade ideal com sistemas ONTAP"^].


====
* Você deve substituir o componente com falha por um componente FRU de substituição da mesma capacidade que recebeu do NetApp.
* Verifique se a interface e0S (porta de chave inglesa e0M) no controlador com defeito não está com falha.
+
A porta e0M é usada para comunicação entre os dois controladores durante o processo de recuperação de inicialização automatizada.

* Para o OKM, você precisa da senha de todo o cluster e também dos dados de backup.
* Para EKM, você precisa de cópias dos seguintes arquivos do nó do parceiro:
+
** arquivo /cfcard/kmip/servers.cfg.
** arquivo /cfcard/kmip/certs/client.crt.
** arquivo /cfcard/kmip/certs/client.key.
** Arquivo /cfcard/kmip/certs/CA.pem.


* É fundamental aplicar os comandos ao controlador correto ao substituir a mídia de inicialização danificada:
+
** O _controlador danificado_ é o controlador no qual você está executando a manutenção.
** O _controlador saudável_ é o parceiro HA do controlador prejudicado.




.O que vem a seguir
Depois de analisar os requisitos do suporte de arranque, pode link:bootmedia-shutdown-bmr.html["desligue o controlador"].
