---
permalink: asa-r2-c30/io-module-overview.html 
sidebar: sidebar 
keywords: asa c30, replace io module, add io module, hotswap io module 
summary: O sistema de armazenamento ASA C30 oferece flexibilidade na expansão ou substituição de módulos de E/S para melhorar a conectividade e o desempenho da rede. Adicionar ou substituir um módulo de e/S é essencial ao atualizar recursos de rede ou endereçar um módulo com falha. 
---
= Visão geral da manutenção do módulo de E/S - ASA C30
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O sistema de armazenamento ASA C30 oferece flexibilidade na expansão ou substituição de módulos de E/S para aprimorar a conectividade e o desempenho da rede. Adicionar, fazer hot swap ou substituir um módulo de E/S é essencial ao atualizar os recursos da rede ou solucionar um módulo com falha.

Você pode substituir um módulo de E/S com defeito no seu sistema de armazenamento pelo mesmo tipo de módulo de E/S ou por um tipo diferente. Você pode fazer hot-swap de um cluster e de um módulo de E/S de alta disponibilidade quando o seu sistema de armazenamento atender a requisitos específicos. Você também pode adicionar um módulo de E/S a um sistema de armazenamento com slots disponíveis.

* link:io-module-add.html["Adicione um módulo de e/S."]
+
A adição de módulos de e/S adicionais pode melhorar a redundância, ajudando a garantir que o sistema de storage permaneça operacional mesmo que um módulo de e/S falhe.

* link:io-module-hotswap.html["Substituição a quente de um módulo de E/S"]
+
É possível realizar a substituição a quente de determinados módulos de E/S por um módulo de E/S equivalente para restaurar o sistema de storage ao seu estado operacional ideal. A substituição a quente é feita sem a necessidade de realizar uma tomada manual.

+
Para usar este procedimento, seu sistema de armazenamento deve estar executando o ONTAP 9.17.1 ou posterior e atender a requisitos específicos do sistema.

* link:io-module-replace.html["Substitua um módulo de e/S."]
+
A substituição de um módulo de e/S com falha pode restaurar o sistema de armazenamento ao seu estado de funcionamento ideal.


