---
permalink: a250/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: a250, replace the boot media 
summary: Antes de substituir a mídia de inicialização do seu AFF A250, certifique-se de atender aos requisitos necessários para uma substituição bem-sucedida. Isso inclui garantir que você tenha um pen drive USB com a quantidade adequada de armazenamento e verificar se você possui o dispositivo de inicialização de substituição correto. 
---
= Requisitos para recuperação manual da mídia de inicialização - AFF A250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de substituir a mídia de inicialização do seu AFF A250, certifique-se de atender aos requisitos necessários para uma substituição bem-sucedida. Isso inclui garantir que você tenha um pen drive USB com a quantidade adequada de armazenamento e verificar se você possui o dispositivo de inicialização de substituição correto.

Se o seu sistema de storage estiver executando ONTAP 9.18.1 ou posterior, use o link:bootmedia-replace-workflow-bmr.html["procedimento automatizado de recuperação de inicialização"]. Se o seu sistema estiver executando uma versão anterior do ONTAP, você deve usar o procedimento de recuperação de inicialização manual.

.Pen drive USB
* Certifique-se de ter uma unidade flash USB formatada para FAT32.
* O USB deve ter capacidade de armazenamento suficiente para armazenar o  `image_xxx.tgz` arquivo.


.Preparação do arquivo
Copie o  `image_xxx.tgz` arquivo para o pen drive USB. Este arquivo será usado quando você transferir a imagem ONTAP usando o pen drive USB.

.Substituição de componentes
Substitua o componente com falha pelo componente de substituição fornecido pela NetApp.

.Identificação do controlador
É fundamental aplicar os comandos ao controlador correto ao substituir a mídia de inicialização danificada:

* O _controlador danificado_ é o controlador no qual você está executando a manutenção.
* O _controlador saudável_ é o parceiro HA do controlador prejudicado.


.O que se segue?
Depois de rever os requisitos para substituir o suporte de arranque, tem de link:bootmedia-encryption-preshutdown-checks.html["verifique o suporte e o status da chave de criptografia na mídia de inicialização"].
