---
permalink: a250/overview.html 
sidebar: sidebar 
keywords: AFF A250 specifications, AFF A250 specs, NetApp AFF A250, AFF A250 hardware 
summary: Especificações principais para o sistema de armazenamento AFF A250 
---
= Especificações principais do AFF A250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A seguir estão algumas especificações selecionadas para o AFF A250.  Visita https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) para uma lista completa das especificações do AFF A250 .  Esta página reflete um único par de alta disponibilidade.



=== Especificações principais do AFF A250

Configuração da plataforma: Par de chassis único AFF A250 HA

Capacidade Máxima de Bruto: 1,1016 PB

Memória: 128.0000 GB

Fator de forma: chassi 2U com 2 controladores HA e 24 slots de unidade

Versão ONTAP : b_startONTAP: 9.16.1P2b_end

Slots de expansão PCIe: 4

Versão mínima do ONTAP : ONTAP 9.8RC1



=== Máximos de Escalabilidade

|===


| Tipo | Pares HA | Capacidade bruta | Memória Máxima 


| NAS | 12 | 13,2 PB / 11,7 PiB | 1536 GB 


| SAN | 6 | 6,6 PB / 5,9 PiB | 768 GB 


| Par HA |  | 1,1 PB / 1,0 PiB | 128,0000 
|===


=== IO



==== IO integrado

|===


| Protocolo | Portos 


| Ethernet 25 Gbps | 4 


| Ethernet 10 Gbps | 4 
|===


==== Total de IO

|===


| Protocolo | Portos 


| Ethernet 100 Gbps | 4 


| Ethernet 25 Gbps | 20 


| Ethernet 10 Gbps | 4 


| FC 32 Gbps | 16 


| NVMe/FC 32 Gbps | 16 


|  | 0 


| SAS 12 Gbps | 8 
|===


==== Portas de Gestão

|===


| Protocolo | Portos 


| Ethernet 1 Gbps | 2 


| RS-232 115 Kbps | 4 


| USB 12 Mbps | 4 
|===


=== Rede de armazenamento suportada

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NVMe/FC; NVMe/TCP; S3; S3 com NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Especificações do ambiente do sistema

* Potência típica: 2642 BTU/h
* Pior cenário de potência: 3476 BTU/h
* Peso: 54,3 lbbr/24,6 kg
* Altura: 2U
* Largura: 19” compatível com rack IEC (17,6” 44,7 cm)
* Profundidade:
* Temperatura/Altitude/Umidade de operação: 10°C a 35°Cbr/50°F a br/95°F) atbr/= 3048mbr/= 10000 pés) de elevação; 8% a 80%br/umidade relativa, sem condensação
* Temperatura/Umidade fora de operação: -40°C a 70°C (-40°F a 158°F) até 12192m (40000 pés)<br/>10% a 95% de umidade relativa, sem condensação, no recipiente original
* Ruído acústico: Potência sonora declarada (LwAd): 7,2;br/Pressão sonora (LpAm) (posições de observação): 69,1 dB




=== Conformidade

* Certificações EMC/EMI: AMCA, FCC, ICES, KC, Marrocos, VCCI
* Certificações de segurança: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificações Segurança/EMC/EMI: EAC, UKRSEPRO
* Certificações Segurança/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normas EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normas de segurança: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilidade

Controlador de gerenciamento de placa base baseado em Ethernet (BMC) e interface de gerenciamento ONTAP ; Controladores redundantes de troca a quente; Fontes de alimentação redundantes de troca a quente; Gerenciamento SAS em banda por meio de conexões SAS para prateleiras externas;
