---
permalink: fas8200/bootmedia-recovery-image-boot-options.html 
sidebar: sidebar 
keywords: fas8200, boot the recovery image 
summary: O procedimento para inicializar o controlador prejudicado a partir da imagem de recuperação depende se o sistema está em uma configuração de MetroCluster de dois nós. 
---
= Inicie a imagem de recuperação - FAS8200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O procedimento para inicializar o controlador prejudicado a partir da imagem de recuperação depende se o sistema está em uma configuração de MetroCluster de dois nós.



== Opção 1: A maioria dos sistemas

: Você deve inicializar a imagem ONTAP da unidade USB, restaurar o sistema de arquivos e verificar as variáveis ambientais.

Este procedimento aplica-se a sistemas que não estão em uma configuração de MetroCluster de dois nós.

.Passos
. A partir do prompt Loader, inicialize a imagem de recuperação da unidade flash USB: `boot_recovery`
+
A imagem é transferida da unidade flash USB.

. Quando solicitado, insira o nome da imagem ou aceite a imagem padrão exibida dentro dos colchetes na tela.
. Restaure o sistema de ficheiros var:
+
[cols="1,2"]
|===
| Se o seu sistema tem... | Então... 


 a| 
Uma ligação de rede
 a| 
.. Pressione `y` quando solicitado para restaurar a configuração de backup.
.. Defina o controlador saudável para nível de privilégio avançado: `set -privilege advanced`
.. Execute o comando Restore backup: `system node restore-backup -node local -target-address _impaired_node_IP_address_`
.. Retorne o controlador ao nível de administração: `set -privilege admin`
.. Pressione `y` quando solicitado a usar a configuração restaurada.
.. Pressione `y` quando solicitado para reiniciar o controlador.




 a| 
Sem ligação à rede
 a| 
.. Pressione `n` quando solicitado para restaurar a configuração de backup.
.. Reinicie o sistema quando solicitado pelo sistema.
.. Selecione a opção *Update flash from backup config* (Sync flash) no menu exibido.
+
Se for solicitado que você continue com a atualização, `y` pressione .



|===
. Certifique-se de que as variáveis ambientais estão definidas como esperado:
+
.. Leve o controlador para o prompt Loader.
.. Verifique as configurações de variáveis de ambiente com o `printenv` comando.
.. Se uma variável de ambiente não for definida como esperado, modifique-a com o `setenv __environment-variable-name__ __changed-value__` comando.
.. Salve suas alterações usando o `savenv` comando.


. O próximo depende da configuração do sistema:
+
** Se o sistema tiver o gerenciador de chaves integrado, NSE ou NVE configurado, vá para xref:bootmedia-encryption-restore.adoc[Restaure OKM, NSE e NVE conforme necessário]
** Se o sistema não tiver o gerenciador de chaves integrado, NSE ou NVE configurado, execute as etapas nesta seção.


. No prompt Loader, digite o `boot_ontap` comando.
+
[cols="1,2"]
|===
| Se você ver... | Então... 


 a| 
O aviso de início de sessão
 a| 
Vá para a próxima etapa.



 a| 
A aguardar pela giveback...
 a| 
.. Faça login no controlador do parceiro.
.. Confirme se o controlador de destino está pronto para giveback com o `storage failover show` comando.


|===
. Conete o cabo do console ao controlador do parceiro.
. Devolva o controlador usando o `storage failover giveback -fromnode local` comando.
. No prompt do cluster, verifique as interfaces lógicas com o `net int -is-home false` comando.
+
Se alguma interface estiver listada como "false", reverta essas interfaces de volta para sua porta inicial usando o `net int revert` comando.

. Mova o cabo do console para o controlador reparado e execute o `version -v` comando para verificar as versões do ONTAP.
. Restaure o giveback automático se você o desativou usando o `storage failover modify -node local -auto-giveback true` comando.




== Opção 2: O controlador está em um MetroCluster de dois nós

Você deve inicializar a imagem ONTAP a partir da unidade USB e verificar as variáveis ambientais.

Este procedimento se aplica a sistemas em uma configuração de MetroCluster de dois nós.

.Passos
. A partir do prompt Loader, inicialize a imagem de recuperação da unidade flash USB: `boot_recovery`
+
A imagem é transferida da unidade flash USB.

. Quando solicitado, insira o nome da imagem ou aceite a imagem padrão exibida dentro dos colchetes na tela.
. Após a instalação da imagem, inicie o processo de restauração:
+
.. Pressione `n` quando solicitado para restaurar a configuração de backup.
.. Pressione `y` quando solicitado a reinicializar para começar a usar o software recém-instalado.
+
Você deve estar preparado para interromper o processo de inicialização quando solicitado.



. À medida que o sistema for inicializado, pressione `Ctrl-C` depois que a `Press Ctrl-C for Boot Menu` mensagem for exibida. E, quando o Menu de inicialização for exibido, selecione a opção 6.
. Verifique se as variáveis ambientais estão definidas como esperado.
+
.. Leve o nó para o prompt Loader.
.. Verifique as configurações de variáveis de ambiente com o `printenv` comando.
.. Se uma variável de ambiente não for definida como esperado, modifique-a com o `setenv __environment-variable-name__ __changed-value__` comando.
.. Salve suas alterações usando o `savenv` comando.
.. Reinicie o nó.



