---
permalink: afx-1k/bootmedia-recovery-image-boot.html 
sidebar: sidebar 
keywords: afx 1k, boot the recovery image 
summary: Após instalar o novo dispositivo de mídia de inicialização no seu sistema de armazenamento AFX 1K, você pode iniciar o processo automatizado de recuperação de mídia de inicialização para restaurar a configuração do nó parceiro. 
---
= Inicialize a imagem de recuperação - AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Após instalar o novo dispositivo de mídia de inicialização no seu sistema de armazenamento AFX 1K, você pode iniciar o processo automatizado de recuperação de mídia de inicialização para restaurar a configuração do nó parceiro.

.Sobre esta tarefa
Durante o processo de recuperação, o sistema verifica se a criptografia está habilitada e identifica o tipo de criptografia de chave que está sendo usada. Se a criptografia de chave estiver habilitada, o sistema o guiará pelas etapas apropriadas para restaurá-la.

.Antes de começar
* Para o OKM, você precisa da senha de todo o cluster e dos dados de backup.
* Para EKM, você precisa de cópias dos seguintes arquivos do nó do parceiro:
+
** arquivo /cfcard/kmip/servers.cfg.
** arquivo /cfcard/kmip/certs/client.crt.
** arquivo /cfcard/kmip/certs/client.key.
** Arquivo /cfcard/kmip/certs/CA.pem.




.Passos
. No prompt Loader, digite o comando:
+
`boot_recovery -partner`

+
O ecrã apresenta a seguinte mensagem:

+
`Starting boot media recovery (BMR) process. Press Ctrl-C to abort…`

. Monitore o processo de recuperação de instalação de Mídia de inicialização.
+
O processo é concluído e exibe a `Installation complete` mensagem.

. O sistema verifica se há criptografia e tipo de criptografia e exibe uma de duas mensagens. Dependendo da mensagem exibida, execute uma das seguintes ações:
+

IMPORTANT: Ocasionalmente, o processo pode não ser capaz de identificar se o gerenciador de chaves está configurado no sistema. Ele exibirá uma mensagem de erro, perguntará se o gerenciador de chaves está configurado para o sistema e perguntará qual tipo de gerenciador de chaves está configurado. O processo será retomado depois de resolver o problema.

+
.Mostrar exemplo de prompts de localização de erros de configuração
[%collapsible]
====
....
Error when fetching key manager config from partner ${partner_ip}: ${status}

Has key manager been configured on this system

Is the key manager onboard

....
====
+
[cols="1,2"]
|===
| Se você vir esta mensagem... | Faça isso... 


 a| 
`key manager is not configured. Exiting.`
 a| 
A criptografia não está configurada no sistema. Conclua as seguintes etapas:

.. Pressione <enter> quando as mensagens do console pararem.
+
*** Se você vir o prompt de login, vá para a etapa 4.
*** Se você não vir o prompt de login, faça login no nó do parceiro e prossiga para a etapa 4.


.. Vá para a etapa 6 para habilitar a devolução automática, caso ela tenha sido desabilitada.




 a| 
`key manager is configured.`
 a| 
Vá para a etapa 5 para restaurar o gerenciador de chaves apropriado.

O nó acessa o menu de inicialização e executa:

** Opção 10 para sistemas com OKM (Onboard Key Manager).
** Opção 11 para sistemas com o External Key Manager (EKM).


|===
. Se a criptografia não estiver instalada no sistema e o prompt de login não for exibido. Conclua as seguintes etapas:
+
.. Devolva apenas a raiz com a opção override-destination-checks:
+
`storage failover giveback -ofnode impaired-node -only-root true -override -destination-checks true`

+

NOTE: Este comando está disponível somente no modo Diagnóstico. Para obter detalhes, consulte link:https://docs.netapp.com/us-en/ontap/system-admin/administrative-privilege-levels-concept.html["Níveis de privilégio para comandos ONTAP CLI"^] .

+
Se encontrar erros, https://support.netapp.com["Suporte à NetApp"] contacte .

.. Aguarde 5 minutos após a conclusão do relatório de giveback e verifique o status de failover e o status de giveback:
+
`storage failover show`e `storage failover show-giveback`

+

NOTE: O comando a seguir só está disponível no nível de privilégio Modo de diagnóstico.

.. Se você estiver executando o ONTAP 9.17.1 e os links de interconexão HA foram desativados, reative-os:
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`

+

NOTE: Se você estiver executando a versão 9.18.1 ou superior, pule a etapa acima e vá para a próxima.

.. Volte a colocar o controlador afetado em funcionamento normal, devolvendo o respetivo armazenamento:
+
`storage failover giveback -ofnode _impaired_node_name_`



. Para sistemas com gerenciador de chaves configurado, selecione o processo de restauração do gerenciador de chaves apropriado.
+
[role="tabbed-block"]
====
.Gerenciador de chaves integrado (OKM)
--
Se OKM for detetado, o sistema exibirá a seguinte mensagem e começará a executar a opção BootMenu 10.

....
key manager is configured.
Entering Bootmenu Option 10...

This option must be used only in disaster recovery procedures. Are you sure? (y or n):
....
.. Digite `Y` no prompt para confirmar que deseja iniciar o processo de recuperação OKM.
.. Digite o seguinte quando solicitado:
+
... A frase-senha
... A frase-senha novamente quando solicitado a confirmar
... Dados de backup para o gerenciador de chaves de bordo
+
.Mostrar exemplo de prompts de senha e dados de backup
[%collapsible]
=====
....
Enter the passphrase for onboard key management:
-----BEGIN PASSPHRASE-----
<passphrase_value>
-----END PASSPHRASE-----
Enter the passphrase again to confirm:
-----BEGIN PASSPHRASE-----
<passphrase_value>
-----END PASSPHRASE-----
Enter the backup data:
-----BEGIN BACKUP-----
<passphrase_value>
-----END ACKUP-----
....
=====


.. Continue a monitorar o processo de recuperação à medida que restaura os arquivos apropriados do nó do parceiro.
+
Quando o processo de recuperação estiver concluído, o nó será reiniciado. As seguintes mensagens indicam uma recuperação bem-sucedida:

+
....
Trying to recover keymanager secrets....
Setting recovery material for the onboard key manager
Recovery secrets set successfully
Trying to delete any existing km_onboard.keydb file.

Successfully recovered keymanager secrets.
....
.. Quando o nó for reiniciado, verifique se a recuperação da Mídia de inicialização foi bem-sucedida, confirmando que o sistema está novamente on-line e operacional.
.. Volte a colocar o controlador afetado em funcionamento normal, devolvendo o respetivo armazenamento:
+
`storage failover giveback -ofnode _impaired_node_name_`

+
... Se os links de interconexão HA foram desativados, reative-os para retomar o retorno automático:
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`



.. Depois que o nó do parceiro estiver totalmente ativo e fornecendo dados, sincronize as chaves OKM no cluster.
+
`security key-manager onboard sync`



--
.Gerenciador de chaves externo (EKM)
--
Se o EKM for detetado, o sistema exibirá a seguinte mensagem e começará a executar a opção BootMenu 11.

....
key manager is configured.
Entering Bootmenu Option 11...
....
.. Dependendo se a chave for restaurada com sucesso, execute uma das seguintes ações:
+
*** Se você ver `kmip2_client: Successfully imported the keys from external key server: xxx.xxx.xxx.xxx:5696` na saída, a configuração do EKM foi restaurada com sucesso.
+
O processo tenta restaurar os arquivos apropriados do nó parceiro e reinicia o nó. Continue para a próxima etapa.

*** Se a chave não for restaurada com sucesso, o sistema irá parar e indicar que não conseguiu restaurar a chave.  As mensagens de erro e aviso são exibidas.  Você deve executar novamente o processo de recuperação:
+
`boot_recovery -partner`

+
.Mostrar exemplo de mensagens de aviso e erro de recuperação de chave
[%collapsible]
=====
....

ERROR: kmip_init: halting this system with encrypted mroot...
WARNING: kmip_init: authentication keys might not be available.
********************************************************
*                 A T T E N T I O N                    *
*                                                      *
*       System cannot connect to key managers.         *
*                                                      *
********************************************************
ERROR: kmip_init: halting this system with encrypted mroot...
.
Terminated

Uptime: 11m32s
System halting...

LOADER-B>
....
=====


.. Quando o nó for reiniciado, verifique se a recuperação da Mídia de inicialização foi bem-sucedida, confirmando que o sistema está novamente on-line e operacional.
.. Volte a colocar o controlador em funcionamento normal, devolvendo o respetivo armazenamento:
+
`storage failover giveback -ofnode _impaired_node_name_`

+
... Se os links de interconexão HA foram desativados, reative-os para retomar o retorno automático:
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`





--
====


. Se a giveback automática foi desativada, reative-a:
+
`storage failover modify -node local auto-giveback-of true`

. Se o AutoSupport estiver ativado, restaure a criação automática de casos:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.O que se segue?
Depois de restaurar a imagem ONTAP e o nó estiver ativo e servindo dados, você precisalink:bootmedia-complete-rma.html["Devolva a peça com falha ao NetApp"] .
