---
permalink: afx-1k/chassis-replace-requirements.html 
sidebar: sidebar 
keywords: afx 1k, replace the chassis 
summary: Antes de substituir o chassi do seu sistema de armazenamento AFX 1K, certifique-se de atender aos requisitos necessários para uma substituição bem-sucedida. Isso inclui verificar se todos os outros componentes do sistema estão funcionando corretamente, verificar se você tem credenciais de administrador local para o ONTAP, o chassi de substituição correto e as ferramentas necessárias. 
---
= Requisitos para substituir o chassi - AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de substituir o chassi do seu sistema de armazenamento AFX 1K, certifique-se de atender aos requisitos necessários para uma substituição bem-sucedida. Isso inclui verificar se todos os outros componentes do sistema estão funcionando corretamente, verificar se você tem credenciais de administrador local para o ONTAP, o chassi de substituição correto e as ferramentas necessárias.

O chassi é o chassi físico que abriga todos os componentes do sistema, como ventiladores, unidade controladora/CPU, NVRAM12, módulo de gerenciamento do sistema, placas de E/S e módulos de bloqueio e PSUs.

Reveja os seguintes requisitos.

* Certifique-se de que todos os outros componentes do sistema estão a funcionar corretamente; caso contrário, contacte http://mysupport.netapp.com/["Suporte à NetApp"^] para obter assistência.
* Obtenha credenciais de administrador local para o ONTAP se você não as tiver.
* Certifique-se de que tem as ferramentas e o equipamento necessários para a substituição.
* Pode utilizar o procedimento de substituição do chassis com todas as versões do ONTAP suportadas pelo seu sistema.
* O procedimento de substituição do chassi foi escrito partindo do pressuposto de que você está movendo o painel, os ventiladores, o módulo do controlador, a NVRAM12, o módulo de gerenciamento do sistema, as placas de E/S e os módulos de obturação e as PSUs para o novo chassi, e que o chassi de substituição é um novo componente da NetApp.


.O que se segue?
Após analisar os requisitos,link:chassis-replace-prepare.html["prepare-se para substituir o chassi"] .
