---
permalink: afx-1k/io-module-overview.html 
sidebar: sidebar 
keywords: afx 1k, replace io module 
summary: O sistema de armazenamento AFX 1K oferece flexibilidade na expansão ou substituição de módulos de E/S para melhorar a conectividade e o desempenho da rede.  Adicionar ou substituir um módulo de E/S é essencial ao atualizar os recursos da rede ou ao lidar com um módulo com falha. 
---
= Visão geral do módulo de E/S de adição e substituição - AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O sistema de armazenamento AFX 1K oferece flexibilidade na expansão ou substituição de módulos de E/S para melhorar a conectividade e o desempenho da rede.  Adicionar ou substituir um módulo de E/S é essencial ao atualizar os recursos da rede ou ao lidar com um módulo com falha.

Você pode substituir um módulo de E/S com falha no seu sistema de armazenamento AFX 1K pelo mesmo tipo de módulo de E/S ou por um tipo diferente de módulo de E/S.  Você também pode adicionar um módulo de E/S a um sistema com slots vazios.

* link:io-module-add.html["Adicione um módulo de e/S."]
+
Adicionar módulos adicionais pode melhorar a redundância, ajudando a garantir que o sistema permaneça operacional mesmo que um módulo falhe.

* link:io-module-replace.html["Substitua um módulo de e/S."]
+
A substituição de um módulo de e/S com falha pode restaurar o sistema ao seu estado de funcionamento ideal.



.Numeração de slots de e/S.
Os slots de E/S no controlador AFX 1K são numerados de 1 a 11, conforme mostrado na ilustração a seguir.

image::../media/drw_a1K_back_slots_labeled_ieops-2162.svg[Numeração de slots em um controlador AFX 1K]
