---
permalink: asa150/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: asa a150, a150, asa, replace, boot, media, image, nondisruptive, disruptive, replacement, fat32, usb 
summary: A mídia de inicialização armazena um conjunto primário e um conjunto secundário de arquivos de imagem de inicialização do sistema que o sistema utiliza ao inicializar. Dependendo da sua configuração de rede, você pode realizar uma substituição sem interrupção ou com interrupção. 
---
= Descrição geral da substituição do suporte de arranque - ASA A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A Mídia de inicialização armazena um conjunto primário e secundário de arquivos do sistema (imagem de inicialização) que o sistema usa quando ele é inicializado. Dependendo da configuração da rede, você pode realizar uma substituição sem interrupções ou disruptiva.

[NOTE]
====
NetApp recomenda fortemente que você habilite o registro de logs no console nos dispositivos que estiver utilizando e execute as seguintes ações ao realizar este procedimento:

* Deixe AutoSupport ativado durante a sua manutenção. Isso permite que o suporte da NetApp receba informações de diagnóstico caso ocorram problemas.
* Habilite o registro de sessão para todas as sessões da CLI. Isso cria um registro completo de todos os comandos e da saída do sistema durante a atividade de manutenção. Para obter orientações sobre como habilitar o registro de sessão, consulte  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Como configurar o PuTTY para obter conectividade ideal com sistemas ONTAP"^].


====
Tem de ter uma unidade flash USB, formatada para FAT32, com a quantidade de armazenamento adequada para guardar o `image_xxx.tgz` ficheiro.

Você também deve copiar o `image_xxx.tgz` arquivo para a unidade flash USB para uso posterior neste procedimento.

* Os métodos sem interrupções e disruptivos para substituir uma Mídia de inicialização exigem que você restaure o `var` sistema de arquivos:
+
** Para substituição sem interrupções, o par de HA deve estar conetado a uma rede para restaurar o `var` sistema de arquivos.
** Para a substituição disruptiva, não é necessário uma ligação de rede para restaurar o `var` sistema de ficheiros, mas o processo requer duas reinicializações.


* Você deve substituir o componente com falha por um componente FRU de substituição que você recebeu de seu provedor.
* É importante que você aplique os comandos nessas etapas no nó correto:
+
** O nó _prejudicado_ é o nó no qual você está realizando a manutenção.
** O nó _Healthy_ é o parceiro de HA do nó prejudicado.



