---
permalink: asa150/overview.html 
sidebar: sidebar 
summary: Especificações principais para o grupo de plataforma ASA150 
---
= Especificações principais para ASA A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A seguir estão especificações selecionadas para o sistema de armazenamento ASA A150 em um único par de alta disponibilidade.  Visite o NetApp Hardware Universe (HWU) para obter as especificações completas deste sistema de armazenamento.



== Especificações principais para ASA A150

* Configuração da plataforma: Par de HA de chassi único ASA A150 UTA2
* Capacidade máxima de matéria-prima: 0,5472 PB
* Memória: 64.0000 GB
* Fator de forma: chassi 2U com 2 controladores HA e 24 slots de unidade
* Versão ONTAP : ONTAP: 9.16.1P2
* Versão mínima do ONTAP : ONTAP 9.13.1 == Máximos de escalonamento
* Tipo: NAS
* Tipo: SAN; Pares HA: 6; Capacidade bruta: 3,3 PB / 2,9 PiB; Memória máxima: 384 GB
* Tipo: Par HA; Capacidade bruta: 0,5 PB / 0,5 PiB; Memória máxima: 64.0000




== E/S



=== E/S integradas

* Protocolo: Ethernet 10 Gbps; Portas: 12
* Protocolo: FC 16 Gbps; Portas: 8
* Protocolo: SAS 12 Gbps; Portas: 4




=== Total de E/S

* Protocolo: Ethernet 10 Gbps; Portas: 12
* Protocolo: FC 16 Gbps; Portas: 8
* Protocolo: SAS 12 Gbps; Portas: 4




=== Portas de gerenciamento

* Protocolo: Ethernet 1 Gbps; Portas: 2
* Protocolo: RS-232 115 Kbps; Portas: 4
* Protocolo: USB 12 Mbps; Portas: 2




== Rede de armazenamento suportada

* FC
* iSCSI
* NVMe/TCP == Especificações do ambiente do sistema Nenhum dado de ambiente disponível.




== Conformidade

* Certificações EMC/EMI: AMCA, FCC, ICES, KC, Marrocos, VCCI
* Certificações de segurança: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificações Segurança/EMC/EMI: EAC, UKRSEPRO
* Certificações Segurança/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normas EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normas de segurança: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




== Alta disponibilidade

* Controlador de gerenciamento de placa base baseado em Ethernet (BMC) e interface de gerenciamento ONTAP
* Controladores redundantes hot-swappable
* Fontes de alimentação redundantes com troca a quente
* Gerenciamento de banda SAS em conexões SAS

