---
permalink: fas50/controller-replace-requirements.html 
sidebar: sidebar 
keywords: fas50, prerequisite, replace the controller module 
summary: Antes de substituir o controlador no seu sistema de armazenamento FAS50, certifique-se de que cumpre os requisitos necessários para uma substituição bem-sucedida. Isso inclui verificar se todos os outros componentes do sistema estão funcionando corretamente, verificar se você tem o controlador de substituição correto e salvar a saída do console do controlador em um arquivo de log de texto. 
---
= Requisitos para substituir o controlador - FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de substituir o controlador no seu sistema de armazenamento FAS50, certifique-se de que cumpre os requisitos necessários para uma substituição bem-sucedida. Isso inclui verificar se todos os outros componentes do sistema estão funcionando corretamente, verificar se você tem o controlador de substituição correto e salvar a saída do console do controlador em um arquivo de log de texto.

Reveja os requisitos e considerações para o procedimento de substituição do controlador.



== Requisitos

* Todas as prateleiras devem estar funcionando corretamente.
* O controlador saudável deve ser capaz de assumir o controlador que está a ser substituído (referido neste procedimento como ""controlador deficiente"").
* Se o sistema estiver em uma configuração do MetroCluster, você deverá revisar a seção https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["Escolher o procedimento de recuperação correto"] para determinar se deve usar esse procedimento.
* Você deve substituir um controlador por um controlador do mesmo tipo de modelo. Você não pode atualizar seu sistema apenas substituindo o controlador.
* Não é possível alterar nenhuma unidade ou compartimentos como parte deste procedimento.
* Você deve sempre capturar a saída do console do controlador para um arquivo de log de texto.
+
A saída do console fornece um Registro do procedimento que você pode usar para solucionar problemas que você pode encontrar durante o processo de substituição.





== Considerações

É importante aplicar os comandos neste procedimento ao controlador correto:

* O controlador _prejudicado_ é o controlador que está sendo substituído.
* O controlador _replacement_ é o novo controlador que está substituindo o controlador prejudicado.
* O controlador _Healthy_ é o controlador sobrevivente.


.O que se segue?
Depois de analisar os requisitos para substituir o controlador afetado, é link:controller-replace-shutdown.html["desligue o controlador desativado"]necessário .
