---
permalink: fas50/io-module-overview.html 
sidebar: sidebar 
keywords: AFF A90, AFF A70, replace io module 
summary: Os sistemas FAS50 oferecem flexibilidade na expansão ou substituição de módulos de e/S para melhorar a conetividade e o desempenho da rede. Adicionar ou substituir um módulo de e/S é essencial ao atualizar recursos de rede ou endereçar um módulo com falha. 
---
= Descrição geral de adicionar e substituir um módulo de e/S - FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os sistemas FAS50 oferecem flexibilidade na expansão ou substituição de módulos de e/S para melhorar a conetividade e o desempenho da rede. Adicionar ou substituir um módulo de e/S é essencial ao atualizar recursos de rede ou endereçar um módulo com falha.

Você pode substituir um módulo de e/S com falha em seu sistema de storage pelo mesmo tipo de módulo de e/S ou por um tipo diferente de módulo de e/S. Você também pode adicionar um módulo de e/S a um sistema de armazenamento com slots disponíveis.

* link:io-module-add.html["Adicione um módulo de e/S."]
+
A adição de módulos de e/S adicionais pode melhorar a redundância, ajudando a garantir que o sistema de storage permaneça operacional mesmo que um módulo de e/S falhe.

* link:io-module-replace.html["Substitua um módulo de e/S."]
+
A substituição de um módulo de e/S com falha pode restaurar o sistema de armazenamento ao seu estado de funcionamento ideal.


