---
permalink: fas50/io-module-overview.html 
sidebar: sidebar 
keywords: fas50, replace io module 
summary: Os sistemas de armazenamento FAS50 oferecem flexibilidade na expansão ou substituição de módulos de E/S para melhorar a conectividade e o desempenho da rede. Adicionar, fazer hot swap ou substituir um módulo de E/S é essencial ao atualizar os recursos da rede ou solucionar um módulo com falha. 
---
= Visão geral da manutenção do módulo de E/S - FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os sistemas de armazenamento FAS50 oferecem flexibilidade na expansão ou substituição de módulos de E/S para melhorar a conectividade e o desempenho da rede. Adicionar, fazer hot swap ou substituir um módulo de E/S é essencial ao atualizar os recursos da rede ou solucionar um módulo com falha.

Você pode substituir um módulo de E/S com defeito no seu sistema de armazenamento pelo mesmo tipo de módulo de E/S ou por um tipo diferente. Você pode fazer hot-swap de um cluster e de um módulo de E/S de alta disponibilidade quando o seu sistema de armazenamento atender a requisitos específicos. Você também pode adicionar um módulo de E/S a um sistema de armazenamento com slots disponíveis.

* link:io-module-add.html["Adicione um módulo de e/S."]
+
A adição de módulos de e/S adicionais pode melhorar a redundância, ajudando a garantir que o sistema de storage permaneça operacional mesmo que um módulo de e/S falhe.

* link:io-module-hotswap-ha-slot4.html["Troca a quente de um cluster e um módulo de E/S HA"]
+
A troca a quente de um cluster com falha e de um módulo de E/S de alta disponibilidade pode restaurar o sistema de armazenamento ao seu estado operacional ideal. A troca a quente é realizada sem a necessidade de assumir manualmente o controlador com defeito.

+
Para usar este procedimento, seu sistema de armazenamento deve estar executando o ONTAP 9.17.1 ou posterior e atender a requisitos específicos do sistema.

* link:io-module-replace.html["Substitua um módulo de e/S."]
+
A substituição de um módulo de e/S com falha pode restaurar o sistema de armazenamento ao seu estado de funcionamento ideal.


