---
permalink: fas9500/chassis_replace_shutdown.html 
sidebar: sidebar 
keywords: aff fas9500, shutdown the controllers 
summary: Para substituir o chassi, você deve desligar os controladores. 
---
= Desligue o controlador desativado - FAS9500
:allow-uri-read: 




== Desligue o controlador desativado - FAS9500

[role="lead"]
Este procedimento destina-se a sistemas com duas configurações de nós. Para obter mais informações sobre o desligamento normal ao fazer manutenção de um cluster, https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/What_is_the_procedure_for_graceful_shutdown_and_power_up_of_a_storage_system_during_scheduled_power_outage["Desligue e ligue o seu sistema de armazenamento de dados - base de dados de Conhecimento da NetApp"] consulte .

.Antes de começar
* Certifique-se de que tem as permissões e credenciais necessárias:
+
** Credenciais de administrador local para o ONTAP.
** Acessibilidade do BMC para cada controlador.


* Certifique-se de que tem as ferramentas e o equipamento necessários para a substituição.


.Passos
. Faça login no cluster através de SSH ou faça login de qualquer nó no cluster usando um cabo de console local e um laptop/console.
. Impedir que todos os clientes/hosts acessem dados no sistema NetApp.
. Suspender trabalhos de cópia de segurança externos.
. Se o AutoSupport estiver ativado, suprimir a criação de casos e indicar quanto tempo espera que o sistema esteja offline:
+
`system node autosupport invoke -node * -type all -message "MAINT=2h Replace chassis"`

. Identifique o endereço SP/BMC de todos os nós de cluster:
+
`system service-processor show -node * -fields address`

. Saia do shell do cluster:
+
`exit`

. Faça login no SP/BMC de cada controlador usando o endereço IP identificado na etapa anterior:
+
** Se você fizer login no BMC via SSH, conecte-se usando o endereço SP/BMC (por exemplo, `ssh admin@<SP/BMC_address>`), depois insira o comando `system console` e autentique-se.
** Se você estiver usando um console local ou um laptop conectado diretamente ao controlador, faça login usando as mesmas credenciais de administrador do cluster.


. Parar os dois nós localizados no chassi com deficiência:
+
`system node halt -node <node1>,<node2> -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true`

+

NOTE: Para clusters que usam o SnapMirror síncrono operando no modo StrictSync: `system node halt -node <node1>,<node2>  -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true -ignore-strict-sync-warnings true`

. Digite *y* para cada controlador no cluster quando você vir:
+
`Warning: Are you sure you want to halt node _<node_name>_? {y|n}:`

. Aguarde que cada controlador pare e exiba o prompt Loader.

