---
permalink: fas9500/controller_replace_complete_system_restoration_rma.html 
sidebar: sidebar 
keywords:  
summary: 'Para concluir o procedimento de substituição e restaurar o sistema para o funcionamento total, tem de voltar a efetuar a recuperação do armazenamento, restaurar a configuração da encriptação de armazenamento NetApp (se necessário) e instalar licenças para o novo controlador.' 
---
= Restauração completa do sistema - FAS9500
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para concluir o procedimento de substituição e restaurar o sistema para o funcionamento total, tem de voltar a efetuar a recuperação do armazenamento, restaurar a configuração da encriptação de armazenamento NetApp (se necessário) e instalar licenças para o novo controlador. Você deve concluir uma série de tarefas antes de restaurar o sistema para a operação completa.



== Passo 1: Instale licenças para o nó de substituição no ONTAP

Você deve instalar novas licenças para o nó _replacement_ se o nó prejudicado estiver usando recursos do ONTAP que exigem uma licença padrão (node-locked). Para recursos com licenças padrão, cada nó no cluster deve ter sua própria chave para o recurso.

.Sobre esta tarefa
Até instalar chaves de licença, os recursos que exigem licenças padrão continuam disponíveis para o nó _replacement_. No entanto, se o nó prejudicado for o único nó no cluster com uma licença para o recurso, nenhuma alteração de configuração será permitida.

Além disso, o uso de recursos não licenciados no nó pode colocá-lo fora de conformidade com o seu contrato de licença, então você deve instalar a chave de licença de substituição ou chaves no nó _replacement_ o mais rápido possível.

As chaves de licença devem estar no formato de 28 carateres.

Você tem um período de carência de 90 dias para instalar as chaves de licença. Após o período de carência, todas as licenças antigas são invalidadas. Depois que uma chave de licença válida é instalada, você tem 24 horas para instalar todas as chaves antes que o período de carência termine.

Se o nó estiver em uma configuração do MetroCluster e todos os nós de um local tiverem sido substituídos, as chaves de licença devem ser instaladas no nó ou nós _replacement_ antes do switchback.

.Passos
. Se você precisar de novas chaves de licença, obtenha chaves de licença de substituição na https://mysupport.netapp.com/site/global/dashboard["Site de suporte da NetApp"] seção meu suporte em licenças de software.
+

NOTE: As novas chaves de licença que você precisa são geradas automaticamente e enviadas para o endereço de e-mail em arquivo. Se você não receber o e-mail com as chaves de licença no prazo de 30 dias, entre em Contato com o suporte técnico.

. Instale cada chave de licença: `+system license add -license-code license-key, license-key...+`
. Remova as licenças antigas, se desejar:
+
.. Verifique se há licenças não utilizadas: `license clean-up -unused -simulate`
.. Se a lista estiver correta, remova as licenças não utilizadas: `license clean-up -unused`






== Passo 2: Verifique LIFs e registrando o número de série

Antes de retornar o nó _replacement_ ao serviço, você deve verificar se os LIFs estão em suas portas iniciais e Registrar o número de série do nó _replacement_ se o AutoSupport estiver ativado e redefinir a giveback automática.

.Passos
. Verifique se as interfaces lógicas estão relatando para o servidor doméstico e as portas: `network interface show -is-home false`
+
Se algum LIFs estiver listado como false, reverta-os para suas portas iniciais: `network interface revert -vserver * -lif *`

. Registre o número de série do sistema com o suporte da NetApp.
+
** Se o AutoSupport estiver ativado, envie uma mensagem AutoSupport para Registrar o número de série.
** Se o AutoSupport não estiver ativado, ligue https://mysupport.netapp.com["Suporte à NetApp"] para registar o número de série.


. Se uma janela de manutenção do AutoSupport foi acionada, encerre-a usando o `system node autosupport invoke -node * -type all -message MAINT=END` comando.
. Se a giveback automática foi desativada, reative-a: `storage failover modify -node local -auto-giveback true`




== Passo 3: Devolva a peça com falha ao NetApp

Devolva a peça com falha ao NetApp, conforme descrito nas instruções de RMA fornecidas com o kit. Consulte a https://mysupport.netapp.com/site/info/rma["Devolução de peças e substituições"] página para obter mais informações.
