---
permalink: fas9500/maintain-overview.html 
sidebar: sidebar 
keywords: FAS9500 maintenance, maintenance, repairing FAS9500, repairing aff FAS9500, replace FAS9500 components, replace FAS9500 components 
summary: Manutenção do hardware FAS9500 
---
= Mantenha o hardware FAS9500
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Faça a manutenção do hardware do seu sistema de armazenamento FAS9500 para garantir confiabilidade a longo prazo e desempenho ideal. Realize tarefas de manutenção regulares, como a substituição de componentes defeituosos, pois isso ajuda a evitar tempo de inatividade e perda de dados.

Os procedimentos de manutenção pressupõem que o sistema de armazenamento FAS9500 já tenha sido implantado como um nó de armazenamento no ambiente ONTAP .



== Componentes do sistema

Para o sistema de armazenamento FAS9500, pode executar procedimentos de manutenção nos seguintes componentes.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["Mídia de inicialização - recuperação automatizada"]
 a| 
A mídia de inicialização armazena um conjunto primário e secundário de arquivos de imagem ONTAP que o sistema de armazenamento usa para inicializar.  Durante a recuperação automatizada, o sistema recupera a imagem de inicialização do nó parceiro e executa automaticamente a opção de menu de inicialização apropriada para instalar a imagem na mídia de inicialização de substituição. O processo automatizado de recuperação da mídia de inicialização é compatível apenas com o ONTAP 9.17.1 e versões posteriores. Se o seu sistema de armazenamento estiver executando uma versão anterior do ONTAP, use o link:bootmedia-replace-workflow.html["procedimento de recuperação de inicialização manual"] .



 a| 
link:bootmedia-replace-workflow.html["Mídia de inicialização - recuperação manual"]
 a| 
A mídia de inicialização armazena um conjunto primário e secundário de arquivos de imagem ONTAP que o sistema de armazenamento usa para inicializar. Durante a recuperação manual, você inicializa o sistema de armazenamento a partir de uma unidade USB e restaura manualmente a imagem e a configuração do sistema de arquivos.  Se o seu sistema de armazenamento estiver executando o ONTAP 9.17.1 e posterior, use olink:bootmedia-replace-workflow-bmr.html["procedimento automatizado de recuperação de inicialização"] .



 a| 
link:caching_module_hot_swap.html["Módulo de armazenamento em cache"]
 a| 
Você deve substituir o módulo de cache do controlador quando o sistema Registrar uma única mensagem AutoSupport (ASUP) informando que o módulo ficou offline.



 a| 
link:chassis_replace_overview.html["Chassis"]
 a| 
O chassi é o gabinete físico que abriga todos os componentes do controlador, como a unidade controladora/CPU, fonte de alimentação e e/S.



 a| 
link:controller_replace_overview.html["Controlador"]
 a| 
Um controlador consiste em uma placa, firmware e software. Controla as unidades e implementa as funções do ONTAP.



 a| 
link:dimm_replace.html["DIMM"]
 a| 
Você deve substituir um DIMM (módulo de memória dual in-line) quando houver uma incompatibilidade de memória ou se tiver um DIMM com falha.



 a| 
link:dcpm-nvram11-battery-replace.html["DCPM"]
 a| 
O DCPM (módulo de alimentação do controlador de destage) contém a bateria de NVRAM11 V.



 a| 
link:fan_swap_out.html["Ventoinha"]
 a| 
A ventoinha arrefece o controlador.



 a| 
link:pci_cards_and_risers_replace.html["Módulo de e/S."]
 a| 
O módulo I/o (módulo de entrada/saída) é um componente de hardware que atua como intermediário entre o controlador e vários dispositivos ou sistemas que precisam trocar dados com o controlador.



 a| 
link:led_module_replace.html["LED USB"]
 a| 
O módulo LED USB fornece conetividade às portas da consola e ao estado do sistema.



 a| 
link:nvram_module_or_nvram_dimm_replacement.html["NVRAM"]
 a| 
O módulo NVRAM (memória de acesso aleatório não volátil) permite que o controlador retenha dados durante ciclos de energia ou reinicializações do sistema, enquanto o NVRAM DIMM mantém as configurações da NVRAM .



 a| 
link:power_supply_swap_out.html["Fonte de alimentação"]
 a| 
Uma fonte de alimentação fornece uma fonte de alimentação redundante em um controlador.



 a| 
link:rtc_battery_replace.html["Bateria de relógio em tempo real"]
 a| 
Uma bateria de relógio em tempo real preserva as informações de data e hora do sistema se a energia estiver desligada.

|===