---
permalink: fas2800/maintain-overview.html 
sidebar: sidebar 
keywords: fas2800 maintenance, maintenance, repairing, repairing fas2800, replace fas2800 components, replace fas2800 components 
summary: Mantenha o hardware FAS2820 
---
= Mantenha o hardware FAS2820
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Faça a manutenção do hardware do seu sistema de armazenamento FAS2820 para garantir confiabilidade a longo prazo e desempenho ideal. Realize tarefas de manutenção regulares, como a substituição de componentes defeituosos, pois isso ajuda a evitar tempo de inatividade e perda de dados.

Os procedimentos de manutenção pressupõem que o sistema de armazenamento FAS2820 já tenha sido implantado como um nó de armazenamento no ambiente ONTAP .



== Componentes do sistema

Para o sistema de armazenamento FAS2820, pode executar procedimentos de manutenção nos seguintes componentes.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["Mídia de inicialização - recuperação automatizada"]
 a| 
A mídia de inicialização armazena um conjunto primário e secundário de arquivos de imagem ONTAP que o sistema de armazenamento usa para inicializar.  Durante a recuperação automatizada, o sistema recupera a imagem de inicialização do nó parceiro e executa automaticamente a opção de menu de inicialização apropriada para instalar a imagem na mídia de inicialização de substituição. O processo automatizado de recuperação da mídia de inicialização é compatível apenas com o ONTAP 9.17.1 e versões posteriores. Se o seu sistema de armazenamento estiver executando uma versão anterior do ONTAP, use o link:bootmedia-replace-workflow.html["procedimento de recuperação de inicialização manual"] .



 a| 
link:bootmedia-replace-workflow.html["Mídia de inicialização - recuperação manual"]
 a| 
A mídia de inicialização armazena um conjunto primário e secundário de arquivos de imagem ONTAP que o sistema de armazenamento usa para inicializar. Durante a recuperação manual, você inicializa o sistema de armazenamento a partir de uma unidade USB e restaura manualmente a imagem e a configuração do sistema de arquivos.  Se o seu sistema de armazenamento estiver executando o ONTAP 9.17.1 e posterior, use olink:bootmedia-replace-workflow-bmr.html["procedimento automatizado de recuperação de inicialização"] .



 a| 
link:caching-module-replace.html["Módulo de armazenamento em cache"]
 a| 
Você deve substituir o módulo de cache do controlador quando o sistema Registrar uma única mensagem AutoSupport (ASUP) informando que o módulo ficou offline.



 a| 
link:chassis-replace-overview.html["Chassis"]
 a| 
O chassi é o gabinete físico que abriga todos os componentes do controlador, como a unidade controladora/CPU, fonte de alimentação e e/S.



 a| 
link:controller-replace-overview.html["Controlador"]
 a| 
Um controlador consiste em uma placa, firmware e software. Controla as unidades e implementa as funções do ONTAP.



 a| 
link:dimm-replace.html["DIMM"]
 a| 
Você deve substituir um DIMM (módulo de memória dual in-line) quando houver uma incompatibilidade de memória ou se tiver um DIMM com falha.



 a| 
link:drive-replace.html["Condução"]
 a| 
Uma unidade é um dispositivo que fornece a Mídia de armazenamento físico para dados.



 a| 
link:nvmem-nvram-battery-replace.html["Bateria NVMEM"]
 a| 
Uma bateria é incluída com o controlador e preserva os dados em cache se a energia CA falhar.



 a| 
link:pci-cards-and-risers-replace.html["Placa mezzanine"]
 a| 
Uma placa Mezzanine é uma placa de expansão projetada para ser inserida em um slot especializado na placa-mãe e contém as placas de E/S.



 a| 
link:power-supply-swap-out.html["Fonte de alimentação"]
 a| 
Uma fonte de alimentação fornece uma fonte de alimentação redundante em um controlador.



 a| 
link:rtc-battery-replace.html["Bateria de relógio em tempo real"]
 a| 
Uma bateria de relógio em tempo real preserva as informações de data e hora do sistema se a energia estiver desligada.

|===