---
permalink: asa250/overview.html 
sidebar: sidebar 
keywords: ASA A250 specifications, ASA A250 specs, NetApp ASA A250, ASA A250 hardware 
summary: Especificações principais para o sistema de armazenamento ASA A250 
---
= Especificações principais para ASA A250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A seguir estão algumas especificações selecionadas para o ASA A250.  Visita https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) para uma lista completa das especificações ASA A250 .  Esta página reflete um único par de alta disponibilidade.



=== Especificações principais para ASA A250

Configuração da plataforma: ASA A250 100V Chassis único HA Pair

Capacidade máxima de matéria-prima: 0,7344 PB

Memória: 128.0000 GB

Fator de forma: chassi 2U com 2 controladores HA e 24 slots de unidade

Versão ONTAP : b_startONTAP: 9.16.1P2b_end

Slots de expansão PCIe: 4

Versão mínima do ONTAP : ONTAP 9.13.1



=== Máximos de Escalabilidade

|===


| Tipo | Pares HA | Capacidade bruta | Memória Máxima 


| NAS |  |  |  


| SAN | 6 | 4,4 PB / 3,9 PiB | 768 GB 


| Par HA |  | 0,7 PB / 0,7 PiB | 128,0000 
|===


=== IO



==== IO integrado

|===


| Protocolo | Portos 


| Ethernet 25 Gbps | 4 


| Ethernet 10 Gbps | 4 
|===


==== Total de IO

|===


| Protocolo | Portos 


| Ethernet 100 Gbps | 4 


| Ethernet 25 Gbps | 12 


| Ethernet 10 Gbps | 4 


| FC 32 Gbps | 8 


| NVMe/FC 32 Gbps | 8 


|  | 0 
|===


==== Portas de Gestão

|===


| Protocolo | Portos 


| Ethernet 1 Gbps | 2 


| RS-232 115 Kbps | 4 


| USB 12 Mbps | 4 
|===


=== Rede de armazenamento suportada

FC; iSCSI; NVMe/FC; NVMe/TCP;



=== Especificações do ambiente do sistema

Não há dados ambientais disponíveis.



=== Conformidade

* Certificações EMC/EMI: AMCA, FCC, ICES, KC, Marrocos, VCCI
* Certificações de segurança: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificações Segurança/EMC/EMI: EAC, UKRSEPRO
* Certificações Segurança/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normas EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normas de segurança: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilidade

Controlador de gerenciamento de placa base baseado em Ethernet (BMC) e interface de gerenciamento ONTAP ; Controladores redundantes de troca a quente; Fontes de alimentação redundantes de troca a quente; Gerenciamento SAS em banda por meio de conexões SAS para prateleiras externas;
