---
permalink: asa250/bootmedia-shutdown.html 
sidebar: sidebar 
keywords: asa a250, shutdown 
summary: Depois de concluir as tarefas NVE ou NSE, você precisa concluir o desligamento do controlador desativado. 
---
= Desligue o controlador - ASA A250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Encerre ou assuma o controlador afetado utilizando o procedimento adequado para a sua configuração.



== Opção 1: A maioria dos sistemas

Depois de concluir as tarefas NVE ou NSE, você precisa concluir o desligamento do controlador desativado.

.Passos
. Leve o controlador prejudicado para o prompt Loader:
+
[cols="1,2"]
|===
| Se o controlador afetado apresentar... | Então... 


 a| 
O prompt Loader
 a| 
Vá para Remover módulo do controlador.



 a| 
`Waiting for giveback...`
 a| 
Pressione Ctrl-C e responda `y` quando solicitado.



 a| 
Prompt do sistema ou prompt de senha (digite a senha do sistema)
 a| 
Assuma ou interrompa o controlador prejudicado do controlador saudável: `storage failover takeover -ofnode impaired_node_name`

Quando o controlador prejudicado mostrar aguardando a giveback..., pressione Ctrl-C e responda `y`.

|===
. No prompt Loader, digite: `printenv` Para capturar todas as variáveis ambientais de inicialização. Salve a saída no arquivo de log.
+

NOTE: Este comando pode não funcionar se o dispositivo de inicialização estiver corrompido ou não funcional.





== Opção 2: Sistemas em um MetroCluster

Depois de concluir as tarefas NVE ou NSE, você precisa concluir o desligamento do controlador desativado.


NOTE: Não use este procedimento se o sistema estiver em uma configuração de MetroCluster de dois nós.

Para encerrar o controlador com deficiência, você deve determinar o status do controlador e, se necessário, assumir o controlador para que o controlador saudável continue fornecendo dados do armazenamento do controlador com deficiência.

* Se você tiver um cluster com mais de dois nós, ele deverá estar no quórum. Se o cluster não estiver em quórum ou se um controlador íntegro exibir false para qualificação e integridade, você deverá corrigir o problema antes de encerrar o controlador prejudicado; link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Sincronize um nó com o cluster"^]consulte .
* Se você tiver uma configuração MetroCluster, você deve ter confirmado que o estado de configuração do MetroCluster está configurado e que os nós estão em um estado ativado e normal (`metrocluster node show`).


.Passos
. Se o AutoSupport estiver ativado, suprimir a criação automática de casos invocando uma mensagem AutoSupport: `system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
A seguinte mensagem AutoSupport suprime a criação automática de casos por duas horas: `cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. Desative a giveback automática a partir da consola do controlador saudável: `storage failover modify –node local -auto-giveback false`
. Leve o controlador prejudicado para o prompt Loader:
+
[cols="1,2"]
|===
| Se o controlador afetado estiver a apresentar... | Então... 


 a| 
O prompt Loader
 a| 
Vá para a próxima etapa.



 a| 
A aguardar pela giveback...
 a| 
Pressione Ctrl-C e responda `y` quando solicitado.



 a| 
Prompt do sistema ou prompt de senha (digite a senha do sistema)
 a| 
Assuma ou interrompa o controlador prejudicado do controlador saudável: `storage failover takeover -ofnode _impaired_node_name_`

Quando o controlador prejudicado mostrar aguardando a giveback..., pressione Ctrl-C e responda `y`.

|===


.O que se segue?
Depois de desligar o controlador, é necessário link:bootmedia-replace.html["substitua o suporte de arranque"].
