---
permalink: c30-60/bootmedia-encryption-preshutdown-checks.html 
sidebar: sidebar 
keywords: aff c30, aff c60, pre-shutdown checks for onboard encryption keys 
summary: Antes de desligar o controlador com deficiência e verificar o estado das chaves de encriptação integradas, tem de verificar o estado do controlador com deficiência, desativar a giveback automática e verificar a versão do ONTAP em execução. 
---
= Verifique as chaves de criptografia integradas - AFF C30 e AFF C60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== Passo 1: Verifique se a sua versão do ONTAP suporta encriptação de volume NetApp

Verifique se sua versão do ONTAP suporta criptografia de volume NetApp (NVE). Esta informação é crucial para transferir a imagem ONTAP correta.

. Determine se sua versão do ONTAP suporta criptografia executando o seguinte comando:
+
`version -v`

+
Se a saída incluir `1Ono-DARE`, o NVE não é suportado na versão do cluster.

. Dependendo se o NVE é compatível com o seu sistema, execute uma das seguintes ações:
+
** Se for suportado NVE, transfira a imagem ONTAP com encriptação de volume NetApp.
** Se a NVE não for suportada, transfira a imagem ONTAP *sem* encriptação de volume NetApp.






== Passo 2: Determine se é seguro desligar o controlador

Para desligar um controlador com segurança, primeiro identifique se o External Key Manager (EKM) ou o Onboard Key Manager (OKM) está ativo. Em seguida, verifique o gerenciador de chaves em uso, exiba as informações de chave apropriadas e tome medidas com base no status das chaves de autenticação.

. Determine qual gerenciador de chaves está habilitado em seu sistema:
+
[cols="1a,2a"]
|===
| Versão de ONTAP | Execute este comando 


 a| 
ONTAP 9.14,1 ou posterior
 a| 
`security key-manager keystore show`

** Se EKM estiver ativado, `EKM` é listado na saída do comando.
** Se OKM estiver ativado, `OKM` o será listado na saída do comando.
** Se nenhum gerenciador de chaves estiver habilitado, `No key manager keystores configured` o será listado na saída do comando.




 a| 
ONTAP 9.13,1 ou anterior
 a| 
`security key-manager show-key-store`

** Se EKM estiver ativado, `external` é listado na saída do comando.
** Se OKM estiver ativado, `onboard` o será listado na saída do comando.
** Se nenhum gerenciador de chaves estiver habilitado, `No key managers configured` o será listado na saída do comando.


|===
. Dependendo se um gerenciador de chaves está configurado no sistema, selecione uma das opções a seguir.
+
[role="tabbed-block"]
====
.Nenhum gerenciador de chaves configurado
--
Pode desligar o controlador com segurança. Vá para link:bootmedia-shutdown.html["desligue o controlador desativado"].

--
.Gestor de chaves externo ou integrado configurado
--
.. Digite o seguinte comando de consulta para exibir o status das chaves de autenticação no gerenciador de chaves.
+
`security key-manager key query`

.. Verifique a saída para o valor na `Restored` coluna do seu gerenciador de chaves.
+
Esta coluna indica se as chaves de autenticação do seu gerenciador de chaves (EKM ou OKM) foram restauradas com êxito.



--
====


. Dependendo se o sistema estiver usando o Gerenciador de chaves Externo ou o Gerenciador de chaves integrado, selecione uma das opções a seguir.
+
[role="tabbed-block"]
====
.Gerenciador de chaves externo
--
Dependendo do valor de saída exibido na `Restored` coluna, siga as etapas apropriadas.

[cols="1a,2a"]
|===
| Valor de saída `Restored` na coluna | Siga estes passos... 


 a| 
`true`
 a| 
Pode desligar o controlador com segurança. Vá para link:bootmedia-shutdown.html["desligue o controlador desativado"].



 a| 
Qualquer outra coisa que não `true`
 a| 
.. Restaure as chaves de autenticação de gerenciamento de chaves externas para todos os nós no cluster usando o seguinte comando:
+
`security key-manager external restore`

+
Se o comando falhar, contactar http://mysupport.netapp.com/["Suporte à NetApp"^].

.. Verifique se a `Restored` coluna é exibida `true` para todas as chaves de autenticação inserindo o  `security key-manager key query` comando.
+
Se todas as chaves de autenticação forem `true`, pode desligar o controlador com segurança. Vá para link:bootmedia-shutdown.html["desligue o controlador desativado"].



|===
--
.Gerenciador de chaves integrado
--
Dependendo do valor de saída exibido na `Restored` coluna, siga as etapas apropriadas.

[cols="1a,2a"]
|===
| Valor de saída `Restored` na coluna | Siga estes passos... 


 a| 
`true`
 a| 
Faça backup manual das informações OKM.

.. Vá para o modo avançado entrando `set -priv advanced` e, em seguida, entre `Y` quando solicitado.
.. Digite o seguinte comando para exibir as informações de gerenciamento de chaves:
+
`security key-manager onboard show-backup`

.. Copie o conteúdo das informações de backup para um arquivo separado ou seu arquivo de log.
+
Você vai precisar dele em cenários de desastre onde você pode precisar recuperar manualmente OKM.

.. Pode desligar o controlador com segurança. Vá para link:bootmedia-shutdown.html["desligue o controlador desativado"].




 a| 
Qualquer outra coisa que não `true`
 a| 
.. Digite o comando Onboard security key-manager sync:
+
`security key-manager onboard sync`

.. Digite a senha alfanumérica de gerenciamento de chaves integradas de 32 carateres quando solicitado.
+
Se a frase-passe não puder ser fornecida, http://mysupport.netapp.com/["Suporte à NetApp"^] contacte .

.. Verifique se a `Restored` coluna exibe `true` todas as chaves de autenticação:
+
`security key-manager key query`

.. Verifique se o `Key Manager` tipo é exibido `onboard` e, em seguida, faça backup manual das informações OKM.
.. Digite o comando para exibir as informações de backup de gerenciamento de chaves:
+
`security key-manager onboard show-backup`

.. Copie o conteúdo das informações de backup para um arquivo separado ou seu arquivo de log.
+
Você vai precisar dele em cenários de desastre onde você pode precisar recuperar manualmente OKM.

.. Pode desligar o controlador com segurança. Vá para link:bootmedia-shutdown.html["desligue o controlador desativado"].


|===
--
====

