---
permalink: c30-60/install-hardware.html 
sidebar: sidebar 
keywords: aff c30, aff c60, install hardware, telco rack 
summary: Instale seu sistema de armazenamento em gabinete ou rack de telecomunicações. 
---
= Instale o hardware - AFF C30 e AFF C60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de se preparar para instalar o sistema de storage AFF C30 ou AFF C60, instale o hardware do sistema de storage. Primeiro, instale os kits de trilho. Em seguida, instale e proteja seu sistema de armazenamento em um gabinete ou rack de telecomunicações.

Ignore esta etapa se o sistema de armazenamento tiver entrado em um gabinete.

.Antes de começar
* Certifique-se de que tem as instruções fornecidas com o kit de calha.
* Esteja ciente dos problemas de segurança associados ao peso do sistema de armazenamento e da prateleira.
* Entenda que o fluxo de ar através do sistema de armazenamento entra pela frente onde a tampa frontal ou as tampas da extremidade estão instaladas e esgota a parte traseira onde as portas estão localizadas.


.Passos
. Instale os kits de trilhos para o seu sistema de armazenamento e prateleiras, conforme necessário, seguindo as instruções incluídas nos kits.
. Instale e proteja seu sistema de armazenamento no gabinete ou rack de telecomunicações:
+
.. Posicione o sistema de armazenamento nos trilhos no meio do gabinete ou rack de telecomunicações e, em seguida, apoie o sistema de armazenamento a partir da parte inferior e deslize-o para o lugar.
.. Fixe o sistema de armazenamento ao gabinete ou rack de telecomunicações usando os parafusos de montagem incluídos.


. Fixe o painel frontal à parte frontal do sistema de armazenamento.
. Instale e fixe a gaveta conforme necessário.
+
.. Posicione a parte de trás da prateleira sobre os trilhos e, em seguida, apoie a prateleira a partir da parte inferior e deslize-a para o gabinete ou rack de telecomunicações.
+
Se você estiver instalando várias gavetas, coloque a primeira gaveta diretamente acima das controladoras. Coloque a segunda gaveta diretamente sob as controladoras. Repita este padrão para quaisquer prateleiras adicionais.

.. Fixe a prateleira ao gabinete ou rack de telecomunicações usando os parafusos de montagem incluídos.
+
.O que se segue?
Depois de instalar o hardware para o seu sistema de storage, link:install-cable.html["faça o cabo do material de fixação"]você .




