---
permalink: c30-60/overview.html 
sidebar: sidebar 
keywords: AFF C30 C60 specifications, AFF C30 C60 specs, AFF C30 C60 capacity, AFF C30 C60 memory, AFF C30 C60 I/O, AFF C30 C60 compliance 
summary: Especificações principais para o grupo de plataformas C30-60 
---
= Especificações principais para o grupo de plataformas C30-60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A seguir estão especificações selecionadas para o grupo de plataformas C30-60.  Visita https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) para uma lista completa de especificações.  Esta página reflete um único par de alta disponibilidade.



== AFF C60



=== Especificações principais do AFF C60

Configuração da plataforma: Par de HA de chassi único AFF C60

Capacidade bruta máxima: 7,3680 PB

Memória: 128.0000 GB

Fator de forma: chassi 2U com 2 controladores HA e 24 slots de unidade

Versão ONTAP : b_startONTAP: 9.16.1P2b_end

Slots de expansão PCIe: 8

Versão mínima do ONTAP : ONTAP 9.16.1RC1



=== Máximos de Escalabilidade

|===


| Tipo | Pares HA | Capacidade bruta | Memória Máxima 


| NAS | 4 | 29,5 PB / 26,2 PiB | 512 GB 


| SAN | 4 | 29,5 PB / 26,2 PiB | 512 GB 


| Par HA |  | 7,4 PB / 6,5 PiB | 128,0000 
|===


=== IO



==== IO integrado

Não há dados de E/S a bordo.



==== Total de IO

|===


| Protocolo | Portos 


| Ethernet 100 Gbps | 16 


| Ethernet 25 Gbps | 24 


| Ethernet 10 Gbps | 24 


| FC 64 Gbps | 24 


| NVMe/FC 64 Gbps | 24 


|  | 0 
|===


==== Portas de Gestão

|===


| Protocolo | Portos 


| Ethernet 1 Gbps | 2 


| RS-232 115 Kbps | 4 


| USB 600 Mbps | 2 
|===


=== Rede de armazenamento suportada

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NVMe/FC; NVMe/TCP; S3; S3 com NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Especificações do ambiente do sistema

* Potência típica: 2892 BTU/h
* Pior cenário de potência: 4445 BTU/h
* Peso: 60,7 lb 27,5 kg
* Altura: 2U
* Largura: 19" (44,7 cm), compatível com o padrão de rack IEC.
* Profundidade:
* Temperatura/Altitude/Umidade de operação: 10°C a 35°C (50°F a 95°F) em altitudes de até 3048 m (10000 pés); umidade relativa de 8% a 80%, sem condensação.
* Temperatura/Umidade fora de operação: -40 °C a 70 °C (-40 °F a 158 °F) até 12.192 m (40.000 pés), 10% a 95% de umidade relativa, sem condensação, na embalagem original.
* Ruído acústico: Potência sonora declarada (LwAd): 8,0; Pressão sonora (LpAm) (posições de observador): 70,5 dB




=== Conformidade

* Certificações EMC/EMI: AMCA, FCC, ICES, KC, Marrocos, VCCI
* Certificações de segurança: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificações Segurança/EMC/EMI: EAC, UKRSEPRO
* Certificações Segurança/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normas EMC/EMI: BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normas de segurança: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilidade

Controlador de gerenciamento de placa base baseado em Ethernet (BMC) e interface de gerenciamento ONTAP ; Controladores redundantes de troca a quente; Fontes de alimentação redundantes de troca a quente;



== AFF C30



=== Especificações principais do AFF C30

Configuração da plataforma: Par de HA de chassi único AFF C30

Capacidade Máxima de Bruto: 2,2104 PB

Memória: 128.0000 GB

Fator de forma: chassi 2U com 2 controladores HA e 24 slots de unidade

Versão ONTAP : b_startONTAP: 9.16.1P2b_end

Slots de expansão PCIe: 8

Versão mínima do ONTAP : ONTAP 9.16.1RC1



=== Máximos de Escalabilidade

|===


| Tipo | Pares HA | Capacidade bruta | Memória Máxima 


| NAS | 4 | 8,8 PB / 7,9 PiB | 512 GB 


| SAN | 4 | 8,8 PB / 7,9 PiB | 512 GB 


| Par HA |  | 2,2 PB / 2,0 PiB | 128,0000 
|===


=== IO



==== IO integrado

Não há dados de E/S a bordo.



==== Total de IO

|===


| Protocolo | Portos 


| Ethernet 100 Gbps | 16 


| Ethernet 25 Gbps | 24 


| Ethernet 10 Gbps | 24 


| FC 64 Gbps | 24 


| NVMe/FC 64 Gbps | 24 


|  | 0 
|===


==== Portas de Gestão

|===


| Protocolo | Portos 


| Ethernet 1 Gbps | 2 


| RS-232 115 Kbps | 4 


| USB 600 Mbps | 2 
|===


=== Rede de armazenamento suportada

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NVMe/FC; NVMe/TCP; S3; S3 com NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Especificações do ambiente do sistema

* Potência típica: 2892 BTU/h
* Pior cenário de potência: 4445 BTU/h
* Peso: 60,7 lb 27,5 kg
* Altura: 2U
* Largura: 19" (44,7 cm), compatível com o padrão de rack IEC.
* Profundidade:
* Temperatura/Altitude/Umidade de operação: 10°C a 35°C (50°F a 95°F) em altitudes de até 3048 m (10000 pés); umidade relativa de 8% a 80%, sem condensação.
* Temperatura/Umidade fora de operação: -40 °C a 70 °C (-40 °F a 158 °F) até 12.192 m (40.000 pés), 10% a 95% de umidade relativa, sem condensação, na embalagem original.
* Ruído acústico: Potência sonora declarada (LwAd): 8,0; Pressão sonora (LpAm) (posições de observador): 70,5 dB




=== Conformidade

* Certificações EMC/EMI: AMCA, FCC, ICES, KC, Marrocos, VCCI
* Certificações de segurança: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificações Segurança/EMC/EMI: EAC, UKRSEPRO
* Certificações Segurança/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normas EMC/EMI: BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normas de segurança: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilidade

Controlador de gerenciamento de placa base baseado em Ethernet (BMC) e interface de gerenciamento ONTAP ; Controladores redundantes de troca a quente; Fontes de alimentação redundantes de troca a quente;
