---
permalink: a20-30-50/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: aff a20, aff a30, aff a50, replace the boot media 
summary: Antes de substituir o suporte de arranque no sistema AFF A20, AFF A30 ou AFF A50, certifique-se de que cumpre os requisitos necessários para uma substituição bem-sucedida. Isso inclui garantir que você tenha uma unidade flash USB com a quantidade adequada de armazenamento e verificar se você tem o dispositivo de inicialização de substituição correto. 
---
= Requisitos para substituir o suporte de arranque - AFF A20, AFF A30 e AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de substituir o suporte de arranque no sistema AFF A20, AFF A30 ou AFF A50, certifique-se de que cumpre os requisitos necessários para uma substituição bem-sucedida. Isso inclui garantir que você tenha uma unidade flash USB com a quantidade adequada de armazenamento e verificar se você tem o dispositivo de inicialização de substituição correto.

Antes de substituir a Mídia de inicialização, verifique os seguintes requisitos e considerações.



== Requisitos

* Tem de ter uma unidade flash USB, formatada para FAT32, com a quantidade de armazenamento adequada para manter o `image_xxx.tgz`.
* Você deve copiar o `image_xxx.tgz` arquivo para a unidade flash USB para uso posterior neste procedimento.
* Você deve substituir o componente com falha por um componente FRU de substituição da mesma capacidade que recebeu do seu provedor.




== Considerações

* É importante que você aplique os comandos nestas etapas no controlador correto:
+
** O controlador _prejudicado_ é o controlador no qual você está realizando a manutenção.
** O controlador _Healthy_ é o parceiro de HA do controlador prejudicado.


* Se necessário, você pode ligar os LEDs de localização do chassi da plataforma (azul) para ajudar a localizar fisicamente a plataforma afetada. Faça login no BMC usando SSH e digite o `system location-led _on_` comando.
+
Um chassi de plataforma tem três LEDs de localização: Um no painel de exibição do operador e um em cada controlador. Os LEDs de localização permanecem acesos durante 30 minutos.

+
Você pode desativá-los digitando o `system location-led _off_` comando. Se não tiver a certeza se os LEDs estão ligados ou desligados, pode verificar o seu estado introduzindo o `system location-led show` comando.



.O que se segue?
Depois de rever os requisitos para substituir o suporte de arranque, tem de link:bootmedia-encryption-preshutdown-checks.html["verifique o suporte e o status da chave de criptografia na mídia de inicialização"].
