---
permalink: a20-30-50/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff a20, aff a30, aff a50, verify and set HA state, complete the replacement process 
summary: Verifique o estado de HA do chassi e, em seguida, devolva a peça com falha ao NetApp para concluir a etapa final no procedimento de substituição do chassi do AFF A20, AFF A30 e AFF A50. 
---
= Substituição completa do chassis - AFF A20, AFF A30 e AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verifique o estado de HA do chassi e, em seguida, devolva a peça com falha ao NetApp para concluir a etapa final no procedimento de substituição do chassi do AFF A20, AFF A30 e AFF A50.



== Etapa 1: Verifique e defina o estado HA do chassi

Você deve verificar o estado de HA do chassi e, se necessário, atualizar o estado para corresponder à configuração do sistema de storage.

. No modo de manutenção, a partir de qualquer um dos controladores, apresenta o estado HA do controlador local e do chassis:
+
`ha-config show`

+
O estado HA deve ser o mesmo para todos os componentes.

. Se o estado do sistema exibido para o chassi não corresponder à configuração do sistema de storage:
+
.. Defina o estado HA para o chassis:
+
`ha-config modify chassis _HA-state_`

+
O valor para HA-State deve ser _ha_. O valor para HA-State pode ser um dos seguintes: *** _Ha_ *** _mcc_ (não suportado no ASA)

.. Confirme se a definição foi alterada:
+
`ha-config show`



. Se você ainda não o fez, recable o resto do seu sistema de storage.




== Passo 2: Devolva a peça com falha ao NetApp

Devolva a peça com falha ao NetApp, conforme descrito nas instruções de RMA fornecidas com o kit. Consulte a https://mysupport.netapp.com/site/info/rma["Devolução de peças e substituições"] página para obter mais informações.
