---
permalink: a20-30-50/controller-replace-requirements.html 
sidebar: sidebar 
keywords: aff a20, aff a30, aff a50, prerequisite, replace the controller module 
summary: Tem de rever os pré-requisitos para o procedimento de substituição e selecionar o correto para a sua versão do sistema operativo ONTAP. 
---
= Requisitos e considerações - AFF A20, AFF A30 e AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve rever os requisitos e considerações para o procedimento de substituição do controlador.



== Requisitos

* Todas as prateleiras devem estar funcionando corretamente.
* O controlador saudável deve ser capaz de assumir o controlador que está a ser substituído (referido neste procedimento como ""controlador deficiente"").
* Você deve substituir um controlador por um controlador do mesmo tipo de modelo. Você não pode atualizar seu sistema apenas substituindo o controlador.
* Não é possível alterar nenhuma unidade ou compartimentos como parte deste procedimento.
* Você deve sempre capturar a saída do console do controlador para um arquivo de log de texto.
+
A saída do console fornece um Registro do procedimento que você pode usar para solucionar problemas que você pode encontrar durante o processo de substituição.





== Considerações

* É importante aplicar os comandos neste procedimento ao controlador correto:
+
** O controlador _prejudicado_ é o controlador que está sendo substituído.
** O controlador _replacement_ é o novo controlador que está substituindo o controlador prejudicado.
** O controlador _Healthy_ é o controlador sobrevivente.


* Se necessário, você pode ligar os LEDs de localização do sistema de armazenamento (azul) para ajudar a localizar fisicamente o sistema de armazenamento afetado. Faça login no BMC usando SSH e digite o `system location-led _on_` comando.
+
Um sistema de armazenamento tem três LEDs de localização: Um no painel de visualização do operador e um em cada controlador. Os LEDs de localização permanecem acesos durante 30 minutos.

+
Você pode desativá-los digitando o `system location-led _off_` comando. Se não tiver a certeza se os LEDs estão ligados ou desligados, pode verificar o seu estado introduzindo o `system location-led show` comando.


