---
permalink: a20-30-50/io-module-overview.html 
sidebar: sidebar 
keywords: aff a20, aff a30, and aff a50, replace io module, add io module, hotswap io module 
summary: Os sistemas de armazenamento AFF A20, AFF A30 e AFF A50 oferecem flexibilidade na expansão ou substituição de módulos de E/S para aprimorar a conectividade e o desempenho da rede. Adicionar, fazer hot swap ou substituir um módulo de E/S é essencial ao atualizar os recursos da rede ou solucionar um módulo com falha. 
---
= Visão geral da manutenção do módulo de E/S - AFF A20, AFF A30 e AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os sistemas de armazenamento AFF A20, AFF A30 e AFF A50 oferecem flexibilidade na expansão ou substituição de módulos de E/S para aprimorar a conectividade e o desempenho da rede. Adicionar, fazer hot swap ou substituir um módulo de E/S é essencial ao atualizar os recursos da rede ou solucionar um módulo com falha.

* link:io-module-add.html["Adicione um módulo de e/S."]
+
Você pode adicionar módulos de E/S para melhorar a redundância, ajudando a garantir que o sistema de storage permaneça operacional mesmo se um módulo de E/S falhar. Você pode adicionar módulos de E/S quando houver slots disponíveis ou quando todos os slots estiverem totalmente ocupados.

* link:io-module-hotswap.html["Substituição a quente de um módulo de E/S"]
+
É possível realizar a substituição a quente de determinados módulos de E/S por um módulo de E/S equivalente para restaurar o sistema de storage ao seu estado operacional ideal. A substituição a quente é feita sem a necessidade de realizar uma tomada manual.

+
Para utilizar este procedimento, seu sistema de storage deve estar executando ONTAP 9.17.1 ou posterior e atender aos requisitos específicos para a versão do ONTAP que seu sistema está executando.

* link:io-module-replace.html["Substitua um módulo de e/S."]
+
Você pode substituir um módulo de E/S com defeito para restaurar o sistema de storage ao seu estado operacional ideal. Este procedimento requer uma transferência manual do controlador com o módulo de E/S com defeito.


