---
permalink: asa-r2-a1k/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa r2 a1k, replace the boot media 
summary: Antes de substituir o suporte de arranque no sistema ASA A1K, certifique-se de que cumpre os requisitos necessários para uma substituição bem-sucedida. 
---
= Requisitos para substituir o suporte de arranque - ASA A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de substituir o suporte de arranque no sistema ASA A1K, certifique-se de que cumpre os requisitos necessários para uma substituição bem-sucedida. Isso inclui verificar se você tem a Mídia de inicialização de substituição correta, confirmar que não há portas de cluster com defeito no controlador e determinar se o Onboard Key Manager (OKM) ou o External Key Manager (EKM) está habilitado.

Reveja os seguintes requisitos.

* Tem de substituir o suporte de arranque com falha por um suporte de arranque de substituição que recebeu do NetApp.
* Não deve haver portas do cluster defeituosas no controlador prejudicado.
* Para OKM, você precisa do conteúdo do arquivo de senha OKM.
* Para EKM, você precisa de cópias dos seguintes arquivos do nó do parceiro:
+
** arquivo /cfcard/kmip/servers.cfg.
** arquivo /cfcard/kmip/certs/client.crt.
** arquivo /cfcard/kmip/certs/client.key.
** Arquivo /cfcard/kmip/certs/CA.pem.




.O que vem a seguir
Depois de analisar os requisitos do suporte de arranque, pode link:bootmedia-shutdown-bmr.html["desligue o controlador"].
