---
permalink: asa-r2-a1k/bootmedia-shutdown-bmr.html 
sidebar: sidebar 
keywords: asa r2 a1k, shut down the controller 
summary: Desligue o controlador desativado no sistema de armazenamento ASA A1K para evitar a perda de dados e garantir a estabilidade do sistema ao substituir a Mídia de inicialização. 
---
= Desligue o controlador para substituir o suporte de arranque - ASA A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Desligue o controlador desativado no sistema de armazenamento ASA A1K para evitar a perda de dados e garantir a estabilidade do sistema ao substituir a Mídia de inicialização.

Para encerrar o controlador com deficiência, você deve determinar o status do controlador e, se necessário, assumir o controlador para que o controlador saudável continue fornecendo dados do armazenamento do controlador com deficiência.

.Sobre esta tarefa
* Se você tiver um sistema SAN, você deve ter verificado mensagens de  `cluster kernel-service show`evento ) para o blade SCSI do controlador afetado. O `cluster kernel-service show` comando (do modo avançado priv) exibe o nome do nó, link:https://docs.netapp.com/us-en/ontap/system-admin/display-nodes-cluster-task.html["status do quorum"]desse nó, o status de disponibilidade desse nó e o status operacional desse nó.
+
Cada processo SCSI-blade deve estar em quórum com os outros nós no cluster. Qualquer problema deve ser resolvido antes de prosseguir com a substituição.

* Se você tiver um cluster com mais de dois nós, ele deverá estar no quórum. Se o cluster não estiver em quórum ou se um controlador íntegro exibir false para qualificação e integridade, você deverá corrigir o problema antes de encerrar o controlador prejudicado; link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Sincronize um nó com o cluster"^]consulte .


.Passos
. Se o AutoSupport estiver ativado, suprimir a criação automática de casos invocando uma mensagem AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`

+
A seguinte mensagem AutoSupport suprime a criação automática de casos por duas horas:

+
`cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. Desabilitar devolução automática:
+
.. Digite o seguinte comando no console do controlador íntegro:
+
`storage failover modify -node local -auto-giveback false`

.. Digitar `y` quando você vê o prompt _Você quer desabilitar o retorno automático?_


. Leve o controlador prejudicado para o prompt Loader:
+
[cols="1,2"]
|===
| Se o controlador afetado estiver a apresentar... | Então... 


 a| 
O prompt Loader
 a| 
Vá para a próxima etapa.



 a| 
A aguardar pela giveback...
 a| 
Pressione Ctrl-C e responda `y` quando solicitado.



 a| 
Prompt do sistema ou prompt de senha
 a| 
Assuma ou interrompa o controlador prejudicado do controlador saudável:

`storage failover takeover -ofnode _impaired_node_name_ -halt _true_`

O parâmetro _-halt True_ traz para o prompt Loader.

|===


.O que vem a seguir
Depois de desligar o controlador desativado, você link:bootmedia-replace-bmr.html["substitua o suporte de arranque"].
