---
permalink: asa-r2-a1k/controller-replace-restore-system-rma.html 
sidebar: sidebar 
keywords: asa r2 a1k, how to restore NetApp Storage Encryption, how to complete the replacement process 
summary: 'Verifique se as interfaces lógicas (LIFs) estão relatando para sua porta inicial, execute uma verificação de integridade do cluster e, em seguida, retorne a peça com falha ao NetApp para concluir a etapa final no procedimento de substituição do controlador ASA A1K.' 
---
= Substituição completa do controlador - ASA A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para concluir a substituição do controlador do seu sistema ASA A1K, primeiro restaure a configuração do NetApp Storage Encryption (se necessário). Em seguida, confirme se as interfaces lógicas (LIFs) estão relatando para suas portas domésticas e execute uma verificação de integridade do cluster. Por fim, devolva a peça com defeito à NetApp.



== Etapa 1: Verificar LIFs e verificar a integridade do cluster

Antes de retornar o nó de substituição ao serviço, verifique se as interfaces lógicas estão em suas portas iniciais, verifique a integridade do cluster e redefina a giveback automática.

.Passos
. Verifique se as interfaces lógicas estão reportando ao servidor doméstico e às portas:
+
`network interface show -is-home false`

+
Se alguma interface lógica estiver listada como falsa, reverta-a para suas portas originais:

+
`network interface revert -vserver * -lif *`

. Verifique a integridade do seu cluster.  Veja o https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["Como realizar uma verificação de integridade do cluster com um script no ONTAP"^] Artigo da Base de Conhecimento.
. Se a giveback automática foi desativada, reative-a:
+
`storage failover modify -node local -auto-giveback true`





== Passo 2: Devolva a peça com falha ao NetApp

Devolva a peça com falha ao NetApp, conforme descrito nas instruções de RMA fornecidas com o kit. Consulte a https://mysupport.netapp.com/site/info/rma["Devolução de peças e substituições"] página para obter mais informações.
