= 
:allow-uri-read: 


[NOTE]
====
NetApp recomenda fortemente que você habilite o registro de logs no console nos dispositivos que estiver utilizando e execute as seguintes ações ao realizar este procedimento:

* Deixe AutoSupport ativado durante a sua manutenção. Isso permite que o suporte da NetApp receba informações de diagnóstico caso ocorram problemas.
* Habilite o registro de sessão para todas as sessões da CLI. Isso cria um registro completo de todos os comandos e da saída do sistema durante a atividade de manutenção. Para obter orientações sobre como habilitar o registro de sessão, consulte  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Como configurar o PuTTY para obter conectividade ideal com sistemas ONTAP"^].


====
.Pen drive USB
* Certifique-se de ter uma unidade flash USB formatada para FAT32.
* O USB deve ter capacidade de armazenamento suficiente para armazenar o  `image_xxx.tgz` arquivo.


.Preparação do arquivo
Copie o  `image_xxx.tgz` arquivo para o pen drive USB. Este arquivo será usado quando você transferir a imagem ONTAP usando o pen drive USB.

Da imagem ONTAP extraída, copie a pasta  `EFI` para o diretório raiz da unidade flash USB.

.Substituição de componentes
Substitua o componente com falha pelo componente de substituição fornecido pela NetApp.

.Identificação do controlador
É fundamental aplicar os comandos ao controlador correto ao substituir a mídia de inicialização danificada:

* O _controlador danificado_ é o controlador no qual você está executando a manutenção.
* O _controlador saudável_ é o parceiro HA do controlador prejudicado.

