= 
:allow-uri-read: 


[NOTE]
====
NetApp recomenda fortemente que você habilite o registro de logs no console nos dispositivos que estiver utilizando e execute as seguintes ações ao realizar este procedimento:

* Deixe AutoSupport ativado durante a sua manutenção. Isso permite que o suporte da NetApp receba informações de diagnóstico caso ocorram problemas.
* Habilite o registro de sessão para todas as sessões da CLI. Isso cria um registro completo de todos os comandos e da saída do sistema durante a atividade de manutenção. Para obter orientações sobre como habilitar o registro de sessão, consulte  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Como configurar o PuTTY para obter conectividade ideal com sistemas ONTAP"^].


====
* Você deve substituir o componente com falha por um componente FRU de substituição da mesma capacidade que recebeu do NetApp.
* Verifique se a interface e0S (porta de chave inglesa e0M) no controlador com defeito não está com falha.
+
A porta e0M é usada para comunicação entre os dois controladores durante o processo de recuperação de inicialização automatizada.

* Para o OKM, você precisa da senha de todo o cluster e também dos dados de backup.
* Para EKM, você precisa de cópias dos seguintes arquivos do nó do parceiro:
+
** arquivo /cfcard/kmip/servers.cfg.
** arquivo /cfcard/kmip/certs/client.crt.
** arquivo /cfcard/kmip/certs/client.key.
** Arquivo /cfcard/kmip/certs/CA.pem.


* É fundamental aplicar os comandos ao controlador correto ao substituir a mídia de inicialização danificada:
+
** O _controlador danificado_ é o controlador no qual você está executando a manutenção.
** O _controlador saudável_ é o parceiro HA do controlador prejudicado.



