= 
:allow-uri-read: 


[role="tabbed-block"]
====
.Sem criptografia
--
Volte a colocar o controlador afetado em funcionamento normal, devolvendo o respetivo armazenamento.

.Passos
. No prompt Loader, digite `boot_ontap`.
. Pressione <enter> quando as mensagens do console pararem.
+
** Se você vir o prompt _login_, vá para a próxima etapa no final desta seção.
** Se você vir _aguardando giveback_, pressione a tecla <enter>, faça login no nó do parceiro e vá para a próxima etapa no final desta seção.


. Volte a colocar o controlador afetado em funcionamento normal, devolvendo o respetivo armazenamento: `storage failover giveback -ofnode _impaired_node_name_`
. Se a giveback automática foi desativada, reative-a: `storage failover modify -node local -auto-giveback _true_`
. Se o AutoSupport estiver ativado, restaurar/anular a criação automática de casos: `system node autosupport invoke -node * -type all -message MAINT=END`


--
.Criptografia integrada (OKM)
--
Redefina a criptografia integrada e retorne o controlador à operação normal.

.Passos
. No prompt Loader, digite `boot_ontap maint`.
. Inicie no menu ONTAP a partir do prompt Loader `boot_ontap menu` e selecione a opção 10.
. Introduza a frase-passe OKM.
+

NOTE: Você é solicitado duas vezes para a senha.

. Insira os dados da chave de backup quando solicitado.
. No menu de inicialização, insira a opção `1` para inicialização normal.
. Pressione <enter> quando _Waiting for giveback_ for exibido.
. Mova o cabo do console para o nó do parceiro e faça login como `admin`.
. Devolver apenas os agregados CFO (o agregado raiz): `storage failover giveback -fromnode local -only-cfo-aggregates _true_`
+
** Se encontrar erros, https://support.netapp.com["Suporte à NetApp"] contacte .


. Aguarde 5 minutos após a conclusão do relatório de giveback e verifique o status de failover e o status de giveback `storage failover show`: E `storage failover show-giveback`.
. Sincronize e verifique o status das chaves:
+
.. Volte a colocar o cabo da consola no controlador de substituição.
.. Sincronizar chaves em falta: `security key-manager onboard sync`
+

NOTE: Você é solicitado a fornecer a senha de OKM para o cluster.

.. Verifique o status das chaves: `security key-manager key query -restored _false_`
+
A saída não deve mostrar resultados quando devidamente sincronizada.

+
Se a saída apresentar resultados (as IDs das chaves que não estão presentes na tabela de chaves internas do sistema), contacte https://support.netapp.com["Suporte à NetApp"].



. Volte a colocar o controlador afetado em funcionamento normal, devolvendo o respetivo armazenamento: `storage failover giveback -ofnode _impaired_node_name_`
. Se a giveback automática foi desativada, reative-a: `storage failover modify -node local -auto-giveback _true_`
. Se o AutoSupport estiver ativado, restaurar/anular a criação automática de casos: `system node autosupport invoke -node * -type all -message MAINT=END`


--
====