= Verifique a configuração do NVE
:allow-uri-read: 


Antes de desligar a controladora prejudicada, você precisa verificar se o sistema tem a criptografia de volume NetApp (NVE) ou a criptografia de armazenamento NetApp (NSE) ativada. Se sim, você precisa verificar a configuração.

. Verifique se o NVE está em uso para quaisquer volumes no cluster: `volume show -is-encrypted true`
+
Se algum volume estiver listado na saída, o NVE será configurado e você precisará verificar a configuração do NVE. Se nenhum volume estiver listado, verifique se o NSE está configurado e em uso.

. Verifique se o NSE está configurado e em uso: `storage encryption disk show`
+
** Se o comando OUTPUT listar os detalhes da unidade com informações de ID de modo e chave, o NSE está configurado e você precisa verificar a configuração do NSE e em uso.
** Se não forem apresentados discos, o NSE não está configurado.
** Se o NVE e o NSE não estiverem configurados, nenhuma unidade será protegida com chaves NSE, é seguro desligar o controlador desativado.






== Verifique a configuração do NVE

. Exibir as IDs de chave das chaves de autenticação armazenadas nos servidores de gerenciamento de chaves: `security key-manager key query`
+

NOTE: Após o lançamento do ONTAP 9.6, você pode ter tipos adicionais de gerenciador de chaves. Os tipos são `KMIP`, `AKV` e `GCP`. O processo para confirmar esses tipos é o mesmo que os tipos de confirmação `external` ou `onboard` gerenciador de chaves.

+
** Se o `Key Manager` tipo for exibido `external` e a `Restored` coluna for exibida `yes`, é seguro desligar o controlador prejudicado.
** Se o `Key Manager` tipo for exibido `onboard` e a `Restored` coluna for exibida `yes`, você precisará concluir algumas etapas adicionais.
** Se o `Key Manager` tipo for exibido `external` e a `Restored` coluna exibir qualquer outra coisa que não `yes`o , você precisará concluir algumas etapas adicionais.
** Se o `Key Manager` tipo for exibido `onboard` e a `Restored` coluna exibir qualquer outra coisa que não `yes`o , você precisará concluir algumas etapas adicionais.


. Se o `Key Manager` tipo for exibido `onboard` e a `Restored` coluna for exibida `yes`, faça backup manual das informações OKM:
+
.. Vá para o modo de privilégio avançado e entre `y` quando solicitado a continuar: `set -priv advanced`
.. Digite o comando para exibir as informações de gerenciamento de chaves: `security key-manager onboard show-backup`
.. Copie o conteúdo das informações de backup para um arquivo separado ou seu arquivo de log. Você vai precisar dele em cenários de desastre onde você pode precisar recuperar manualmente OKM.
.. Voltar ao modo de administração: `set -priv admin`
.. Desligue o controlador desativado.


. Se o `Key Manager` tipo for exibido `external` e a `Restored` coluna exibir algo diferente `yes`de :
+
.. Restaure as chaves de autenticação de gerenciamento de chaves externas para todos os nós no cluster: `security key-manager external restore`
+
Se o comando falhar, entre em Contato com o suporte da NetApp.

+
http://mysupport.netapp.com/["mysupport.NetApp.com"^]

.. Verifique se a `Restored` coluna é igual a `yes` todas as chaves de autenticação: `security key-manager key query`
.. Desligue o controlador desativado.


. Se o `Key Manager` tipo for exibido `onboard` e a `Restored` coluna exibir algo diferente `yes`de :
+
.. Digite o comando Onboard security key-manager sync: `security key-manager onboard sync`
+

NOTE: Insira a senha alfanumérica de gerenciamento de chaves integradas de 32 carateres do cliente no prompt. Se a frase-passe não puder ser fornecida, contacte o suporte da NetApp. http://mysupport.netapp.com/["mysupport.NetApp.com"^]

.. Verifique se a `Restored` coluna mostra `yes` todas as chaves de autenticação: `security key-manager key query`
.. Verifique se o `Key Manager` tipo mostra `onboard`e faça backup manual das informações OKM.
.. Vá para o modo de privilégio avançado e entre `y` quando solicitado a continuar: `set -priv advanced`
.. Digite o comando para exibir as informações de backup de gerenciamento de chaves: `security key-manager onboard show-backup`
.. Copie o conteúdo das informações de backup para um arquivo separado ou seu arquivo de log. Você vai precisar dele em cenários de desastre onde você pode precisar recuperar manualmente OKM.
.. Voltar ao modo de administração: `set -priv admin`
.. Pode desligar o controlador com segurança.






== Verifique a configuração do NSE

. Exibir as IDs de chave das chaves de autenticação armazenadas nos servidores de gerenciamento de chaves: `security key-manager key query -key-type NSE-AK`
+

NOTE: Após o lançamento do ONTAP 9.6, você pode ter tipos adicionais de gerenciador de chaves. Os tipos são `KMIP`, `AKV` e `GCP`. O processo para confirmar esses tipos é o mesmo que os tipos de confirmação `external` ou `onboard` gerenciador de chaves.

+
** Se o `Key Manager` tipo for exibido `external` e a `Restored` coluna for exibida `yes`, é seguro desligar o controlador prejudicado.
** Se o `Key Manager` tipo for exibido `onboard` e a `Restored` coluna for exibida `yes`, você precisará concluir algumas etapas adicionais.
** Se o `Key Manager` tipo for exibido `external` e a `Restored` coluna exibir qualquer outra coisa que não `yes`o , você precisará concluir algumas etapas adicionais.
** Se o `Key Manager` tipo for exibido `external` e a `Restored` coluna exibir qualquer outra coisa que não `yes`o , você precisará concluir algumas etapas adicionais.


. Se o `Key Manager` tipo for exibido `onboard` e a `Restored` coluna for exibida `yes`, faça backup manual das informações OKM:
+
.. Vá para o modo de privilégio avançado e entre `y` quando solicitado a continuar: `set -priv advanced`
.. Digite o comando para exibir as informações de gerenciamento de chaves: `security key-manager onboard show-backup`
.. Copie o conteúdo das informações de backup para um arquivo separado ou seu arquivo de log. Você vai precisar dele em cenários de desastre onde você pode precisar recuperar manualmente OKM.
.. Voltar ao modo de administração: `set -priv admin`
.. Pode desligar o controlador com segurança.


. Se o `Key Manager` tipo for exibido `external` e a `Restored` coluna exibir algo diferente `yes`de :
+
.. Restaure as chaves de autenticação de gerenciamento de chaves externas para todos os nós no cluster: `security key-manager external restore`
+
Se o comando falhar, entre em Contato com o suporte da NetApp.

+
http://mysupport.netapp.com/["mysupport.NetApp.com"^]

.. Verifique se a `Restored` coluna é igual a `yes` todas as chaves de autenticação: `security key-manager key query`
.. Pode desligar o controlador com segurança.


. Se o `Key Manager` tipo for exibido `onboard` e a `Restored` coluna exibir algo diferente `yes`de :
+
.. Digite o comando Onboard security key-manager sync: `security key-manager onboard sync`
+
Insira a senha alfanumérica de gerenciamento de chaves integradas de 32 carateres do cliente no prompt. Se a frase-passe não puder ser fornecida, contacte o suporte da NetApp.

+
http://mysupport.netapp.com/["mysupport.NetApp.com"^]

.. Verifique se a `Restored` coluna mostra `yes` todas as chaves de autenticação: `security key-manager key query`
.. Verifique se o `Key Manager` tipo mostra `onboard`e faça backup manual das informações OKM.
.. Vá para o modo de privilégio avançado e entre `y` quando solicitado a continuar: `set -priv advanced`
.. Digite o comando para exibir as informações de backup de gerenciamento de chaves: `security key-manager onboard show-backup`
.. Copie o conteúdo das informações de backup para um arquivo separado ou seu arquivo de log. Você vai precisar dele em cenários de desastre onde você pode precisar recuperar manualmente OKM.
.. Voltar ao modo de administração: `set -priv admin`
.. Pode desligar o controlador com segurança.



