= Requisitos
:allow-uri-read: 


Reveja os seguintes requisitos e considerações.



== Requisitos

* O chassis de substituição tem de ser o mesmo modelo que o chassis com deficiência. Este procedimento é para uma substituição similar, não para uma atualização.
* Todos os outros componentes do sistema de armazenamento devem estar a funcionar corretamente; caso contrário, contacte https://mysupport.netapp.com/site/global/dashboard["Suporte à NetApp"] antes de continuar com este procedimento.




== Considerações

* O procedimento de substituição do chassis é disruptivo. Para um cluster de dois nós, você terá uma interrupção de serviço completa e uma interrupção parcial em um cluster de vários nós.
* Você pode usar o procedimento de substituição de chassi com todas as versões do ONTAP suportadas pelo sistema de storage.
* O procedimento de substituição do chassi é escrito com a suposição de que você está movendo o painel frontal, as unidades, quaisquer lacunas de unidade e os controladores para o novo chassi.

