= Requisitos
:allow-uri-read: 


Você deve rever os requisitos e considerações para o procedimento de substituição do controlador.



== Requisitos

* Todas as prateleiras devem estar funcionando corretamente.
* O controlador saudável deve ser capaz de assumir o controlador que está a ser substituído (referido neste procedimento como ""controlador deficiente"").
* Você deve substituir um controlador por um controlador do mesmo tipo de modelo. Você não pode atualizar seu sistema apenas substituindo o controlador.
* Não é possível alterar nenhuma unidade ou compartimentos como parte deste procedimento.
* Você deve sempre capturar a saída do console do controlador para um arquivo de log de texto.
+
A saída do console fornece um Registro do procedimento que você pode usar para solucionar problemas que você pode encontrar durante o processo de substituição.





== Considerações

* É importante aplicar os comandos neste procedimento ao controlador correto:
+
** O controlador _prejudicado_ é o controlador que está sendo substituído.
** O controlador _replacement_ é o novo controlador que está substituindo o controlador prejudicado.
** O controlador _Healthy_ é o controlador sobrevivente.



