= 
:allow-uri-read: 


Você pode substituir uma unidade com falha sem interrupções enquanto a e/S estiver em andamento.

.Antes de começar
* A unidade que você está instalando deve ser suportada pelo seu sistema de armazenamento.
+
https://hwu.netapp.com["NetApp Hardware Universe"^]

* Se a autenticação de unidade com autocriptografia (SED) estiver ativada, você deverá usar as instruções de substituição do SED na documentação do ONTAP.
+
As instruções na documentação do ONTAP descrevem as etapas adicionais que você deve executar antes e depois de substituir uma SED.

+
https://docs.netapp.com/us-en/ontap/encryption-at-rest/index.html["Visão geral da criptografia NetApp com a CLI"^]

* Todos os outros componentes do sistema de armazenamento têm de estar a funcionar corretamente; caso contrário, tem de contactar https://mysupport.netapp.com/site/global/dashboard["Suporte à NetApp"] antes de continuar com este procedimento.
* Verifique se a unidade que você está removendo está com falha.
+
Você pode verificar se a unidade está com falha executando o `storage disk show -broken` comando. A unidade com falha aparece na lista de unidades com falha. Se isso não acontecer, você deve esperar, e então executar o comando novamente.

+

NOTE: Dependendo do tipo e da capacidade da unidade, pode levar até várias horas para a unidade aparecer na lista de unidades com falha.



.Sobre esta tarefa
* Ao substituir uma unidade com falha, você deve esperar 70 segundos entre a remoção da unidade e a inserção da unidade de substituição para permitir que o sistema de armazenamento reconheça que uma unidade foi removida.
* A prática recomendada é ter a versão atual do Pacote de Qualificação de disco (DQP) instalada antes de trocar uma unidade em modo automático.
+
Ter a versão atual do DQP instalada permite que seu sistema reconheça e use unidades recém-qualificadas. Isso evita mensagens de eventos do sistema sobre ter informações de unidade não atuais e prevenção do particionamento de unidade porque as unidades não são reconhecidas. O DQP também notifica você sobre o firmware da unidade não atual.

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware/download/DISKQUAL/ALL/qual_devices.zip["NetApp Downloads: Pacote de Qualificação de disco"^]

* A prática recomendada é ter versões atuais do firmware do módulo de gaveta NVMe (NSM) e do firmware da unidade no sistema antes de substituir os componentes da FRU.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["Downloads do NetApp: Firmware da gaveta de disco"^]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["Downloads do NetApp: Firmware da unidade de disco"^]

+
[NOTE]
====
Não reverta o firmware para uma versão que não suporte a gaveta e seus componentes.

====
* O firmware da unidade é atualizado automaticamente (sem interrupções) em novas unidades com versões de firmware não atuais.
+

NOTE: As verificações de firmware da unidade ocorrem a cada dois minutos.

* Se necessário, você pode ligar os LEDs de localização do sistema de armazenamento (azul) para ajudar a localizar fisicamente o sistema de armazenamento afetado. Faça login no BMC usando SSH e digite o `system location-led _on_` comando.
+
Um sistema de armazenamento tem três LEDs de localização: Um no painel de visualização do operador e um em cada controlador. Os LEDs de localização permanecem acesos durante 30 minutos.

+
Você pode desativá-los digitando o `system location-led _off_` comando. Se não tiver a certeza se os LEDs estão ligados ou desligados, pode verificar o seu estado introduzindo o `system location-led show` comando.


