= 
:allow-uri-read: 


Coloque o cluster de substituição e o módulo HA I/O no slot 4 on-line, verifique se as portas do módulo foram inicializadas com sucesso, verifique se o slot 4 está ligado e, em seguida, verifique se o módulo está on-line e é reconhecido.

. Coloque o cluster de substituição e o módulo de E/S HA on-line:
+
.. Digite o seguinte comando:
+
`system controller slot module insert -node _impaired_node_name_ -slot _slot_name_`

.. Digitar `y` quando você vê o prompt, _Você quer continuar?_
+
A saída deve confirmar que o cluster e o módulo HA I/O foram colocados on-line com sucesso (ligados, inicializados e colocados em serviço).

+
Por exemplo, o comando a seguir coloca o slot 4 no nó 2 (o controlador prejudicado) online e exibe uma mensagem de que o processo foi bem-sucedido:

+
[listing]
----
node2::> system controller slot module insert -node node2 -slot 4

Warning: IO_2X_100GBE_NVDA_NIC module in slot 4 of node node2 will be powered on and initialized.

Do you want to continue? {y|n}: `y`

The module has been successfully powered on, initialized and placed into service.
----


. Verifique se cada porta no cluster e o módulo de E/S HA foram inicializados com sucesso:
+
`event log show -event \*hotplug.init*`

+

NOTE: Pode levar vários minutos para permitir quaisquer atualizações de firmware necessárias e a inicialização da porta.

+
A saída deve mostrar um evento hotplug.init.success EMS registrado para cada porta no cluster e módulo HA I/O com  `_hotplug.init.success:_` no  `_Event_` coluna.

+
Por exemplo, a saída a seguir mostra que a inicialização foi bem-sucedida para as portas e4b e e4a do cluster e do módulo de E/S HA:

+
[listing]
----
node2::> event log show -event *hotplug.init*

Time                Node             Severity      Event

------------------- ---------------- ------------- ---------------------------

7/11/2025 16:04:06  node2      NOTICE        hotplug.init.success: Initialization of ports "e4b" in slot 4 succeeded

7/11/2025 16:04:06  node2      NOTICE        hotplug.init.success: Initialization of ports "e4a" in slot 4 succeeded

2 entries were displayed.
----
. Verifique se o slot 4 do módulo de E/S está ligado e pronto para operação:
+
`system controller slot module show`

+
A saída deve mostrar o status do slot 4 como  `_powered-on_` e, portanto, pronto para a operação do cluster de substituição e do módulo HA I/O.

. Verifique se o cluster de substituição e o módulo de E/S HA estão on-line e são reconhecidos.
+
Digite o comando do console do controlador com deficiência:

+
`system controller config show -node local -slot4`

+
Se o cluster de substituição e o módulo de E/S HA forem colocados on-line com sucesso e reconhecidos, a saída mostrará informações do módulo de E/S, incluindo informações de porta, para o slot 4.

+
Por exemplo, você deverá ver uma saída semelhante à seguinte:

+
[listing]
----
node2::> system controller config show -node local -slot 4

Node: node2
Sub- Device/
Slot slot Information
---- ---- -----------------------------
   4    - Dual 40G/100G Ethernet Controller CX6-DX
                  e4a MAC Address: d0:39:ea:59:69:74 (auto-100g_cr4-fd-up)
                          QSFP Vendor:        CISCO-BIZLINK
                          QSFP Part Number:   L45593-D218-D10
                          QSFP Serial Number: LCC2807GJFM-B
                  e4b MAC Address: d0:39:ea:59:69:75 (auto-100g_cr4-fd-up)
                          QSFP Vendor:        CISCO-BIZLINK
                          QSFP Part Number:   L45593-D218-D10
                          QSFP Serial Number: LCC2809G26F-A
                  Device Type:        CX6-DX PSID(NAP0000000027)
                  Firmware Version:   22.44.1700
                  Part Number:        111-05341
                  Hardware Revision:  20
                  Serial Number:      032403001370
----

