= Equipamento necessário para instalação
:allow-uri-read: 




== Equipamento necessário para instalação

Para instalar seu sistema de storage, você precisa dos seguintes equipamentos e ferramentas.

* Acesso a um navegador da Web para configurar o sistema de armazenamento
* Fita de descarga eletrostática (ESD)
* Lanterna
* Computador portátil ou console com conexão USB/serial
* Clipe de papel ou caneta esferográfica de ponta estreita para definir NS224 IDs de prateleira de armazenamento
* Chave de fendas Phillips nº 2




== Precauções de elevação

Os sistemas de armazenamento e as prateleiras são pesados. Tenha cuidado ao levantar e mover estes itens.



=== Peso do sistema de armazenamento

Tome as precauções necessárias ao mover ou elevar o sistema de armazenamento.



=== Peso da prateleira

Tome as precauções necessárias ao mover ou levantar a prateleira.

.Informações relacionadas
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Informações de segurança e avisos regulamentares"^]

