= Passo 1: Prepare o site
:allow-uri-read: 




== Passo 1: Prepare o site

Para instalar seu sistema de armazenamento, certifique-se de que o local e o gabinete ou rack que você planeja usar atendam às especificações de sua configuração.

.Passos
. Use https://hwu.netapp.com["NetApp Hardware Universe"^] para confirmar se o local atende aos requisitos ambientais e elétricos do sistema de armazenamento.
. Certifique-se de que tem espaço de rack adequado:
+
** 4U em uma configuração de HA para o sistema de storage
** 2U TB para cada compartimento de armazenamento de NS224 TB


+
*NOTA:* link:https://hwu.netapp.com["NetApp Hardware Universe"^]consulte para obter os requisitos de espaço em rack para outras prateleiras de armazenamento suportadas.

. Instale todos os switches de rede necessários.
+
Consulte o https://docs.netapp.com/us-en/ontap-systems-switches/index.html["Documentação do switch"^] para obter instruções de instalação e link:https://hwu.netapp.com["NetApp Hardware Universe"^] para obter informações sobre compatibilidade.





== Passo 2: Desembale as caixas

Depois de garantir que o local e o gabinete ou rack que você planeja usar para o seu sistema de armazenamento atendam às especificações necessárias, desembale todas as caixas e compare o conteúdo com os itens na guia de embalagem.

.Passos
. Abra cuidadosamente todas as caixas e coloque o conteúdo de forma organizada.
. Compare o conteúdo que você descompactou com a lista no folheto de embalagem.
+

NOTE: Você pode obter sua lista de embalagem digitalizando o código QR no lado da caixa de transporte.

+
Os itens a seguir são alguns dos conteúdos que você pode ver nas caixas.

+
Certifique-se de que tudo nas caixas corresponde à lista no folheto de embalagem. Se houver discrepâncias, anote-as para outras ações.

+
[cols="12,9,4"]
|===


| *Hardware* | *Cabos* |  


 a| 
** Painel frontal
** Dispositivo de gerenciamento de cabos
** Sistema de storage
** Kits de trilhos com instruções (opcional)
** Compartimento de armazenamento

 a| 
** Cabos Ethernet de gerenciamento (cabos RJ-45)
** Cabos de rede
** Cabos de energia
** Cabos de armazenamento (se você tiver pedido armazenamento adicional)
** Cabo de porta serial USB-C.

|  
|===




== Passo 3: Registre seu sistema de armazenamento

Depois de garantir que o seu local cumpre os requisitos das especificações do seu sistema de armazenamento e ter verificado que tem todas as peças que encomendou, deve registar o seu sistema.

.Passos
. Localize o número de série do seu sistema de armazenamento.
+
Você pode encontrar o número no boletim de embalagem, em seu e-mail de confirmação ou no módulo de gerenciamento do sistema do controlador depois de descompactá-lo.

+
image::../media/drw_ssn_label.svg[Exemplo de número de série do sistema]

. Vá para http://mysupport.netapp.com/["Site de suporte da NetApp"^] .
. Determine se você precisa Registrar seu sistema de storage:
+
[cols="1a,2a"]
|===
| Se você é um... | Siga estes passos... 


 a| 
Cliente NetApp existente
 a| 
.. Inicie sessão com o seu nome de utilizador e palavra-passe.
.. Selecione *sistemas* > *Meus sistemas*.
.. Confirme se o novo número de série está listado.
.. Se não estiver, siga as instruções para novos clientes NetApp.




 a| 
Novo cliente da NetApp
 a| 
.. Clique em *Registe-se agora* e crie uma conta.
.. Selecione *Systems* > *Register Systems*.
.. Introduza o número de série do sistema de armazenamento e os detalhes solicitados.


Após a aprovação do seu registo, pode transferir qualquer software necessário. O processo de aprovação pode demorar até 24 horas.

|===

