= Equipamento necessário para instalação
:allow-uri-read: 




== Equipamento necessário para instalação

Para instalar seu sistema de storage, você precisa dos seguintes equipamentos e ferramentas.

* Acesso a um navegador da Web para configurar o sistema de armazenamento
* Fita de descarga eletrostática (ESD)
* Lanterna
* Computador portátil ou console com conexão USB/serial
* Clipe de papel ou caneta esferográfica de ponta estreita para definir NS224 IDs de prateleira de armazenamento
* Chave de fendas Phillips nº 2




== Precauções de elevação

Os sistemas de armazenamento e as prateleiras de armazenamento são pesados. Tenha cuidado ao levantar e mover estes itens.



=== Pesos do sistema de armazenamento

Tome as precauções necessárias ao mover ou elevar o sistema de armazenamento.

[role="tabbed-block"]
====
.A1K
--
Um sistema de armazenamento A1K pode pesar até 62,83 lbs (28,5 kg). Para levantar o sistema, utilize duas pessoas ou um elevador hidráulico.

image::../media/drw_a1k_weight_caution_ieops-1698.svg[Ícone de aviso de elevação do AFF A1K]

--
.A70 e A90
--
Um sistema de armazenamento A70 ou um sistema de armazenamento A90 podem pesar até 151,68 lbs (68,8 kg). Para levantar o sistema, utilize quatro pessoas ou um elevador hidráulico.

image::../media/drw_a70-90_weight_icon_ieops-1730.svg[Ícone de aviso de peso do AFF A90 e do AFF A70]

--
====


=== Pesos da prateleira de armazenamento

Uma prateleira de armazenamento de NS224 kg pode pesar até 66,78 lbs (30,29 kg). Para levantar a prateleira de armazenamento, utilize duas pessoas ou um elevador hidráulico. Mantenha todos os componentes na prateleira de armazenamento (dianteira e traseira) para evitar o desbalanceamento do peso da prateleira.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 precaução de elevação]

.Informações relacionadas
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Informações de segurança e avisos regulamentares"^]

