---
permalink: c190/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: AFF c190, nondisruptive, disruptive, replace the boot media, manual, manual boot recovery 
summary: Saiba mais sobre a substituição da mídia de inicialização em um sistema AFF C190 e entenda os diferentes métodos de substituição. O sistema AFF C190 suporta apenas procedimentos manuais de recuperação de mídia de inicialização. A recuperação automática de mídia de inicialização não é suportada. 
---
= Descrição geral da substituição do suporte de arranque - AFF C190
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Saiba mais sobre a substituição da mídia de inicialização em um sistema AFF C190 e entenda os diferentes métodos de substituição. A mídia de inicialização armazena arquivos de imagem de inicialização primários e secundários que o sistema usa durante a inicialização. Dependendo da configuração da sua rede, você pode realizar uma substituição sem interrupção (par HA conectado à rede) ou uma substituição com interrupção (requer duas reinicializações).

O sistema AFF C190 suporta apenas procedimentos manuais de recuperação de mídia de inicialização. A recuperação automática de mídia de inicialização não é suportada.

Tem de ter uma unidade flash USB, formatada para FAT32, com a quantidade de armazenamento adequada para guardar o `image_xxx.tgz` ficheiro.

* Os métodos sem interrupções e disruptivos para substituir uma Mídia de inicialização exigem que você restaure o sistema de arquivos var:
+
** Para substituição sem interrupções, o par de HA deve ser conetado a uma rede para restaurar o sistema de arquivos var.
** Para a substituição disruptiva, não é necessário uma ligação de rede para restaurar o sistema de ficheiros var, mas o processo requer duas reinicializações.


* Você deve substituir o componente com falha por um componente FRU de substituição que você recebeu de seu provedor.
* É importante que você aplique os comandos nestas etapas no controlador correto:
+
** O controlador _prejudicado_ é o controlador no qual você está realizando a manutenção.
** O controlador _Healthy_ é o parceiro de HA do controlador prejudicado.



