---
permalink: c190/bootmedia-shutdown.html 
sidebar: sidebar 
keywords: aff c190, shut down the controller, manual, manual boot recovery 
summary: Após concluir as verificações de criptografia, desligue o controlador com defeito em um sistema AFF C190 . O sistema AFF C190 suporta apenas procedimentos manuais de recuperação de mídia de inicialização. A recuperação automática de mídia de inicialização não é suportada. 
---
= Desligue o controlador - AFF C190
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Após concluir as verificações de criptografia, desligue o controlador com defeito em um sistema AFF C190 . Este procedimento inclui levar o controlador ao prompt LOADER, capturar as variáveis ​​de ambiente de inicialização para referência e preparar o controlador para a substituição da mídia de inicialização.

O sistema AFF C190 suporta apenas procedimentos manuais de recuperação de mídia de inicialização. A recuperação automática de mídia de inicialização não é suportada.

Depois de concluir as tarefas NVE ou NSE, você precisa concluir o desligamento do controlador desativado.

.Passos
. Leve o controlador prejudicado para o prompt Loader:
+
[cols="1,2"]
|===
| Se o controlador afetado apresentar... | Então... 


 a| 
O prompt Loader
 a| 
Vá para Remover módulo do controlador.



 a| 
`Waiting for giveback...`
 a| 
Pressione Ctrl-C e responda `y` quando solicitado.



 a| 
Prompt do sistema ou prompt de senha (digite a senha do sistema)
 a| 
Assuma ou interrompa o controlador prejudicado do controlador saudável: `storage failover takeover -ofnode impaired_node_name`

Quando o controlador prejudicado mostrar aguardando a giveback..., pressione Ctrl-C e responda `y`.

|===
. No prompt Loader, digite: `printenv` Para capturar todas as variáveis ambientais de inicialização. Salve a saída no arquivo de log.
+

NOTE: Este comando pode não funcionar se o dispositivo de inicialização estiver corrompido ou não funcional.


