---
permalink: c190/chassis-replace-overview.html 
sidebar: sidebar 
keywords: aff c190, replace the chassis 
summary: Substituir um chassis com deficiência o novo chassis do mesmo modelo que o chassis com deficiência. 
---
= Analise os requisitos antes de substituir o chassi AFF C190
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de substituir o chassi do seu AFF C190, revise os requisitos para uma substituição bem-sucedida. O procedimento de substituição do chassi exige a transferência de todas as unidades, fontes de alimentação e módulos de controle do chassi com problema para o chassi de substituição e é um processo disruptivo.

Todos os outros componentes do sistema devem estar funcionando corretamente; caso contrário, você deve entrar em Contato com o suporte técnico.

* Pode utilizar este procedimento com todas as versões do ONTAP suportadas pelo seu sistema.
* Este procedimento é escrito com a suposição de que você está movendo todas as unidades e módulos de controladora ou módulos para o novo chassi e que o chassi é um novo componente da NetApp.
* Este procedimento é disruptivo. Para um cluster de dois nós, você terá uma interrupção de serviço completa e uma interrupção parcial em um cluster de vários nós.

