---
permalink: a700/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: aff a700, fas9000, how to recable the system, how to reassign disks 
summary: Você deve remarcar o armazenamento e confirmar a reatribuição do disco. 
---
= Recable o sistema e reatribuir discos - AFF A700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Continue o procedimento de substituição reativando o armazenamento e confirmando a reatribuição do disco.



== Passo 1: Recable o sistema

Recable as conexões de rede e armazenamento do módulo do controlador.

.Passos
. Recable o módulo do controlador para armazenamento e conexões de rede.
. Verifique se o cabeamento está correto usando https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"]o .
+
.. Baixe e instale o Config Advisor.
.. Insira as informações do sistema de destino e clique em coletar dados.
.. Clique na guia cabeamento e examine a saída. Certifique-se de que todos os compartimentos de disco sejam exibidos e todos os discos apareçam na saída, corrigindo quaisquer problemas de cabeamento encontrados.
.. Verifique outro cabeamento clicando na guia apropriada e, em seguida, examinando a saída do Config Advisor.






== Etapa 2: Reatribuir discos

Se o sistema de storage estiver em um par de HA, a ID do sistema do novo módulo de controladora será automaticamente atribuída aos discos quando o giveback ocorrer no final do procedimento. Você deve confirmar a alteração do ID do sistema quando você inicializar o nó _replacement_ e, em seguida, verificar se a alteração foi implementada.

Este procedimento aplica-se apenas a sistemas que executam o ONTAP em um par de HA.

. Se o nó _replacement_ estiver no modo Manutenção (mostrando o `*>` prompt, saia do modo Manutenção e vá para o prompt Loader: `halt`
. A partir do prompt Loader no nó _replacement_, inicialize o nó, inserindo `y` se for solicitado a substituir o ID do sistema devido a uma incompatibilidade de ID do sistema.``boot_ontap``
. Aguarde até que a `Waiting for giveback...` mensagem seja exibida no console do nó _replacement_ e, em seguida, a partir do nó de integridade, verifique se o novo ID do sistema do parceiro foi atribuído automaticamente: `storage failover show`
+
Na saída do comando, você verá uma mensagem informando que a ID do sistema foi alterada no nó prejudicado, mostrando as IDs antigas e novas corretas. No exemplo a seguir, o node2 foi substituído e tem um novo ID de sistema de 151759706.

+
[listing]
----
node1> `storage failover show`
                                    Takeover
Node              Partner           Possible     State Description
------------      ------------      --------     -------------------------------------
node1             node2             false        System ID changed on partner (Old:
                                                  151759755, New: 151759706), In takeover
node2             node1             -            Waiting for giveback (HA mailboxes)
----
. A partir do nó saudável, verifique se todos os coredumps são salvos:
+
.. Mude para o nível de privilégio avançado: `set -privilege advanced`
+
Você pode responder `Y` quando solicitado a continuar no modo avançado. O prompt do modo avançado é exibido (*>).

.. Salve quaisquer coredumps: `system node run -node _local-node-name_ partner savecore`
.. Aguarde que o comando "avecore" seja concluído antes de emitir o giveback.
+
Você pode inserir o seguinte comando para monitorar o progresso do comando savecore: `system node run -node _local-node-name_ partner savecore -s`

.. Voltar ao nível de privilégio de administrador: `set -privilege admin`


. Se o sistema de storage tiver o Storage ou o volume Encryption configurado, você deverá restaurar a funcionalidade Storage ou volume Encryption usando um dos procedimentos a seguir, dependendo se você estiver usando o gerenciamento de chaves integrado ou externo:
+
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html["Restaurar chaves de criptografia integradas de gerenciamento de chaves"^]
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-external-encryption-keys-93-later-task.html["Restaurar chaves de criptografia de gerenciamento de chaves externas"^]


. Devolver o nó:
+
.. A partir do nó íntegro, devolva o armazenamento do nó substituído: `storage failover giveback -ofnode _replacement_node_name_`
+
O nó _replacement_ recupera seu armazenamento e completa a inicialização.

+
Se você for solicitado a substituir a ID do sistema devido a uma incompatibilidade de ID do sistema, `y` digite .

+

NOTE: Se o giveback for vetado, você pode considerar substituir os vetos.

+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["Encontre o Guia de Configuração de alta disponibilidade para a sua versão do ONTAP 9"]

.. Após a conclusão do giveback, confirme que o par de HA está saudável e que a aquisição é possível: `storage failover show`
+
A saída do `storage failover show` comando não deve incluir a ID do sistema alterada na mensagem do parceiro.



. Verifique se os discos foram atribuídos corretamente: `storage disk show -ownership`
+
Os discos pertencentes ao nó _replacement_ devem mostrar o novo ID do sistema. No exemplo a seguir, os discos de propriedade de node1 agora mostram o novo ID do sistema, 1873775277:

+
[listing]
----
node1> `storage disk show -ownership`

Disk  Aggregate Home  Owner  DR Home  Home ID    Owner ID  DR Home ID Reserver  Pool
----- ------    ----- ------ -------- -------    -------    -------  ---------  ---
1.0.0  aggr0_1  node1 node1  -        1873775277 1873775277  -       1873775277 Pool0
1.0.1  aggr0_1  node1 node1           1873775277 1873775277  -       1873775277 Pool0
.
.
.
----
. Se o sistema estiver em uma configuração MetroCluster, monitore o status do nó: `metrocluster node show`
+
A configuração do MetroCluster leva alguns minutos após a substituição para retornar a um estado normal, quando cada nó mostrará um estado configurado, com espelhamento de DR ativado e um modo normal. O `metrocluster node show -fields node-systemid` comando output exibe o ID do sistema antigo até que a configuração do MetroCluster retorne a um estado normal.

. Se o nó estiver em uma configuração do MetroCluster, dependendo do estado do MetroCluster, verifique se o campo ID inicial do DR mostra o proprietário original do disco se o proprietário original for um nó no local do desastre.
+
Isso é necessário se ambos os seguintes itens forem verdadeiros:

+
** A configuração do MetroCluster está em um estado de switchover.
** O nó _replacement_ é o proprietário atual dos discos no local de desastre.
+
https://docs.netapp.com/us-en/ontap-metrocluster/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html#disk-ownership-changes-during-ha-takeover-and-metrocluster-switchover-in-a-four-node-metrocluster-configuration["Alterações na propriedade do disco durante o takeover de HA e o switchover do MetroCluster em uma configuração de MetroCluster de quatro nós"]



. Se o sistema estiver em uma configuração do MetroCluster, verifique se cada nó está configurado: `metrocluster node show - fields configuration-state`
+
[listing]
----
node1_siteA::> metrocluster node show -fields configuration-state

dr-group-id            cluster node           configuration-state
-----------            ---------------------- -------------- -------------------
1 node1_siteA          node1mcc-001           configured
1 node1_siteA          node1mcc-002           configured
1 node1_siteB          node1mcc-003           configured
1 node1_siteB          node1mcc-004           configured

4 entries were displayed.
----
. Verifique se os volumes esperados estão presentes para cada nó: `vol show -node node-name`
. Se você desativou o controle automático na reinicialização, ative-o a partir do nó de integridade: `storage failover modify -node replacement-node-name -onreboot true`

