---
sidebar: sidebar 
permalink: fas-70-90/install-requirements.html 
keywords: fas70, fas90, install, setup, cautions 
summary: Reveja o equipamento necessário e as precauções de elevação para a sua plataforma e prateleiras. 
---
= Requisitos de instalação - FAS70 e FAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Reveja o equipamento necessário e as precauções de elevação para o seu sistema de armazenamento FAS70 ou FAS90 e prateleiras de armazenamento.



== Equipamento necessário para instalação

Para instalar seu sistema de storage, você precisa dos seguintes equipamentos e ferramentas.

* Acesso a um navegador da Web para configurar o sistema de armazenamento
* Fita de descarga eletrostática (ESD)
* Lanterna
* Computador portátil ou console com conexão USB/serial
* Clipe de papel ou caneta esferográfica de ponta estreita para definir NS224 IDs de prateleira de armazenamento
* Chave de fendas Phillips nº 2




== Precauções de elevação

Os sistemas de armazenamento e as prateleiras são pesados. Tenha cuidado ao levantar e mover estes itens.



=== Peso do sistema de armazenamento

Tome as precauções necessárias ao mover ou elevar o sistema de armazenamento.

Um sistema de armazenamento de FAS70kg ou FAS90kg pode pesar até 62,83 lbs (28,5 kg). Para levantar o sistema, utilize duas pessoas ou um elevador hidráulico.

image::../media/drw_a1k_weight_caution_ieops-1698.svg[Ícone de aviso de elevação FAS70 e FAS90]



=== Peso da prateleira

Tome as precauções necessárias ao mover ou levantar a prateleira.

Uma prateleira de NS224 kg pode pesar até 66,78 lbs (30,29 kg). Para levantar a prateleira, use duas pessoas ou um elevador hidráulico. Mantenha todos os componentes na prateleira (dianteira e traseira) para evitar desequilibrar o peso da prateleira.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 NSM100 precaução de elevação]

Uma prateleira de DS460C kg pode pesar até 260,4 lbs (181,1 kg). Para levantar a prateleira de armazenamento, pode ser necessário um máximo de cinco pessoas ou um elevador hidráulico. Mantenha todos os componentes na prateleira de armazenamento (dianteira e traseira) para evitar o desbalanceamento do peso da prateleira.

image::../media/drw_ds460c_weight_warning_ieops-1932.svg[DS460C precaução de elevação]

.Informações relacionadas
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Informações de segurança e avisos regulamentares"^]


.O que se segue?
Depois de analisar os requisitos de hardware, você link:install-prepare.html["Prepare-se para instalar o sistema de storage FAS70 ou FAS90"].
