---
permalink: fas-70-90/maintain-overview.html 
sidebar: sidebar 
keywords: fas70, fas90 maintenance, maintenance, repairing a1k, repairing fas70, fas90, replace fas70, fas90 components, replace fas70, fas90 components 
summary: Mantenha o hardware do seu sistema de storage FAS70 ou FAS90 para garantir confiabilidade a longo prazo e desempenho ideal. Execute tarefas de manutenção regulares, como a substituição de componentes defeituosos, pois isso ajuda a evitar tempo de inatividade e perda de dados. 
---
= Descrição geral dos procedimentos de manutenção - FAS70 e FAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mantenha o hardware do seu sistema de storage FAS70 ou FAS90 para garantir confiabilidade a longo prazo e desempenho ideal. Execute tarefas de manutenção regulares, como a substituição de componentes defeituosos, pois isso ajuda a evitar tempo de inatividade e perda de dados.

Os procedimentos de manutenção presumem que o sistema FAS70 ou FAS90 já foi implantado como um nó de storage no ambiente ONTAP.



== Componentes do sistema

Para o sistema de armazenamento FAS70 e FAS90, pode executar procedimentos de manutenção nos seguintes componentes.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow.html["Suporte de arranque"]
 a| 
A Mídia de inicialização armazena um conjunto primário e secundário de arquivos de imagem ONTAP que o sistema usa quando ele é inicializado.



 a| 
link:controller-replace-workflow.html["Controlador"]
 a| 
Um controlador consiste em uma placa, firmware e software. Ele controla as unidades e executa o software do sistema operacional ONTAP.



 a| 
link:dimm-replace.html["DIMM"]
 a| 
Um módulo de memória dual in-line (DIMM) é um tipo de memória de computador. Eles são instalados para adicionar memória do sistema a uma placa-mãe controladora.



 a| 
link:fan-replace.html["Ventoinha"]
 a| 
Uma ventoinha arrefece o controlador.



 a| 
link:caching-module-hot-swap.html["Flash Cache"]
 a| 
O Flash Cache acelera o acesso aos dados por meio do armazenamento em cache inteligente em tempo real dos dados do usuário lidos recentemente e dos metadados do NetApp. Ele é eficaz para cargas de trabalho com uso intenso de leitura aleatória, incluindo bancos de dados, e-mail e serviços de arquivos.



 a| 
link:nvram-replace.html["NVRAM"]
 a| 
O NVRAM (memória de acesso aleatório não volátil) é um módulo que permite ao controlador proteger e guardar dados em trânsito se o sistema perder energia. A ID do sistema reside no módulo NVRAM. Quando substituído, o controlador assume a nova ID do sistema a partir do módulo NVRAM de substituição.



 a| 
link:nvdimm-battery-replace.html["Bateria NV"]
 a| 
A bateria NV é responsável por fornecer energia ao módulo NVRAM enquanto os dados em trânsito estão sendo destagidos para memória flash após uma perda de energia.



 a| 
link:io-module-overview.html["Módulo de e/S."]
 a| 
O módulo I/o (módulo de entrada/saída) é um componente de hardware que atua como intermediário entre o controlador e vários dispositivos ou sistemas que precisam trocar dados com o controlador.



 a| 
link:power-supply-replace.html["Fonte de alimentação"]
 a| 
Uma fonte de alimentação fornece uma fonte de alimentação redundante em um controlador.



 a| 
link:rtc-battery-replace.html["Bateria de relógio em tempo real"]
 a| 
Uma bateria de relógio em tempo real preserva as informações de data e hora do sistema se a energia estiver desligada.



 a| 
link:system-management-replace.html["Módulo de gestão do sistema"]
 a| 
O módulo de gerenciamento do sistema fornece a interface entre o controlador e um console ou laptop para fins de manutenção do controlador ou do sistema. O módulo de gestão do sistema contém o suporte de arranque e guarda o número de série do sistema (SSN).

|===