---
permalink: a150/maintain-overview.html 
sidebar: sidebar 
keywords: aff A150 maintenance, maintenance, repairing a150, repairing aff a150, replace aff a150 components, replace aff a150 components 
summary: Realizar manutenção no hardware AFF A150 
---
= Saiba mais sobre a manutenção do seu sistema de storage AFF A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Faça a manutenção do hardware do seu sistema de storage AFF A150 para garantir confiabilidade a longo prazo e desempenho ideal. Execute tarefas de manutenção regulares, como a substituição de componentes defeituosos, para ajudar a evitar tempo de inatividade e perda de dados.



[[boot-media]]
== Suporte de arranque

A Mídia de inicialização armazena um conjunto primário e secundário de arquivos de imagem de inicialização que o sistema usa quando ele é inicializado.



[[chassis]]
== Chassis

O chassi é o gabinete físico que abriga todos os componentes do controlador, como a unidade controladora/CPU, fonte de alimentação e e/S.



[[controller]]
== Controlador

Um controlador consiste em uma placa, firmware e software. Controla as unidades e implementa as funções do ONTAP.



[[dimm]]
== DIMM

Você deve substituir um DIMM (módulo de memória dual in-line) quando houver uma incompatibilidade de memória ou se tiver um DIMM com falha.



[[drive]]
== Condução

Uma unidade é um dispositivo que fornece a Mídia de armazenamento físico para dados.



[[nvem-battery]]
== Bateria NVEM

Uma bateria é incluída com um controlador e preserva os dados em cache se a energia CA falhar.



[[power-supply]]
== Fonte de alimentação

Uma fonte de alimentação fornece uma fonte de alimentação redundante em um compartimento de controladora.



[[real-time-clock-battery]]
== Bateria do relógio em tempo real

Uma bateria de relógio em tempo real preserva as informações de data e hora do sistema se a energia estiver desligada.
