---
permalink: a150/overview.html 
sidebar: sidebar 
keywords: AFF A150 specifications, AFF A150 specs, NetApp AFF A150, AFF A150 hardware 
summary: Especificações principais para o sistema de armazenamento AFF A150 
---
= Especificações principais do AFF A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A seguir estão algumas especificações selecionadas para o AFF A150.  Visita https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) para uma lista completa das especificações do AFF A150 .  Esta página reflete um único par de alta disponibilidade.



=== Especificações principais do AFF A150

Configuração da plataforma: AFF A150 UTA2 Par de chassis único HA

Capacidade máxima de matéria-prima: 0,5472 PB

Memória: 64.0000 GB

Fator de forma: chassi 2U com 2 controladores HA e 24 slots de unidade

Versão ONTAP : b_startONTAP: 9.16.1P2b_end

Slots de expansão PCIe:

Versão mínima do ONTAP : ONTAP 9.10.1P12



=== Máximos de Escalabilidade

|===


| Tipo | Pares HA | Capacidade bruta | Memória Máxima 


| NAS | 12 | 6,6 PB / 5,8 PiB | 768 GB 


| SAN | 6 | 3,3 PB / 2,9 PiB | 384 GB 


| Par HA |  | 0,5 PB / 0,5 PiB | 64,0000 
|===


=== IO



==== IO integrado

|===


| Protocolo | Portos 


| Ethernet 10 Gbps | 12 


| FC 16 Gbps | 8 


| SAS 12 Gbps | 4 
|===


==== Total de IO

|===


| Protocolo | Portos 


| Ethernet 10 Gbps | 12 


| FC 16 Gbps | 8 


| SAS 12 Gbps | 4 
|===


==== Portas de Gestão

|===


| Protocolo | Portos 


| Ethernet 1 Gbps | 2 


| RS-232 115 Kbps | 4 


| USB 12 Mbps | 2 
|===


=== Rede de armazenamento suportada

CIFS; FC; FCoE; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NVMe/TCP; S3; S3 com NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Especificações do ambiente do sistema

* Potência típica: 1209 BTU/h
* Pior cenário de potência: 1676 BTU/h
* Peso: 60,8 lb<br/>27,6 kg
* Altura: 2U
* Largura: 19” compatível com rack IEC (17,6” 44,7 cm)
* Profundidade: 19,0”<br/>(24,1” com suporte para gerenciamento de cabos)
* Temperatura/Altitude/Umidade de operação: 5°C a 45°C<br/>41°F a <br/>113°F) a<br/><= 3048m<br/><= 10000 pés) de altitude; 8% a 90%<br/>de umidade relativa, sem condensação
* Temperatura/Umidade fora de operação: -40°C a 70°C (-40°F a 158°F) até 12192m (40000 pés)<br/>10% a 95% de umidade relativa, sem condensação, no recipiente original
* Ruído acústico: Potência sonora declarada (LwAd): 6,9;<br/>Pressão sonora (LpAm) (posições de observação): 51,0 dB




=== Conformidade

* Certificações EMC/EMI: AMCA, FCC, ICES, KC, Marrocos, VCCI
* Certificações de segurança: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificações Segurança/EMC/EMI: EAC, UKRSEPRO
* Certificações Segurança/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normas EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normas de segurança: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilidade

Controlador de gerenciamento de placa base baseado em Ethernet (BMC) e interface de gerenciamento ONTAP ; Controladores redundantes de troca a quente; Fontes de alimentação redundantes de troca a quente; Gerenciamento SAS em banda por meio de conexões SAS; [//] 2025-10-15 ontap-systems-internal/issues/1357
