---
permalink: asa-c400/bootmedia-recovery-image-boot.html 
sidebar: sidebar 
keywords: asa c400, asa, c400, procedure, boot, impair, controller, recovery, image, system, two-node, metrocluster, configuration, boot the recovery image 
summary: O procedimento para inicializar o controlador prejudicado a partir da imagem de recuperação depende se o sistema está em uma configuração de MetroCluster de dois nós. 
---
= Inicie a imagem de recuperação - ASA C400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de instalar o novo dispositivo multimédia de arranque no seu sistema, pode arrancar a imagem de recuperação a partir de uma unidade USB e restaurar a configuração a partir do nó do parceiro.

.Passos
. A partir do prompt Loader, inicialize a imagem de recuperação da unidade flash USB: `boot_recovery`
+
A imagem é transferida da unidade flash USB.

. Quando solicitado, insira o nome da imagem ou aceite a imagem padrão exibida dentro dos colchetes na tela.
. Restaure o sistema de ficheiros var:
+
[role="tabbed-block"]
====
.Opção 1: ONTAP 9.16,0 ou anterior
--
.. No controlador para deficientes, prima `Y` quando vir `Do you want to restore the backup configuration now?`
.. Se solicitado no controlador prejudicado, pressione `Y` para substituir _/etc/ssh/ssh_host_ecdsa_key_.
.. No controlador de parceiro saudável, defina o controlador prejudicado para nível de privilégio avançado: `set -privilege advanced`.
.. No controlador do parceiro saudável, execute o comando Restore backup: `system node restore-backup -node local -target-address impaired_node_IP_address` .
+
*NOTA:* se você vir qualquer mensagem que não seja uma restauração bem-sucedida, entre em Contato https://support.netapp.com["Suporte à NetApp"]com .

.. No controlador do parceiro saudável, devolva o controlador afetado ao nível de administração: `set -privilege admin`.
.. No controlador para deficientes, prima `Y` quando vir `Was the restore backup procedure successful?`.
.. No controlador para deficientes, prima `Y` quando vir `...would you like to use this restored copy now?`.
.. No controlador desativado, `Y` prima quando for solicitado que reinicie o controlador desativado e prima `ctrl-c` para aceder ao Menu de arranque.
.. Se o sistema não usar criptografia, selecione _opção 1 Inicialização normal._, caso contrário, vá para link:bootmedia-encryption-restore.html["Restaure a criptografia"].


--
.Opção 2: ONTAP 9.16,1 ou posterior
--
.. No controlador afetado, prima `Y` quando for solicitado que restaure a configuração de cópia de segurança.
+
Depois que o procedimento de restauração for bem-sucedido, essa mensagem será exibida no console - `syncflash_partner: Restore from partner complete`.

.. No controlador desativado, `Y` prima quando solicitado para confirmar se a cópia de segurança de restauro foi bem sucedida.
.. No controlador prejudicado, `Y` pressione quando solicitado a usar a configuração restaurada.
.. No controlador prejudicado, `Y` pressione quando solicitado a reinicializar o nó.
.. No controlador desativado, `Y` prima quando for solicitado que reinicie o controlador desativado e prima `ctrl-c` para aceder ao Menu de arranque.
.. Se o sistema não usar criptografia, selecione _opção 1 Inicialização normal._, caso contrário, vá para link:bootmedia-encryption-restore.html["Restaure a criptografia"].


--
====


. Conete o cabo do console ao controlador do parceiro.
. Devolva o controlador usando o `storage failover giveback -fromnode local` comando.
. Restaure o giveback automático se você o desativou usando o `storage failover modify -node local -auto-giveback true` comando.
. Se o AutoSupport estiver ativado, restaure/dessuprimir a criação automática de casos usando o `system node autosupport invoke -node * -type all -message MAINT=END` comando.
+
*NOTA:* se o processo falhar, entre em Contato https://support.netapp.com["Suporte à NetApp"]com .


