---
permalink: asa-c400/controller-replace-requirements.html 
sidebar: sidebar 
keywords: asa c400, prerequisite, replace the controller module 
summary: Antes de substituir o controlador do seu ASA C400, verifique se todos os outros componentes do sistema estão funcionando corretamente, certifique-se de que possui o controlador de substituição correto e salve a saída do console do controlador em um arquivo de log. 
---
= Requisitos para substituir o controlador - ASA C400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de substituir o controlador do seu ASA C400, verifique se todos os outros componentes do sistema estão funcionando corretamente, certifique-se de que possui o controlador de substituição correto e salve a saída do console do controlador em um arquivo de log.

Reveja os requisitos para substituir o módulo do controlador.

[NOTE]
====
NetApp recomenda fortemente que você habilite o registro de logs no console nos dispositivos que estiver utilizando e execute as seguintes ações ao realizar este procedimento:

* Deixe AutoSupport ativado durante a sua manutenção. Isso permite que o suporte da NetApp receba informações de diagnóstico caso ocorram problemas.
* Habilite o registro de sessão para todas as sessões da CLI. Isso cria um registro completo de todos os comandos e da saída do sistema durante a atividade de manutenção. Para obter orientações sobre como habilitar o registro de sessão, consulte  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Como configurar o PuTTY para obter conectividade ideal com sistemas ONTAP"^].


====
* Todas as gavetas de unidades devem estar funcionando corretamente.
* O controlador em bom estado deve ser capaz de assumir o controle do controlador que está sendo substituído (referido neste procedimento como controlador com defeito).
* Não utilize este procedimento para atualizações de controladores.  Consulte https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["Escolha o procedimento de atualização do hardware do controlador"] para orientação.
* Se o seu sistema estiver em uma configuração MetroCluster , revise https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["Escolher o procedimento de recuperação correto"] para determinar se este procedimento deve ser utilizado.
* Substitua o componente defeituoso pela unidade substituível em campo (FRU) que você recebeu da NetApp.
* Substitua o módulo controlador por um módulo controlador do mesmo modelo.  Não é possível atualizar o sistema substituindo o módulo controlador.
* Não é possível trocar unidades de disco ou gavetas de unidades como parte deste procedimento.
* Neste procedimento, o dispositivo de inicialização é movido do controlador prejudicado para o controlador de substituição, de modo que o controlador de substituição será inicializado na mesma versão do ONTAP que o módulo do controlador antigo.
* Compreenda a terminologia do controlador utilizada neste procedimento:
+
** O controlador _com defeito_ é o controlador que está sendo substituído.
** O controlador _de substituição_ é o novo controlador que substitui o controlador com defeito.
** O controlador _Healthy_ é o controlador sobrevivente.


* Use  `security key-manager onboard show-key-store` para verificar se o Onboard Key Manager (OKM) está configurado. Caso esteja, recupere a senha de todo o cluster usando  https://docs.netapp.com/us-en/ontap-cli/security-key-manager-onboard-show-backup.html["security key-manager onboard show-backup"] ou entre em contato com o NetApp Support antes de iniciar este procedimento.


.O que se segue?
Após analisar os requisitos para substituir o seu ASA C400, você precisa link:controller-replace-shutdown.html["desligue o controlador desativado"].
