---
permalink: asa-r2-70-90/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa r2 a70, a90, replace the boot media 
summary: Saiba mais sobre os requisitos para substituir a Mídia de inicialização. 
---
= Requisitos de substituição do suporte de arranque - ASA A70 e ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de substituir o suporte de arranque, certifique-se de que verifica os seguintes requisitos.

* Tem de substituir o suporte de arranque com falha por um suporte de arranque de substituição que recebeu do NetApp.
* Não deve haver portas do cluster defeituosas no controlador prejudicado.
* Determine se o OKM (Onboard Key Manager) ou o EKM (Eternal Key Manager) estão configurados usando um dos seguintes métodos:
+
** Você pode perguntar ao administrador do sistema se OKM ou EKM estão ativados.
** Para verificar se o OKM está ativado, você pode usar o `security key-manager onboard show`.
** Para verificar se o EKM está ativado, pode utilizar o `security key-manager external show`.


* Para OKM, você precisa do conteúdo do arquivo de senha OKM.
* Para EKM, você precisa de cópias dos seguintes arquivos do nó do parceiro:
+
** arquivo /cfcard/kmip/servers.cfg.
** arquivo /cfcard/kmip/certs/client.crt.
** arquivo /cfcard/kmip/certs/client.key.
** Arquivo /cfcard/kmip/certs/CA.pem.




.O que vem a seguir
Depois de analisar os requisitos do suporte de arranque, pode link:bootmedia-shutdown-bmr.html["desligue o controlador desativado"].
