---
permalink: asa-r2-70-90/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa r2 a70, a90, replace the boot media 
summary: Antes de substituir o suporte de arranque no sistema ASA A70 ou A90, certifique-se de que cumpre os requisitos necessários para uma substituição bem-sucedida. 
---
= Requisitos para substituir a mídia de inicialização - ASA A70 e ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de substituir a mídia de inicialização no seu sistema ASA A70 ou ASA A90, certifique-se de atender aos requisitos necessários para uma substituição bem-sucedida. Isso inclui verificar se você possui a mídia de inicialização de substituição correta, confirmar se as portas do cluster no controlador danificado estão funcionando corretamente e determinar se o Gerenciador de Chaves Onboard (OKM) ou o Gerenciador de Chaves Externas (EKM) está habilitado.

Reveja os seguintes requisitos.

* Tem de substituir o suporte de arranque com falha por um suporte de arranque de substituição que recebeu do NetApp.
* As portas do cluster são usadas para comunicação entre os dois controladores durante o processo de recuperação de inicialização automatizada. Certifique-se de que as portas do cluster no controlador afetado estejam funcionando corretamente.
* Para o OKM, você precisa da senha de todo o cluster e também dos dados de backup.
* Para EKM, você precisa de cópias dos seguintes arquivos do nó do parceiro:
+
** /cfcard/kmip/servers.cfg
** /cfcard/kmip/certs/client.crt
** /cfcard/kmip/certs/client.key
** /cfcard/kmip/certs/CA.pem


* É fundamental aplicar os comandos ao controlador correto ao substituir a mídia de inicialização danificada:
+
** O _controlador danificado_ é o controlador no qual você está executando a manutenção.
** O _controlador saudável_ é o parceiro HA do controlador prejudicado.




.O que vem a seguir
Depois de analisar os requisitos do suporte de arranque, pode link:bootmedia-shutdown-bmr.html["desligue o controlador"].
