---
permalink: asa-r2-70-90/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: asa r2 a70, asa r2 a90, verify and set HA state, complete the replacement process 
summary: Reinicie os controladores, verifique a integridade do sistema e devolva a peça com falha ao NetApp para concluir a etapa final no fluxo de trabalho de substituição do chassi do ASA A70 e do ASA A90. 
---
= Complete a substituição do chassi - ASA A70 e ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Reinicie os controladores, verifique a integridade do sistema e devolva a peça com falha ao NetApp para concluir a etapa final no procedimento de substituição do chassi do ASA A70 e do ASA A90.



== Passo 1: Inicialize os controladores e devolva os controladores

Após a reinicialização dos controladores, inicialize o ONTAP e devolva os controladores.

.Passos
. Verifique a saída da consola:
+
.. Se o controlador inicializar no prompt Loader, reinicie o controlador com o `boot_ontap` comando.
.. Se o console for exibido `waiting for giveback` após a reinicialização, faça login no controlador parceiro e verifique se o controlador substituído está pronto para giveback com o `storage failover show` comando.


. Execute a giveback:
+
.. Conete o cabo do console ao controlador do parceiro.
.. Devolva o controlador com o `storage failover giveback -fromnode local` comando.






== Etapa 2: Verificar a integridade do sistema de armazenamento

Depois que o controlador devolver o armazenamento, você deve verificar a integridade geral com https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"].

.Passos
. Após a conclusão do giveback, execute o Active IQ Config Advisor para verificar a integridade do sistema de storage.
. Corrija quaisquer problemas que você encontrar.




== Passo 3: Devolva a peça com falha ao NetApp

Devolva a peça com falha ao NetApp, conforme descrito nas instruções de RMA fornecidas com o kit. Consulte a https://mysupport.netapp.com/site/info/rma["Devolução de peças e substituições"] página para obter mais informações.
