---
permalink: asa-r2-70-90/chassis-replace-prepare.html 
sidebar: sidebar 
keywords: asa r2 a70, asa r2 a90, prepare to replace the chassis 
summary: Prepare-se para substituir o chassi com deficiência no sistema ASA A70 ou ASA A90 identificando o chassi com deficiência, verificando os componentes de substituição e rotulando os cabos e os módulos do controlador. 
---
= Prepare-se para substituir o chassis - ASA A70 e ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prepare-se para substituir o chassi danificado em seu sistema ASA A70 ou ASA A90, identificando o chassi danificado, verificando os componentes de substituição e etiquetando os cabos e módulos de controle.

.Passos
. Conete-se à porta do console serial à interface e monitore o sistema.
. Ligue o LED de localização do controlador:
+
.. Use o `system controller location-led show` Comando para exibir o estado atual do LED de localização.
.. Ligue o LED de localização:
+
`system controller location-led modify -node _node1_ -state on`

+
O LED de localização permanece aceso durante 30 minutos.



. Antes de abrir a embalagem, examine o rótulo e verifique o seguinte:
+
** Número da peça do componente
** Descrição da peça
** Quantidade na caixa


. Retire o conteúdo da embalagem e guarde-a para devolver o componente com defeito à NetApp.
. Identifique todos os cabos conectados ao sistema de armazenamento.  Isso garante a correta recablagem posteriormente neste procedimento.
. Conecte-se com a terra, caso ainda não esteja conectado.


.O que se segue?
Após se preparar para substituir o chassi ASA A70 ou ASA A90,link:chassis-replace-shutdown.html["desligue os controladores"] .
