---
permalink: asa-r2-70-90/io-module-overview.html 
sidebar: sidebar 
keywords: ASA A90,  ASA A70, replace io module 
summary: Os sistemas ASA A70 e ASA A90 oferecem flexibilidade na expansão ou substituição de módulos de e/S para melhorar a conetividade e o desempenho da rede. Adicionar ou substituir um módulo de e/S é essencial ao atualizar recursos de rede ou endereçar um módulo com falha. 
---
= Descrição geral de adicionar e substituir um módulo de e/S - ASA A70 e ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os sistemas ASA A70 e ASA A90 oferecem flexibilidade na expansão ou substituição de módulos de e/S para melhorar a conetividade e o desempenho da rede. Adicionar ou substituir um módulo de e/S é essencial ao atualizar recursos de rede ou endereçar um módulo com falha.

Você pode substituir um módulo de e/S com falha em seu sistema de storage ASA A70 ou ASA A90 pelo mesmo tipo de módulo de e/S ou por um tipo diferente de módulo de e/S. Você também pode adicionar um módulo de e/S a um sistema com slots vazios.

* link:io-module-add.html["Adicione um módulo de e/S."]
+
Adicionar módulos adicionais pode melhorar a redundância, ajudando a garantir que o sistema permaneça operacional mesmo que um módulo falhe.

* link:io-module-hotswap.html["Substituição a quente de um módulo de E/S"]
+
É possível realizar a substituição a quente de determinados módulos de E/S por um módulo de E/S equivalente para restaurar o sistema de storage ao seu estado operacional ideal. A substituição a quente é feita sem a necessidade de realizar uma tomada manual.

+
Para usar este procedimento, seu sistema de storage deve estar executando ONTAP 9.18.1.

* link:io-module-replace.html["Substitua um módulo de e/S."]
+
A substituição de um módulo de e/S com falha pode restaurar o sistema ao seu estado de funcionamento ideal.



.Numeração de slots de e/S.
Os slots de e/S nos controladores ASA A70 e ASA A90 estão numerados de 1 a 11, como mostrado na ilustração a seguir.

image::../media/drw_a1K_back_slots_labeled_ieops-2162.svg[Numeração de slots em controladores ASA A70 e AFF A90]
