---
permalink: asa-r2-70-90/io-module-overview.html 
sidebar: sidebar 
keywords: ASA A90,  ASA A70, replace io module 
summary: Os sistemas ASA A70 e ASA A90 oferecem flexibilidade na expansão ou substituição de módulos de e/S para melhorar a conetividade e o desempenho da rede. Adicionar ou substituir um módulo de e/S é essencial ao atualizar recursos de rede ou endereçar um módulo com falha. 
---
= Descrição geral do módulo de e/S adicional e/S - ASA A70 e ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os sistemas ASA A70 e ASA A90 oferecem flexibilidade na expansão ou substituição de módulos de e/S para melhorar a conetividade e o desempenho da rede. Adicionar ou substituir um módulo de e/S é essencial ao atualizar recursos de rede ou endereçar um módulo com falha.

Você pode substituir um módulo de e/S com falha em seu sistema de storage ASA A70 ou ASA A90 pelo mesmo tipo de módulo de e/S ou por um tipo diferente de módulo de e/S. Você também pode adicionar um módulo de e/S a um sistema com slots vazios.

* link:io-module-add.html["Adicione um módulo de e/S."]
+
Adicionar módulos adicionais pode melhorar a redundância, ajudando a garantir que o sistema permaneça operacional mesmo que um módulo falhe.

* link:io-module-replace.html["Substitua um módulo de e/S."]
+
A substituição de um módulo de e/S com falha pode restaurar o sistema ao seu estado de funcionamento ideal.


