---
permalink: asa-r2-70-90/maintain-overview.html 
sidebar: sidebar 
keywords: asa r2 a70 asa r2 a90 maintenance, maintenance, repairing asa r2 a70 asa r2 a90, repairing a70 asa r2 a90, replace a70 asa r2 a90 components 
summary: Mantenha o hardware ASA R2 A70, ASA R2 A90 
---
= Descrição geral dos procedimentos de manutenção - ASA A70 e ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mantenha o hardware dos seus sistemas de storage ASA A70 e ASA A90 para garantir confiabilidade a longo prazo e desempenho ideal. Execute tarefas de manutenção regulares, como a substituição de componentes defeituosos, pois isso ajuda a evitar tempo de inatividade e perda de dados.

Os procedimentos de manutenção pressupõem que os sistemas ASA A70 e ASA A90 já foram implantados como um nó de storage no ambiente ONTAP.



== Componentes do sistema

Para os sistemas de storage ASA A70 e ASA A90, você pode executar procedimentos de manutenção nos seguintes componentes.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["Suporte de arranque"]
 a| 
A mídia de inicialização armazena um conjunto primário e secundário de arquivos de imagem ONTAP que o sistema de armazenamento usa para inicializar.  Durante a recuperação automatizada, o sistema recupera a imagem de inicialização do nó parceiro e executa automaticamente a opção de menu de inicialização apropriada para instalar a imagem na mídia de inicialização de substituição.



 a| 
link:chassis-replace-workflow.html["Chassis"]
 a| 
O chassi é o gabinete físico que abriga todos os componentes do controlador, como a unidade controladora/CPU, fonte de alimentação e e/S.



 a| 
link:controller-replace-workflow.html["Controlador"]
 a| 
Um controlador consiste em uma placa, firmware e software. Ele controla o storage, as placas de e/S e executa o software do sistema operacional ONTAP.



 a| 
link:dimm-replace.html["DIMM"]
 a| 
Um módulo de memória dual in-line (DIMM) é um tipo de memória de computador. Eles são instalados para adicionar memória do sistema a uma placa-mãe controladora.



 a| 
link:drive-replace.html["Condução"]
 a| 
Uma unidade é um dispositivo que fornece o armazenamento físico necessário para os dados.



 a| 
link:fan-swap-out.html["Ventoinha"]
 a| 
Uma ventoinha arrefece o controlador.



 a| 
link:nvram-replace.html["NVRAM"]
 a| 
O NVRAM (memória de acesso aleatório não volátil) é um módulo que permite ao controlador proteger e guardar dados em trânsito se o sistema perder energia. A ID do sistema reside no módulo NVRAM. Quando substituído, o controlador assume a nova ID do sistema a partir do módulo NVRAM de substituição.



 a| 
link:nvdimm-battery-replace.html["Bateria NV"]
 a| 
A bateria NV é responsável por fornecer energia ao módulo NVRAM enquanto os dados em trânsito estão sendo destagidos para memória flash após uma perda de energia.



 a| 
link:io-module-overview.html["Módulo de e/S."]
 a| 
O módulo I/o (módulo de entrada/saída) é um componente de hardware que atua como intermediário entre o controlador e vários dispositivos ou sistemas que precisam trocar dados com o controlador.



 a| 
link:power-supply-replace.html["Fonte de alimentação"]
 a| 
Uma fonte de alimentação fornece uma fonte de alimentação redundante em um controlador.



 a| 
link:rtc-battery-replace.html["Bateria de relógio em tempo real"]
 a| 
Uma bateria de relógio em tempo real preserva as informações de data e hora do sistema se a energia estiver desligada.



 a| 
link:system-management-replace.html["Módulo de gestão do sistema"]
 a| 
O módulo Gerenciamento do sistema fornece a interface entre o controlador e um console ou laptop para fins de manutenção do controlador ou do sistema. O módulo de gestão do sistema contém o suporte de arranque e guarda o número de série do sistema (SSN).

|===