---
permalink: c800/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff c800, verify and set HA state, complete the replacement process 
summary: Você precisa verificar o estado de HA do chassi e devolver a peça com falha à NetApp, conforme descrito nas instruções de RMA fornecidas com o kit. 
---
= Conclua o processo de restauração e substituição - AFF C800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Reinicie os controladores, verifique a integridade do sistema e devolva a peça com defeito à NetApp para concluir a etapa final do procedimento de substituição do chassi AFF C800 .



== Etapa 1: Verifique e defina o estado HA do chassi

.Passos
. No modo de manutenção, a partir de qualquer um dos módulos do controlador, apresentar o estado HA do módulo do controlador local e do chassis: `ha-config show`
+
O estado HA deve ser o mesmo para todos os componentes.

. Se o estado do sistema apresentado para o chassis não corresponder à configuração do sistema:
+
.. Defina o estado HA para o chassis: `ha-config modify chassis _HA-state_`
+
O valor para HA-State pode ser um dos seguintes:

+
*** `ha`
*** `mcc`
*** `mccip`
*** `non-ha`


.. Confirme se a definição foi alterada: `ha-config show`


. Se você ainda não o fez, recable o resto de seu sistema.
. Volte a instalar a moldura na parte frontal do sistema.




== Etapa 2: Verificar a integridade do sistema de armazenamento

Após a conclusão da devolução do controlador, verifique a integridade do sistema usando https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"] .  Corrija quaisquer problemas encontrados.



== Passo 3: Devolva a peça com falha ao NetApp

Devolva a peça com falha ao NetApp, conforme descrito nas instruções de RMA fornecidas com o kit. Consulte a https://mysupport.netapp.com/site/info/rma["Devolução de peças e substituições"] página para obter mais informações.
