---
permalink: asa-r2-a20-30-50/bootmedia-overview-bmr.html 
sidebar: sidebar 
keywords: asa a20, asa a30, asa a50, overview, automatic recovery, boot media 
summary: Saiba mais sobre o método automatizado para substituir a Mídia de inicialização. 
---
= Visão geral da recuperação de Mídia de inicialização - ASA A20, ASA A30 e ASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A recuperação de Mídia de inicialização para o sistema de armazenamento ASA A20, ASA A30 ou ASA A50 usa a imagem de inicialização do nó do parceiro e executa automaticamente a opção de menu de inicialização apropriada para instalar a imagem de inicialização na Mídia de inicialização de substituição.

Quando você encontrar mensagens de erro de inicialização semelhantes às mostradas abaixo, você precisa substituir a Mídia de inicialização e restaurar a imagem ONTAP do nó do parceiro.

....
Can't find primary boot device u0a.0
Can't find backup boot device u0a.1
ACPI RSDP Found at 0x777fe014

Starting AUTOBOOT press Ctrl-C to abort...
Could not load fat://boot0/X86_64/freebsd/image1/kernel: Device not found

ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/Linux/image1/vmlinuz (boot0, fat)
ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/freebsd/image1/kernel (boot0, fat)

Autoboot of PRIMARY image failed. Device not found (-6)
LOADER-A>
....