---
permalink: asa-r2-a20-30-50/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: aff a20, aff a30, aff a50, replace the boot media 
summary: Saiba mais sobre os requisitos para substituir a Mídia de inicialização. 
---
= Requisitos - AFF A20, AFF A30 e AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de substituir a Mídia de inicialização, verifique os seguintes requisitos e considerações.



== Requisitos

* Você deve substituir o componente com falha por um componente FRU de substituição da mesma capacidade que recebeu do NetApp.
* A porta e0S (chave de e0M mm) no controlador desativado não pode estar avariada.
+
A porta e0S é usada para recuperação automática de inicialização.

* Determine se o OKM (Onboard Key Manager) ou o EKM (Eternal Key Manager) estão configurados usando um dos seguintes métodos:
+
** Você pode perguntar ao administrador do sistema se OKM ou EKM estão ativados.
** Para verificar se o OKM está ativado, você pode usar o `security key-manager onboard show`.
** Para verificar se o EKM está ativado, pode utilizar o `security key-manager external show`.


* Para OKM, você precisa do conteúdo do arquivo de senha OKM.
* Para EKM, você precisa de cópias dos seguintes arquivos do nó do parceiro:
+
** arquivo /cfcard/kmip/servers.cfg.
** arquivo /cfcard/kmip/certs/client.crt.
** arquivo /cfcard/kmip/certs/client.key.
** Arquivo /cfcard/kmip/certs/CA.pem.






== Considerações

* É importante que você aplique os comandos nestas etapas no controlador correto:
+
** O controlador _prejudicado_ é o controlador no qual você está realizando a manutenção.
** O controlador _Healthy_ é o parceiro de HA do controlador prejudicado.


* Se necessário, você pode ligar os LEDs de localização do chassi da plataforma (azul) para ajudar a localizar fisicamente a plataforma afetada. Faça login no BMC usando SSH e digite o `system location-led _on_` comando.
+
Um chassi de plataforma tem três LEDs de localização: Um no painel de exibição do operador e um em cada controlador. Os LEDs de localização permanecem acesos durante 30 minutos.

+
Você pode desativá-los digitando o `system location-led _off_` comando. Se não tiver a certeza se os LEDs estão ligados ou desligados, pode verificar o seu estado introduzindo o `system location-led show` comando.



.O que vem a seguir
Depois de analisar os requisitos do suporte de arranque, link:bootmedia-shutdown-bmr.html["desligue o controlador desativado"].
