---
permalink: asa-r2-a20-30-50/chassis-replace-requirements.html 
sidebar: sidebar 
keywords: asa a20, asa a30, asa a50, replace the chassis 
summary: Substituir um chassis com deficiência pelo novo chassis do mesmo modelo que o chassis com deficiência. 
---
= Requisitos de substituição do chassis - ASA A20, ASA A30 e ASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de substituir o chassi, verifique os seguintes requisitos e considerações.



== Requisitos

* O chassis de substituição tem de ser o mesmo modelo que o chassis com deficiência. Este procedimento é para uma substituição similar, não para uma atualização.
* Todos os outros componentes do sistema de armazenamento têm de estar a funcionar corretamente; caso contrário, tem de contactar https://mysupport.netapp.com/site/global/dashboard["Suporte à NetApp"] antes de prosseguir com este procedimento.




== Considerações

* *O procedimento de substituição do chassis é disruptivo.* Para um cluster de dois nós, você terá uma interrupção de serviço completa e uma interrupção parcial em um cluster de vários nós.
* Você pode usar o procedimento de substituição de chassi com todas as versões do ONTAP suportadas pelo sistema de storage.
* O procedimento de substituição do chassi é escrito com a suposição de que você está movendo o painel frontal, as unidades, quaisquer lacunas de unidade e os controladores para o novo chassi.
* Se necessário, você pode ligar os LEDs de localização do sistema de armazenamento (azul) para ajudar a localizar fisicamente o sistema de armazenamento afetado. Faça login no BMC usando SSH e digite o `system location-led _on_` comando.
+
Um sistema de armazenamento tem três LEDs de localização: Um no painel de visualização do operador e um em cada controlador. Os LEDs de localização permanecem acesos durante 30 minutos.

+
Você pode desativá-los digitando o `system location-led _off_` comando. Se não tiver a certeza se os LEDs estão ligados ou desligados, pode verificar o seu estado introduzindo o `system location-led show` comando.


