---
permalink: asa-r2-a20-30-50/controller-replace-requirements.html 
sidebar: sidebar 
keywords: asa a20, asa a30, asa a50, prerequisite, replace the controller module 
summary: Antes de substituir o controlador no seu sistema de armazenamento ASA A20, ASA A30 ou ASA A50, certifique-se de atender aos requisitos necessários para uma substituição bem-sucedida.  Isso inclui verificar se todos os outros componentes do sistema estão funcionando corretamente, verificar se você tem o controlador de substituição correto e salvar a saída do console do controlador em um arquivo de log de texto. 
---
= Requisitos para substituir o controlador - ASA A20, ASA A30 e ASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de substituir o controlador no seu sistema de armazenamento ASA A20, ASA A30 ou ASA A50, certifique-se de atender aos requisitos necessários para uma substituição bem-sucedida.  Isso inclui verificar se todos os outros componentes do sistema estão funcionando corretamente, verificar se você tem o controlador de substituição correto e salvar a saída do console do controlador em um arquivo de log de texto.

Você deve rever os requisitos e considerações para o procedimento de substituição do controlador.

[NOTE]
====
NetApp recomenda fortemente que você habilite o registro de logs no console nos dispositivos que estiver utilizando e execute as seguintes ações ao realizar este procedimento:

* Deixe AutoSupport ativado durante a sua manutenção. Isso permite que o suporte da NetApp receba informações de diagnóstico caso ocorram problemas.
* Habilite o registro de sessão para todas as sessões da CLI. Isso cria um registro completo de todos os comandos e da saída do sistema durante a atividade de manutenção. Para obter orientações sobre como habilitar o registro de sessão, consulte  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Como configurar o PuTTY para obter conectividade ideal com sistemas ONTAP"^].


====


== Requisitos

* Todas as prateleiras devem estar funcionando corretamente.
* O controlador saudável deve ser capaz de assumir o controlador que está a ser substituído (referido neste procedimento como ""controlador deficiente"").
* Você deve substituir um controlador por um controlador do mesmo tipo de modelo. Você não pode atualizar seu sistema apenas substituindo o controlador.
* Não é possível alterar nenhuma unidade ou compartimentos como parte deste procedimento.




== Considerações

* É importante aplicar os comandos neste procedimento ao controlador correto:
+
** O controlador _prejudicado_ é o controlador que está sendo substituído.
** O controlador _replacement_ é o novo controlador que está substituindo o controlador prejudicado.
** O controlador _Healthy_ é o controlador sobrevivente.




.O que se segue?
Depois de analisar os requisitos para substituir o controlador afetado, é link:controller-replace-shutdown.html["desligue o controlador desativado"]necessário .
