---
permalink: asa-r2-a20-30-50/controller-replace-restore-system-rma.html 
sidebar: sidebar 
keywords: asa a20, asa a30, asa a50, how to restore NetApp Storage Encryption, how to complete the replacement process 
summary: Para restaurar o sistema para a operação completa, você deve verificar os LIfs, verificar a integridade do cluster e retornar a peça com falha ao NetApp. 
---
= Substituição completa do controlador - ASA A20, ASA A30 e ASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para restaurar o sistema de storage para a operação completa, você deve verificar os LIFs, verificar a integridade do cluster e retornar a peça com falha ao NetApp.



== Etapa 1: Verificar LIFs e verificar a integridade do cluster

Antes de retornar o nó de substituição ao serviço, verifique se as interfaces lógicas estão em suas portas iniciais, verifique a integridade do cluster e redefina a giveback automática.

.Passos
. Verifique se as interfaces lógicas estão relatando para o servidor doméstico e as portas: `network interface show -is-home false`
+
Se alguma interface lógica for listada como falsa, reverta-as para suas portas iniciais: `network interface revert -vserver * -lif *`

. Verifique a integridade do cluster. Consulte o https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["Como realizar uma verificação de integridade do cluster com um script no ONTAP"^] artigo da KB para obter mais informações.
. Se a giveback automática foi desativada, reative-a: `storage failover modify -node local -auto-giveback true`




== Passo 2: Devolva a peça com falha ao NetApp

Devolva a peça com falha ao NetApp, conforme descrito nas instruções de RMA fornecidas com o kit. Consulte a https://mysupport.netapp.com/site/info/rma["Devolução de peças e substituições"] página para obter mais informações.
