---
permalink: asa-r2-a20-30-50/maintain-overview.html 
sidebar: sidebar 
keywords: asa a20 asa a30 asa a50 maintenance, maintenance, repairing a20 asa a30 asa a50, replace a20 asa a30 asa a50 components 
summary: Faça a manutenção do hardware do seu sistema de armazenamento ASA A20, ASA A30 ou ASA A50 para garantir confiabilidade a longo prazo e desempenho ideal. Realize tarefas de manutenção regulares, como a substituição de componentes defeituosos, pois isso ajuda a evitar tempo de inatividade e perda de dados. 
---
= Visão geral da manutenção de hardware - ASA A20, ASA A30 e ASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Faça a manutenção do hardware do seu sistema de armazenamento ASA A20, ASA A30 ou ASA A50 para garantir confiabilidade a longo prazo e desempenho ideal. Realize tarefas de manutenção regulares, como a substituição de componentes defeituosos, pois isso ajuda a evitar tempo de inatividade e perda de dados.

Os procedimentos de manutenção presumem que os sistemas ASA A20, ASA A30 e ASA A50 já foram implantados como nós de storage no ambiente ONTAP.



== Componentes do sistema

Para os sistemas de storage ASA A20, ASA A30 e ASA A50, é possível executar procedimentos de manutenção nos seguintes componentes.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["Mídia de inicialização - recuperação automatizada"]
 a| 
A mídia de inicialização armazena um conjunto primário e secundário de arquivos de imagem ONTAP que o sistema de armazenamento usa para inicializar.  Durante a recuperação automatizada, o sistema recupera a imagem de inicialização do nó parceiro e executa automaticamente a opção de menu de inicialização apropriada para instalar a imagem na mídia de inicialização de substituição.

O processo automatizado de recuperação de mídia de inicialização é compatível apenas com o ONTAP 9.17.1 e versões posteriores. Se o seu sistema de armazenamento estiver executando uma versão anterior do ONTAP, use o link:bootmedia-replace-workflow.html["procedimento de recuperação de inicialização manual"] .



 a| 
link:bootmedia-replace-workflow.html["Mídia de inicialização - recuperação manual"]
 a| 
A mídia de inicialização armazena um conjunto primário e secundário de arquivos de imagem ONTAP que o sistema de armazenamento usa para inicializar a imagem de uma unidade USB e restaurar a configuração do nó parceiro



 a| 
link:chassis-replace-workflow.html["Chassis"]
 a| 
O chassi é o gabinete físico que abriga todos os componentes do controlador, como a unidade controladora/CPU, fonte de alimentação e e/S.



 a| 
link:controller-replace-workflow.html["Controlador"]
 a| 
Um controlador consiste em uma placa, firmware e software. Ele controla as unidades e executa o software do sistema operacional ONTAP.



 a| 
link:dimm-replace.html["DIMM"]
 a| 
Um módulo de memória dual in-line (DIMM) é um tipo de memória de computador. Eles são instalados para adicionar memória do sistema a uma placa-mãe controladora.



 a| 
link:drive-replace.html["Condução"]
 a| 
Uma unidade é um dispositivo que fornece o armazenamento físico necessário para os dados.



 a| 
link:fan-replace.html["Ventoinha"]
 a| 
Uma ventoinha arrefece o controlador e as unidades.



 a| 
link:io-module-overview.html["Módulo de e/S."]
 a| 
O módulo I/o (módulo de entrada/saída) é um componente de hardware que atua como intermediário entre o controlador e vários dispositivos ou sistemas que precisam trocar dados com o controlador.



 a| 
link:nvdimm-battery-replace.html["Bateria NV"]
 a| 
A bateria de memória não volátil (NV) é responsável por fornecer energia aos componentes do NVMEM enquanto os dados em trânsito estão sendo destinados à memória flash após uma perda de energia.



 a| 
link:power-supply-replace.html["Fonte de alimentação"]
 a| 
Uma fonte de alimentação fornece uma fonte de alimentação redundante em um controlador.



 a| 
link:rtc-battery-replace.html["Bateria de relógio em tempo real"]
 a| 
Uma bateria de relógio em tempo real preserva as informações de data e hora do sistema se a energia estiver desligada.

|===