---
permalink: asa-r2-key-specifications/asa-a70-key-specifications.html 
sidebar: sidebar 
summary: Especificações principais do ASA A70 
---
= Especificações principais do ASA A70
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A seguir estão especificações selecionadas para o sistema de armazenamento ASA A70 em um único par de alta disponibilidade.  Visite o NetApp Hardware Universe (HWU) para obter as especificações completas deste sistema de armazenamento.



== Especificações de capacidade principal, memória, fator de forma e versão do ONTAP

* Configuração da plataforma: Par de HA de chassi único ASA A70
* Capacidade máxima de matéria-prima: 2,6622 PB
* Memória: 256.0000 GB
* Fator de forma: chassi 4U com 2 controladores HA e 48 slots de unidade
* Versão ONTAP : ONTAP: 9.16.1P2
* Slots de expansão PCIe: 18
* Versão mínima do ONTAP : ONTAP 9.16.0 == Máximos de escalonamento
* Tipo: NAS
* Tipo: SAN; Pares HA: 6; Capacidade bruta: 16,0 PB / 14,2 PiB; Memória máxima: 1536 GB
* Tipo: Par HA; Capacidade bruta: 2,7 PB / 2,4 PiB; Memória máxima: 256.0000




== E/S



=== E/S integradas

Não há dados de E/S integrados.



=== Total de E/S

* Protocolo: Ethernet 200 Gbps; Portas: 24
* Protocolo: Ethernet 100 Gbps; Portas: 36
* Protocolo: Ethernet 25 Gbps; Portas: 56
* Protocolo: Ethernet 10 Gbps; Portas: 56
* Protocolo: FC 64 Gbps; Portas: 56
* Protocolo: NVMe/FC 64 Gbps; Portas: 56
* Portas: 0




=== Portas de gerenciamento

* Protocolo: Ethernet 1 Gbps; Portas: 2
* Protocolo: RS-232 115 Kbps; Portas: 4
* Protocolo: USB 600 Mbps; Portas: 2




== Rede de armazenamento suportada

* FC
* iSCSI
* NVMe/FC
* NVMe/TCP == Especificações do ambiente do sistema
* Potência típica: 6938 BTU/h
* Pior cenário de potência: 9089 BTU/h
* Peso: 170,4 lb 77,3 kg
* Altura: 4U
* Largura: 19” compatível com rack IEC (17,6” 44,7 cm)
* Profundidade: 34,5” (36,6” com suporte para gerenciamento de cabos)
* Temperatura/Altitude/Umidade de operação: 10°C a 35°C (50°F a 95°F) a 3048 m (10000 pés) de altitude; 8% a 80% de umidade relativa, sem condensação
* Temperatura/Umidade fora de operação: -40°C a 70°C (-40°F a 158°F) até 12192m (40000 pés) 10% a 95% de umidade relativa, sem condensação, no recipiente original
* Ruído acústico: Potência sonora declarada (LwAd): 8,6 Pressão sonora (LpAm) (posições de observação): 71,6 dB




== Conformidade

* Certificações EMC/EMI: AMCA, FCC, ICES, KC, Marrocos, VCCI
* Certificações de segurança: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificações Segurança/EMC/EMI: EAC, UKRSEPRO
* Certificações Segurança/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normas EMC/EMI: BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normas de segurança: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




== Alta disponibilidade

* Controlador de gerenciamento de placa base baseado em Ethernet (BMC) e interface de gerenciamento ONTAP
* Controladores redundantes hot-swappable
* Fontes de alimentação redundantes com troca a quente
* Gerenciamento de banda SAS por meio de conexões SAS para prateleiras externas

