---
permalink: asa-c250/overview.html 
sidebar: sidebar 
keywords: ASA C250 specifications, ASA C250 specs, NetApp ASA C250, ASA C250 hardware 
summary: Especificações principais para o grupo de plataformas ASA-C250 
---
= Especificações principais do ASA C250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A seguir estão especificações selecionadas para o sistema de armazenamento ASA C250 em um único par de alta disponibilidade. Visite o NetApp Hardware Universe (HWU) para obter as especificações completas deste sistema de armazenamento.



== Especificações principais do ASA C250

* Configuração da plataforma: Par de HA de chassi único ASA C250
* Capacidade máxima de matéria-prima: 1,4736 PB
* Memória: 128.0000 GB
* Fator de forma: chassi 2U com 2 controladores HA e 24 slots de unidade
* Versão ONTAP : ONTAP: 9.16.1P2
* Slots de expansão PCIe: 4
* Versão mínima do ONTAP : ONTAP 9.13.1P1




== máximos de escala

* Tipo: NAS
* Tipo: SAN; Pares HA: 6; Capacidade bruta: 8,8 PB / 7,9 PiB; Memória máxima: 768 GB
* Tipo: Par HA; Capacidade bruta: 1,5 PB / 1,3 PiB; Memória máxima: 128.0000




== E/S



=== E/S integradas

* Protocolo: Ethernet 25 Gbps; Portas: 4
* Protocolo: Ethernet 10 Gbps; Portas: 4




=== Total de E/S

* Protocolo: Ethernet 100 Gbps; Portas: 4
* Protocolo: Ethernet 25 Gbps; Portas: 20
* Protocolo: Ethernet 10 Gbps; Portas: 4
* Protocolo: FC 32 Gbps; Portas: 16
* Protocolo: NVMe/FC 32 Gbps; Portas: 16
* Portas: 0




=== Portas de gerenciamento

* Protocolo: Ethernet 1 Gbps; Portas: 2
* Protocolo: RS-232 115 Kbps; Portas: 4
* Protocolo: USB 12 Mbps; Portas: 4




== Rede de armazenamento suportada

* FC
* iSCSI
* NVMe/FC




== Especificações do ambiente do sistema

* Potência típica: 2906 BTU/h
* Pior cenário de potência: 3750 BTU/h
* Peso: 54,3 lb 24,6 kg
* Altura: 2U
* Largura: 19” compatível com rack IEC (17,6” 44,7 cm)
* Profundidade:
* Temperatura/Altitude/Umidade de operação: 10°C a 35°C (50°F a 95°F) em altitudes de até 3048 m (10000 pés); umidade relativa de 8% a 80%, sem condensação.
* Temperatura/Umidade fora de operação: -40 °C a 70 °C (-40 °F a 158 °F) até 12.192 m (40.000 pés), 10% a 95% de umidade relativa, sem condensação, na embalagem original.
* Ruído acústico: Potência sonora declarada (LwAd): 7,2 Pressão sonora (LpAm) (posições de observação): 69,1 dB




== Conformidade

* Certificações EMC/EMI: AMCA, FCC, ICES, KC, Marrocos, VCCI
* Certificações de segurança: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificações Segurança/EMC/EMI: EAC, UKRSEPRO
* Certificações Segurança/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Normas EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Normas de segurança: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




== Alta disponibilidade

* Controlador de gerenciamento de placa base baseado em Ethernet (BMC) e interface de gerenciamento ONTAP
* Controladores redundantes hot-swappable
* Fontes de alimentação redundantes com troca a quente

