---
permalink: a300/maintain-overview.html 
sidebar: sidebar 
keywords: aff A4300 maintenance, maintenance, repairing A300, repairing asa A300, replace  A300 components, replace A300 components 
summary: Mantenha o hardware ASA A400 
---
= Manter o hardware do AFF A300
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para o sistema de armazenamento AFF A300, pode executar procedimentos de manutenção nos seguintes componentes.



[[boot-media]]
== Suporte de arranque

A Mídia de inicialização armazena um conjunto primário e secundário de arquivos de imagem de inicialização que o sistema usa quando ele é inicializado.



[[chassis]]
== Chassis

O chassi é o gabinete físico que abriga todos os componentes do controlador, como a unidade controladora/CPU, fonte de alimentação e e/S.



[[controller]]
== Controlador

Um controlador consiste em uma placa, firmware e software. Controla as unidades e implementa as funções do ONTAP.



[[dimm]]
== DIMM

Você deve substituir um DIMM (módulo de memória dual in-line) quando houver uma incompatibilidade de memória ou se tiver um DIMM com falha.



[[fan]]
== Ventoinha

A ventoinha arrefece o controlador.



[[nvdimm-battery]]
== Bateria NVDIMM

Uma bateria NVDIMM é responsável por manter a energia do módulo NVDIMM.



[[pcie]]
== PCIe

Uma placa PCIe (Peripheral Component Interconnect Express) é uma placa de expansão que se coneta ao slot PCIe da placa-mãe.



[[power-supply]]
== Fonte de alimentação

Uma fonte de alimentação fornece uma fonte de alimentação redundante em um compartimento de controladora.



[[real-time-clock-battery]]
== Bateria do relógio em tempo real

Uma bateria de relógio em tempo real preserva as informações de data e hora do sistema se a energia estiver desligada.
