---
permalink: ns224/cable-as-switch-attached.html 
sidebar: sidebar 
keywords: ns224 nvme drive shelf cabling guide, ns224 drive shelf cabling guide, ns224 shelf cabling guide, ns224 cabling guide, switch-attach, switch-attached, switch-attached storage, cable ns224 drive shelves as switch-attached storage 
summary: 'Se você tiver um sistema no qual os compartimentos de unidades NS224 precisam ser cabeados como armazenamento conetado a switch (não armazenamento conetado diretamente), use as informações fornecidas.' 
---
= Prateleiras de cabos como armazenamento conetado a switch - NS224 gavetas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você tiver um sistema no qual os NS224 compartimentos de unidades precisem ser cabeados como storage conectado ao switch (não storage com conexão direta), use as informações fornecidas.

* Para cable NS224 shelves de unidade através de switches de armazenamento, você pode consultar o https://hwu.netapp.com["NetApp Hardware Universe"^] para obter mais informações. Para modelos de hardware mais antigos, as informações de cabeamento de switch também podem ser encontradas no https://library.netapp.com/ecm/ecm_download_file/ECMLP2876580["Guia de cabeamento de compartimento de unidade NVMe de NS224 GB"^].
* Para instalar os switches de armazenamento, consulte o https://docs.netapp.com/us-en/ontap-systems-switches/index.html["Documentação do comutador AFF e FAS"^].
* Para confirmar o hardware suportado para o modelo da sua plataforma, como switches de armazenamento e cabos, consulte o https://hwu.netapp.com["NetApp Hardware Universe"^].

