---
permalink: ns224/hot-add-aff-cable-a800-c800.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, aff a800, aff c800, cable 
summary: Conecte sua shelf NS224 ao seu sistema AFF A800 ou AFF C800 de forma que cada shelf tenha duas conexões com cada controlador no par de HA. 
---
= Conecte uma prateleira NS224 ao seu sistema AFF A800 ou AFF C800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Conecte sua shelf NS224 ao seu sistema AFF A800 ou AFF C800 de forma que cada shelf tenha duas conexões com cada controlador no par de HA.

.Passos
. Se você estiver adicionando um compartimento usando um conjunto de portas compatíveis com RoCE (uma placa PCIe compatível com RoCE) em cada controladora e esse for o único compartimento de NS224 TB do seu par de HA, execute as seguintes etapas.
+
Caso contrário, vá para a próxima etapa.

+

NOTE: Esta etapa pressupõe que você instalou a placa PCIe compatível com RoCE no slot 5.

+
.. Compartimento de cabos NSM A porta e0a para controlador A slot 5 porta a (E5A).
.. Compartimento de cabos NSM A porta e0b para a porta b (e5b) do slot 5 do controlador B.
.. Compartimento de cabos NSM B porta e0a para a porta a (E5A) do slot B do controlador B slot 5.
.. Compartimento de cabos NSM B porta e0b para a porta b (e5b) do slot 5 do controlador A.
+
A ilustração a seguir mostra o cabeamento de uma gaveta hot-added usando uma placa PCIe compatível com RoCE em cada controladora:

+
image::../media/drw_ns224_a800_c800_1shelf_IEOPS-964.svg[Cabeamento para AFF/ASA A800 ou AFF/ASA C800 com uma gaveta NS224 e uma placa PCIe]



. Se você estiver adicionando uma ou duas prateleiras usando dois conjuntos de portas compatíveis com RoCE (duas placas PCIe compatíveis com RoCE) em cada controladora, execute as subetapas aplicáveis.
+

NOTE: Esta etapa pressupõe que você instalou as placas PCIe compatíveis com RoCE no slot 5 e slot 3.

+
[cols="1,3"]
|===
| Compartimentos | Cabeamento 


 a| 
Gaveta 1
 a| 

NOTE: Essas subetapas supõem que você está começando o cabeamento pela porta da gaveta de cabeamento e0a para a placa PCIe compatível com RoCE no slot 5, em vez do slot 3.

.. Cabo NSM A porta e0a para controlador A slot 5 porta a (E5A).
.. Cabo NSM A porta e0b para a porta b (e3b) do slot 3 do controlador B.
.. Cabo NSM B porta e0a para o slot B do controlador 5 porta a (E5A).
.. Cabo NSM B porta e0b para o slot 3 do controlador A porta b (e3b).
.. Se você estiver adicionando uma segunda prateleira com o produto em funcionamento, conclua as subetapas "`Prateleira 2`"; caso contrário, vá para a próxima etapa.




 a| 
Gaveta 2
 a| 

NOTE: Essas subetapas supõem que você está começando o cabeamento pela porta da gaveta de cabeamento e0a para a placa PCIe compatível com RoCE no slot 3, em vez do slot 5 (que se correlaciona com as subetapas de cabeamento para a gaveta 1).

.. Cabo NSM A porta e0a para controlador A slot 3 porta a (E3A).
.. Cabo NSM A porta e0b para a porta b (e5b) do slot 5 do controlador B.
.. Cabo NSM B porta e0a para o slot B do controlador 3 porta a (E3A).
.. Cabo NSM B porta e0b para o slot 5 do controlador A porta b (e5b).
.. Vá para a próxima etapa.


|===
+
A ilustração a seguir mostra o cabeamento de duas prateleiras adicionadas a quente:

+
image::../media/drw_ns224_a800_c800_2shelves_IEOPS-966.svg[drw ns224 A800 C800 2shelves IEOPS 966]

. Verifique se o compartimento hot-added está cabeado corretamente usando https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^]o .
+
Se forem gerados erros de cabeamento, siga as ações corretivas fornecidas.



.O que vem a seguir
Se você desativou a atribuição automática de unidades como parte da preparação para este procedimento, será necessário atribuir manualmente a propriedade da unidade e, em seguida, reativar a atribuição automática de unidades, se necessário. Acesse link:hot-add-aff-complete.html["Complete o hot-add"].

Caso contrário, você é feito com o procedimento de hot-add prateleira.
