---
permalink: ns224/hot-add-asa-prepare-a900.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, asa systems, preparation, roce, asa a900 
summary: Prepare seu sistema ASA A900 para adicionar um shelf NS224 a quente, instalando módulos de I/O compatíveis com RoCE, configurando portas, recabeando shelves existentes e desativando a atribuição automática de unidades. 
---
= Prepare seu sistema ASA A900 para adicionar um shelf NS224 a quente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prepare seu sistema ASA A900 para adicionar um shelf NS224 a quente, garantindo portas de storage com capacidade RoCE suficientes, configurando-as para uso de storage, recabeando os shelves existentes para conectividade ideal e desativando a atribuição automática de discos.



== Instale módulos de E/S compatíveis com RoCE

Se o seu sistema suporta o uso de placas PCIe ou módulos de E/S compatíveis com RoCE, o seu par de HA deve ter portas Ethernet compatíveis com RoCE suficientes para suportar o número de gavetas que você está adicionando dinamicamente.

.Passos
. Para cada gaveta que você está adicionando, verifique se há duas portas compatíveis com RoCE em cada controladora.
+
Essas portas podem estar integradas aos controladores, em placas PCIe compatíveis com RoCE, em uma combinação de ambos ou em módulos de E/S compatíveis com RoCE, conforme suportado pelo seu sistema.

. Se o seu par de HA não tiver portas compatíveis com RoCE suficientes disponíveis, instale as placas PCIe ou módulos de E/S adicionais nos slots de controlador corretos, conforme suportado pelo seu sistema.
+
.. Identifique os slots de controlador corretos para o seu sistema. Consulte  https://hwu.netapp.com["NetApp Hardware Universe"^].
.. Consulte a documentação do seu sistema para obter instruções de instalação da placa PCIe ou do módulo de E/S.






== Configurar portas compatíveis com RoCE para uso de armazenamento

Em alguns sistemas, as portas compatíveis com RoCE são automaticamente configuradas para uso de storage quando você instala uma placa PCIe compatível com RoCE ou um módulo de E/S compatível com RoCE em um slot de controlador compatível. No entanto, você deve concluir este procedimento para verificar se as portas estão configuradas corretamente para uso de storage.

A configuração de portas não dedicadas compatíveis com RoCE para uso de armazenamento é um procedimento não disruptivo. Não é necessário reinicializar os controladores, a menos que um ou ambos estejam em modo de manutenção. Este procedimento pressupõe que nenhum dos controladores esteja em modo de manutenção.

Se precisar alterar as portas de uso de storage para uso de rede no futuro, use o comando  `storage port modify -node _node_name_ -port _port_name_ -mode network`.

.Passos
. Verifique se você instalou quaisquer placas PCIe ou módulos de E/S adicionais compatíveis com RoCE em cada controlador.
. Faça login no cluster usando SSH ou a porta serial do console.
. Verifique se as portas não dedicadas no par de HA estão configuradas para uso de armazenamento inserindo o comando  `storage port show`.
+
A saída do comando varia dependendo da sua versão do ONTAP:

+
** **ONTAP 9.8 ou posterior:** As portas não dedicadas configuradas para uso de storage exibem  `storage` na coluna  `Mode`. Portas não configuradas para uso de storage exibem  `network` na coluna  `Mode`.
** **ONTAP 9.7:** As portas não dedicadas configuradas para uso de armazenamento exibem  `false` na  `Is Dedicated?` coluna e  `enabled` na  `State` coluna. Portas não configuradas para uso de armazenamento exibem  `false` na  `Is Dedicated?` coluna e  `disabled` na  `State` coluna.


. Se as portas não dedicadas estiverem configuradas para uso de armazenamento, você concluiu este procedimento. Caso contrário, conclua as etapas a seguir para configurar as portas.
. Configure as portas não dedicadas para uso de storage em um dos controladores. Você deve repetir o comando aplicável para cada porta que estiver configurando.
+
[cols="1,3"]
|===
| Se o seu par HA estiver em execução... | Use este comando... 


 a| 
ONTAP 9 .8 ou posterior
 a| 
`storage port modify -node _node_name_ -port _port_name_ -mode storage`



 a| 
ONTAP 9,7
 a| 
`storage port enable -node _node_name_ -port _port_name_`

|===
. Repita o passo anterior para o segundo controlador.
. Verifique se as portas não dedicadas em ambos os controladores estão configuradas para uso de armazenamento inserindo o comando  `storage port show`.
+
A saída do comando varia dependendo da sua versão do ONTAP:

+
** **ONTAP 9.8 ou posterior:** As portas não dedicadas configuradas para uso de storage exibem  `storage` na  `Mode` coluna.
** **ONTAP 9.7:** As portas não dedicadas configuradas para uso de storage exibem  `false` na  `Is Dedicated?` coluna e  `enabled` na  `State` coluna.






== Gavetas existentes recuperáveis

Ao adicionar shelves a quente a um par de HA A900, é necessário recabelar os shelves existentes para equilibrar a conectividade entre vários módulos de E/S compatíveis com RoCE.

* Se você estiver adicionando uma segunda prateleira com o equipamento em funcionamento, a primeira prateleira deve ser recabeada entre os slots 2 e 10. Para uma segunda prateleira, o procedimento pressupõe que a prateleira existente esteja cabeada a um módulo de E/S compatível com RoCE no slot 2 de cada controlador.
* Se você estiver adicionando uma quarta prateleira com o equipamento em funcionamento, a terceira prateleira deve ser recabeada entre os slots 1 e 11. Para uma quarta prateleira, o procedimento pressupõe que a terceira prateleira esteja cabeada ao slot 1 em cada controlador.


.Passos
. Siga um destes procedimentos se você estiver adicionando uma segunda prateleira ou uma quarta prateleira a quente.
+
** Se você estiver adicionando uma segunda prateleira, reconetável a primeira prateleira através dos módulos de e/S compatíveis com RoCE no slot 2 e slot 10 em cada controladora.
+
... No controlador A, mova o cabo do slot 2 porta b (e2b) para o slot 10 porta b (e10b).
... Repita o mesmo movimento do cabo no controlador B.


** Se você estiver adicionando uma quarta prateleira, reconetável a terceira prateleira através dos módulos de e/S compatíveis com RoCE no slot 1 e slot 11 em cada controladora.
+
... No controlador A, mova o cabo do slot 1 porta b (e1b) para o slot 11 porta b (e11b).
... Repita o mesmo movimento do cabo no controlador B.




. Verifique se a gaveta cabeada está cabeada corretamente usando https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^]o .
+
Se forem gerados erros de cabeamento, siga as ações corretivas fornecidas.





== Desativar a atribuição automática de condução

Se você não tiver certeza se deve atribuir manualmente a propriedade da unidade ou se deseja entender a atribuição automática de políticas de propriedade da unidade para seu sistema de armazenamento, vá para https://docs.netapp.com/us-en/ontap/disks-aggregates/disk-autoassignment-policy-concept.html["Sobre a atribuição automática de propriedade de disco"^].

.Passos
. Verifique se a atribuição automática de unidades está ativada: `storage disk option show`
+
Você pode inserir o comando em qualquer nó.

+
Se a atribuição automática de unidades estiver ativada, o resultado mostra  `on` na  `Auto Assign` coluna para cada nó.

. Se a atribuição automática de condução estiver ativada, desative-a: `storage disk option modify -node _node_name_ -autoassign off`
+
Você deve desativar a atribuição automática de unidade em ambos os nós.



.O que vem a seguir
Vá para link:hot-add-asa-install.html["instalar a prateleira"].
