---
permalink: ns224/hot-add-asa-complete.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, asa systems, complete, drive 
summary: Se você desativou a atribuição automática de unidades, atribua manualmente a propriedade da unidade e reative a atribuição automática de unidades para o seu sistema ASA. 
---
= Conclua a adição a quente da shelf NS224 para o seu sistema ASA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você desativou a atribuição automática de unidade como parte da preparação para o hot-add de gaveta NS224, será necessário atribuir manualmente a propriedade da unidade e, em seguida, reativar a atribuição automática de unidade, se necessário.

.Antes de começar
Você já deve ter conectado os cabos da sua prateleira conforme as instruções para o seu par de HA.

.Passos
. Exibir todas as unidades não possuídas: `storage disk show -container-type unassigned`
+
Você pode inserir o comando em qualquer um dos controladores.

. Atribuir cada unidade: `storage disk assign -disk _disk_name_ -owner _owner_name_`
+
Você pode inserir o comando em qualquer um dos controladores.

+
Você pode usar o caractere curinga para atribuir mais de uma unidade de uma vez.

. Reative a atribuição automática de condução, se necessário: `storage disk option modify -node _node_name_ -autoassign on`
+
É necessário reativar a atribuição automática de unidades em ambos os controladores.


