---
permalink: ns224/service-replace-drive.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, fail, replace, drive, nondisruptive, i/o, hot-swap, hot-swap a drive 
summary: Você pode substituir uma unidade com falha sem interrupções em um compartimento de unidade de NS224 TB que esteja ligado e enquanto e/S estiver em andamento. 
---
= Unidade de troca a quente - NS224 gavetas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode substituir uma unidade com falha sem interrupções em um compartimento de unidade de NS224 TB que esteja ligado e enquanto e/S estiver em andamento.

.Antes de começar
* A unidade que você está instalando deve ser compatível com o compartimento NS224.
+
https://hwu.netapp.com["NetApp Hardware Universe"^]

* Se a autenticação SED estiver ativada, você deverá usar as instruções de substituição do SED na documentação do ONTAP.
+
As instruções na documentação do ONTAP descrevem as etapas adicionais que você deve executar antes e depois de substituir uma SED.

+
https://docs.netapp.com/us-en/ontap/encryption-at-rest/index.html["Visão geral da criptografia NetApp com a CLI"^]

* Todos os outros componentes do sistema devem estar funcionando corretamente; caso contrário, entre em Contato com o suporte técnico.
* Verifique se a unidade que você está removendo está com falha.
+
Você pode verificar se a unidade está com falha executando o `storage disk show -broken` comando. A unidade com falha aparece na lista de unidades com falha. Se isso não acontecer, você deve esperar, e então executar o comando novamente.

+

NOTE: Dependendo do tipo e da capacidade da unidade, pode levar até várias horas para a unidade aparecer na lista de unidades com falha.



.Sobre esta tarefa
* *Prática recomendada:* a melhor prática é ter a versão atual do Pacote de Qualificação de disco (DQP) instalada antes de trocar uma unidade por quente.
+
Ter a versão atual do DQP instalada permite que seu sistema reconheça e use unidades recém-qualificadas. Isso evita mensagens de eventos do sistema sobre ter informações de unidade não atuais e prevenção do particionamento de unidade porque as unidades não são reconhecidas. O DQP também notifica você sobre o firmware da unidade não atual.

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware/download/DISKQUAL/ALL/qual_devices.zip["NetApp Downloads: Pacote de Qualificação de disco"^]

* *Prática recomendada:* a prática recomendada é ter versões atuais do firmware do módulo de gaveta NVMe (NSM) e do firmware da unidade em seu sistema antes de substituir componentes FRU.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["Downloads do NetApp: Firmware da gaveta de disco"^]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["Downloads do NetApp: Firmware da unidade de disco"^]

+
[NOTE]
====
Não reverta o firmware para uma versão que não suporte a gaveta e seus componentes.

====
* O firmware da unidade é atualizado automaticamente (sem interrupções) em novas unidades com versões de firmware não atuais.
+

NOTE: As verificações de firmware da unidade ocorrem a cada dois minutos.

* Se necessário, você pode ligar os LEDs de localização da prateleira (azul) para ajudar a localizar fisicamente a prateleira afetada: `storage shelf location-led modify -shelf-name _shelf_name_ -led-status on`
+
Se você não souber `_shelf_name_` o do compartimento afetado, execute o `storage shelf show` comando.

+
Uma prateleira tem três LEDs de localização: Um no painel de visualização do operador e um em cada módulo NSM. Os LEDs de localização permanecem acesos durante 30 minutos. Você pode desativá-los digitando o mesmo comando, mas usando a `off` opção.

* Quando você desembalar a unidade de substituição, salve todos os materiais de embalagem para uso quando retornar a unidade com falha.
+
Se você precisar do número RMA ou de ajuda adicional com o procedimento de substituição, entre em Contato com o suporte técnico em https://mysupport.netapp.com/site/global/dashboard["Suporte à NetApp"^], 888-463-8277 (América do Norte), 00-800-44-638277 (Europa) ou 800-800-80-800 (Ásia/Pacífico).

* A animação a seguir fornece uma visão geral das partes físicas de remoção e inserção do procedimento de hot-swap da unidade.
+
.Troca automática de uma unidade em uma gaveta de NS224 U.
video::733011a7-e03a-41b0-8723-aa840133bf25[panopto]
+
.Passos
.. Se você quiser atribuir manualmente a propriedade da unidade para a unidade de substituição, você precisa desativar a atribuição automática de unidade se ela estiver ativada.
+

NOTE: Você precisa atribuir manualmente a propriedade da unidade se as unidades na gaveta forem propriedade de ambos os módulos da controladora no par de HA.

+

NOTE: Atribua manualmente a propriedade da unidade e, em seguida, reative a atribuição automática da unidade mais adiante neste procedimento.

+
... Verifique se a atribuição automática de unidades está ativada: `storage disk option show`
+
Você pode inserir o comando em qualquer um dos módulos do controlador.

+
Se a atribuição automática de acionamento estiver ativada, a saída será exibida `on` `Auto Assign` na coluna (para cada módulo do controlador).

... Se a atribuição automática de condução estiver ativada, desative-a: `storage disk option modify -node node_name -autoassign off`
+
Tem de desativar a atribuição automática de condução em ambos os módulos do controlador.



.. Aterre-se corretamente.
.. Identifique fisicamente a unidade com falha.
+
Quando uma unidade falha, o sistema Registra uma mensagem de aviso no console do sistema indicando qual unidade falhou. Além disso, o LED atenção (âmbar) no painel de visualização do operador da prateleira de acionamento e a unidade com falha acendem-se.

+

NOTE: O LED de atividade (verde) em uma unidade com falha pode ser iluminado (sólido), o que indica que a unidade tem energia, mas não deve estar piscando, o que indica atividade de e/S. Uma unidade com falha não tem atividade de e/S.

.. Remova a unidade com falha:
+
... Prima o botão de libertação na superfície da unidade para abrir a pega do excêntrico.
... Deslize a unidade para fora da prateleira usando a alça do came e apoiando a unidade com a outra mão.


.. Aguarde, no mínimo, 70 segundos antes de inserir a unidade de substituição.
+
Isso permite que o sistema reconheça que uma unidade foi removida.

.. Insira a unidade de substituição:
+
... Com o manípulo do excêntrico na posição aberta, utilize as duas mãos para introduzir a transmissão de substituição.
... Prima até a unidade parar.
... Feche a pega do came de forma a que a unidade fique totalmente assente no plano intermédio e a pega encaixe no devido lugar.
+
Certifique-se de que fecha lentamente a pega do excêntrico de forma a que fique corretamente alinhada com a face da unidade.



.. Verifique se o LED de atividade (verde) da unidade está aceso.
+
Quando o LED de atividade da unidade está sólido, significa que a unidade tem energia. Quando o LED de atividade da unidade está intermitente, significa que a unidade tem alimentação e e/S está em curso. Se o firmware da unidade estiver sendo atualizado automaticamente, o LED pisca.

.. Se estiver substituindo outra unidade, repita as etapas 3 a 7.
.. Se você desativou a atribuição automática de unidade na etapa 1, atribua manualmente a propriedade da unidade e, em seguida, reative a atribuição automática de unidade, se necessário:
+
... Exibir todas as unidades não possuídas: `storage disk show -container-type unassigned`
+
Você pode inserir o comando em qualquer um dos módulos do controlador.

... Atribuir cada unidade: `storage disk assign -disk disk_name -owner owner_name`
+
Você pode inserir o comando em qualquer um dos módulos do controlador.

+
Você pode usar o caractere curinga para atribuir mais de uma unidade de uma vez.

... Reative a atribuição automática de condução, se necessário: `storage disk option modify -node node_name -autoassign on`
+
Você deve reativar a atribuição automática de acionamento em ambos os módulos do controlador.






