---
permalink: ns224/service-replace-rtc-battery.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, replace, fail, real-time, clock, rtc, battery, nondisruptive, power, i/o, replace the real-time clock battery 
summary: 'Você pode substituir uma bateria de relógio em tempo real (RTC) com falha sem interrupções em um compartimento de unidade de NS224 TB que está ligado e enquanto e/S está em andamento.' 
---
= Substitua a bateria do relógio em tempo real - NS224 prateleiras
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode substituir uma bateria de relógio em tempo real (RTC) com falha sem interrupções em um compartimento de unidade de NS224 TB que esteja ligado e enquanto e/S estiver em andamento.

.Antes de começar
* O módulo NSM do parceiro do compartimento deve estar ativo e em execução e ser cabeado corretamente, de modo que seu compartimento mantenha a conectividade quando você remover o módulo NSM com a FRU (módulo NSM de destino) com falha.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp Downloads: Config Advisor"^]

* Todos os outros componentes do sistema devem estar a funcionar corretamente.


.Sobre esta tarefa
* Aguarde pelo menos 70 segundos entre a remoção e a instalação do módulo de gaveta NVMe (NSM).
+
Isso permite tempo suficiente para que o ONTAP processe o evento de remoção de NSM.

* Depois de substituir a bateria RTC, reinstale o módulo NSM e o módulo inicializa, a hora do relógio em tempo real é atualizada pelo ONTAP.
* *Prática recomendada:* a prática recomendada é ter versões atuais do firmware do módulo de gaveta NVMe (NSM) e do firmware da unidade em seu sistema antes de substituir componentes FRU.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["Downloads do NetApp: Firmware da gaveta de disco"^]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["Downloads do NetApp: Firmware da unidade de disco"^]

+
[NOTE]
====
Não reverta o firmware para uma versão que não suporte a gaveta e seus componentes.

====
* Se necessário, você pode ligar os LEDs de localização da prateleira (azul) para ajudar a localizar fisicamente a prateleira afetada: `storage shelf location-led modify -shelf-name _shelf_name_ -led-status on`
+
Se você não souber `shelf_name` o do compartimento afetado, execute o `storage shelf show` comando.

+
Uma prateleira tem três LEDs de localização: Um no painel de visualização do operador e um em cada módulo NSM. Os LEDs de localização permanecem acesos durante 30 minutos. Você pode desativá-los digitando o mesmo comando, mas usando a `off` opção.

* Quando desembalar a bateria RTC de substituição, guarde todos os materiais de embalagem para utilização quando devolver a bateria RTC avariada.
+
Se você precisar do número RMA ou de ajuda adicional com o procedimento de substituição, entre em Contato com o suporte técnico em https://mysupport.netapp.com/site/global/dashboard["Suporte à NetApp"^], 888-463-8277 (América do Norte), 00-800-44-638277 (Europa) ou 800-800-80-800 (Ásia/Pacífico).

* Você pode usar a animação a seguir ou as etapas escritas para substituir uma bateria RTC.
+
.Substitua uma bateria RTC em uma prateleira NS224
video::df7a12f4-8554-4448-a3df-aa86002f2de8[panopto]


.Passos
. Aterre-se corretamente.
. Desconete o cabeamento do módulo NSM que contém a FRU que você está substituindo:
+
.. Desconete o cabo de alimentação da fonte de alimentação abrindo o retentor do cabo de alimentação se for uma fonte de alimentação CA ou desapertando os dois parafusos de orelhas se for uma fonte de alimentação CC e, em seguida, desconete o cabo de alimentação da fonte de alimentação.
+
As fontes de alimentação não têm um interrutor de alimentação.

.. Desconete o cabeamento de armazenamento das portas do módulo NSM.
+
Anote as portas do módulo NSM às quais cada cabo está conetado. Reconete os cabos às mesmas portas quando você reinserir o módulo NSM, mais adiante neste procedimento.



. Retire o módulo NSM da prateleira:
+
.. Passe os dedos indicadores através dos orifícios dos dedos dos mecanismos de bloqueio em ambos os lados do módulo NSM.
+

NOTE: Se você estiver removendo o módulo NSM inferior e se o trilho inferior estiver obstruindo o acesso aos mecanismos de travamento, coloque seus dedos indicadores através dos orifícios dos dedos a partir do interior (cruzando os braços).

.. Com os polegares, pressione e segure as abas laranja na parte superior dos mecanismos de travamento.
+
Os mecanismos de bloqueio levantam-se, limpando os pinos de bloqueio na prateleira.

.. Puxe suavemente até que o módulo NSM esteja cerca de um terço da saída da prateleira, segure os lados do módulo NSM com as duas mãos para suportar o seu peso e, em seguida, coloque-o em uma superfície plana e estável.
+
Quando começar a puxar, os braços do mecanismo de engate estendem-se do módulo NSM e trancam-se na sua posição totalmente estendida.



. Desaperte o parafuso de orelhas da tampa do módulo NSM e abra a tampa.
+
A etiqueta FRU na tampa do módulo NSM mostra a localização da bateria RTC, perto da parte frontal do módulo NSM e à direita da fonte de alimentação.

. Identifique fisicamente a bateria RTC com falha.
. Substitua a bateria RTC:
+
.. Retire a bateria empurrando-a suavemente para fora do suporte até que esteja num ângulo inclinado (inclinado para longe do suporte) e, em seguida, levante-a para fora do suporte.
.. Introduza a bateria de substituição no suporte a um ângulo inclinado (inclinado para longe do suporte), empurre-a para uma posição vertical e, em seguida, pressione-a firmemente no conetor até estar completamente assente.
+

NOTE: O lado positivo da bateria, marcado com um sinal de mais, é orientado para fora (afastado do suporte), correspondendo ao sinal de mais marcado na placa do módulo NSM.



. Feche a tampa do módulo NSM e, em seguida, aperte o parafuso de orelhas.
. Volte a inserir o módulo NSM na prateleira:
+
.. Certifique-se de que os braços do mecanismo de engate estão bloqueados na posição totalmente estendida.
.. Utilizando ambas as mãos, deslize cuidadosamente o módulo NSM para dentro da prateleira até que o peso do módulo NSM esteja totalmente suportado pela prateleira.
.. Empurre o módulo NSM para dentro da prateleira até parar (cerca de meia polegada da parte de trás da prateleira).
+
Pode colocar os polegares nas patilhas cor-de-laranja na parte da frente de cada presilha (dos braços do mecanismo de fecho) para empurrar o módulo NSM.

.. Passe os dedos indicadores através dos orifícios dos dedos dos mecanismos de bloqueio em ambos os lados do módulo NSM.
+

NOTE: Se você estiver inserindo o módulo NSM inferior e se o trilho inferior estiver obstruindo o acesso aos mecanismos de travamento, coloque seus dedos indicadores através dos orifícios dos dedos a partir do interior (cruzando os braços).

.. Com os polegares, pressione e segure as abas laranja na parte superior dos mecanismos de travamento.
.. Empurre suavemente para a frente para colocar as travas sobre o batente.
.. Solte os polegares da parte superior dos mecanismos de travamento e, em seguida, continue empurrando até que os mecanismos de travamento se encaixem no lugar.
+
O módulo NSM deve ser totalmente inserido na prateleira e nivelado com as bordas da prateleira.



. Reconecte o cabeamento ao módulo NSM:
+
.. Reconecte o cabeamento de storage às mesmas duas portas de módulo NSM.
+
Os cabos são inseridos com a presilha do conetor voltada para cima. Quando um cabo é inserido corretamente, ele clica no lugar.

.. Volte a ligar o cabo de alimentação à fonte de alimentação e, em seguida, fixe o cabo de alimentação com o fixador do cabo de alimentação se for uma fonte de alimentação CA ou aperte os dois parafusos de orelhas se for uma fonte de alimentação CC e, em seguida, desligue o cabo de alimentação da fonte de alimentação.
+
Quando estiver a funcionar corretamente, o LED bicolor de uma fonte de alimentação acende-se a verde.

+
Além disso, ambos os LEDs LNK (verde) da porta do módulo NSM acendem-se. Se um LED LNK não acender, recoloque o cabo.



. Verifique se os LEDs atenção (âmbar) no módulo NSM que contém a bateria RTC com falha e o painel do visor do operador da prateleira já não estão acesos
+
Os LEDs de atenção do módulo NSM desligam-se depois de o módulo NSM ser reiniciado e não detetar mais um problema com a bateria RTC. Isso pode levar de três a cinco minutos.

. Verifique se o módulo NSM está cabeado corretamente, executando o Active IQ Config Advisor.
+
Se forem gerados erros de cabeamento, siga as ações corretivas fornecidas.

+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp Downloads: Config Advisor"^]


