---
permalink: ns224/service-replace-dimm.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, replace, nondisruptive, dimm, i/o, replace a dimm 
summary: Você pode substituir um DIMM com defeito sem interrupções em um compartimento de unidade NS224 que esteja ligado e enquanto e/S estiver em andamento. 
---
= Substitua um DIMM - NS224 prateleiras
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode substituir um DIMM com defeito sem interrupções em um compartimento de unidade NS224 que esteja ligado e enquanto e/S estiver em andamento.

.Antes de começar
* O módulo NSM do parceiro do compartimento deve estar ativo e em execução e ser cabeado corretamente, de modo que seu compartimento mantenha a conectividade quando você remover o módulo NSM com a FRU (módulo NSM de destino) com falha.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp Downloads: Config Advisor"^]

* Todos os outros componentes do sistema, incluindo os outros três DIMMs, devem estar funcionando corretamente.


.Sobre esta tarefa
* Aguarde pelo menos 70 segundos entre a remoção e a instalação do módulo de gaveta NVMe (NSM).
+
Isso permite tempo suficiente para que o ONTAP processe o evento de remoção de NSM.

* *Prática recomendada:* a prática recomendada é ter versões atuais do firmware do módulo de gaveta NVMe (NSM) e do firmware da unidade em seu sistema antes de substituir componentes FRU.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["Downloads do NetApp: Firmware da gaveta de disco"^]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["Downloads do NetApp: Firmware da unidade de disco"^]

+
[NOTE]
====
Não reverta o firmware para uma versão que não suporte a gaveta e seus componentes.

====
* Se necessário, você pode ligar os LEDs de localização da prateleira (azul) para ajudar a localizar fisicamente a prateleira afetada: `storage shelf location-led modify -shelf-name _shelf_name_ -led-status on`
+
Se você não souber `_shelf_name_` o do compartimento afetado, execute o `storage shelf show` comando.

+
Uma prateleira tem três LEDs de localização: Um no painel de visualização do operador e um em cada módulo NSM. Os LEDs de localização permanecem acesos durante 30 minutos. Você pode desativá-los digitando o mesmo comando, mas usando a `off` opção.

* Quando você desembalar o DIMM de substituição, salve todos os materiais de embalagem para uso quando retornar o DIMM com falha.
+
Se você precisar do número RMA ou de ajuda adicional com o procedimento de substituição, entre em Contato com o suporte técnico em https://mysupport.netapp.com/site/global/dashboard["Suporte à NetApp"^], 888-463-8277 (América do Norte), 00-800-44-638277 (Europa) ou 800-800-80-800 (Ásia/Pacífico).

* Você pode usar a animação a seguir ou as etapas escritas para substituir um DIMM.
+
.Substitua um DIMM em uma gaveta NS224
video::eef28b10-ed93-4aa7-bfce-aa86002f20a2[panopto]


.Passos
. Aterre-se corretamente.
. Desconete o cabeamento do módulo NSM que contém a FRU que você está substituindo:
+
.. Desconete o cabo de alimentação da fonte de alimentação abrindo o retentor do cabo de alimentação se for uma fonte de alimentação CA ou desapertando os dois parafusos de orelhas se for uma fonte de alimentação CC e, em seguida, desconete o cabo de alimentação da fonte de alimentação.
+
As fontes de alimentação não têm um interrutor de alimentação.

.. Desconete o cabeamento de armazenamento das portas do módulo NSM.
+
Anote as portas do módulo NSM às quais cada cabo está conetado. Reconete os cabos às mesmas portas quando você reinserir o módulo NSM, mais adiante neste procedimento.



. Retire o módulo NSM da prateleira:
+
.. Passe os dedos indicadores através dos orifícios dos dedos dos mecanismos de bloqueio em ambos os lados do módulo NSM.
+

NOTE: Se você estiver removendo o módulo NSM inferior e se o trilho inferior estiver obstruindo o acesso aos mecanismos de travamento, coloque seus dedos indicadores através dos orifícios dos dedos a partir do interior (cruzando os braços).

.. Com os polegares, pressione e segure as abas laranja na parte superior dos mecanismos de travamento.
+
Os mecanismos de bloqueio levantam-se, limpando os pinos de bloqueio na prateleira.

.. Puxe suavemente até que o módulo NSM esteja cerca de um terço da saída da prateleira, segure os lados do módulo NSM com as duas mãos para suportar o seu peso e, em seguida, coloque-o em uma superfície plana e estável.
+
Quando começar a puxar, os braços do mecanismo de engate estendem-se do módulo NSM e trancam-se na sua posição totalmente estendida.



. Desaperte o parafuso de orelhas da tampa do módulo NSM e abra a tampa.
+
A etiqueta FRU na tampa do módulo NSM mostra a localização dos quatro DIMMs, dois em ambos os lados do dissipador de calor, no centro do módulo NSM.

. Identifique fisicamente o DIMM com defeito.
+
Quando um DIMM está com defeito, o sistema Registra uma mensagem de aviso no console do sistema indicando qual DIMM está com defeito.

. Substitua o DIMM com defeito:
+
.. Observe a orientação do DIMM no slot para que você possa inserir o DIMM de substituição usando a mesma orientação.
.. Ejete o DIMM do slot empurrando lentamente as abas do ejetor em ambas as extremidades do slot DIMM e, em seguida, levante o DIMM para fora do slot.
+

NOTE: Segure cuidadosamente o DIMM pelos cantos ou bordas para evitar a pressão nos componentes da placa de circuito DIMM.

+
As patilhas do ejetor permanecem na posição aberta.

.. Remova o DIMM de substituição do respetivo saco de transporte antiestático.
.. Segure o DIMM pelos cantos e insira o DIMM diretamente em um slot.
+
O entalhe na parte inferior do DIMM, entre os pinos, deve estar alinhado com a guia no slot.

+
Quando inserido corretamente, o DIMM deve entrar facilmente, mas encaixar firmemente no slot. Caso contrário, insira novamente o DIMM.

.. Empurre com cuidado, mas firmemente, para baixo na borda superior do DIMM até que as abas do ejetor se encaixem no lugar sobre os entalhes em ambas as extremidades do DIMM.


. Feche a tampa do módulo NSM e, em seguida, aperte o parafuso de orelhas.
. Volte a inserir o módulo NSM na prateleira:
+
.. Certifique-se de que os braços do mecanismo de engate estão bloqueados na posição totalmente estendida.
.. Utilizando ambas as mãos, deslize cuidadosamente o módulo NSM para dentro da prateleira até que o peso do módulo NSM esteja totalmente suportado pela prateleira.
.. Empurre o módulo NSM para dentro da prateleira até parar (cerca de meia polegada da parte de trás da prateleira).
+
Pode colocar os polegares nas patilhas cor-de-laranja na parte da frente de cada presilha (dos braços do mecanismo de fecho) para empurrar o módulo NSM.

.. Passe os dedos indicadores através dos orifícios dos dedos dos mecanismos de bloqueio em ambos os lados do módulo NSM.
+

NOTE: Se você estiver inserindo o módulo NSM inferior e se o trilho inferior estiver obstruindo o acesso aos mecanismos de travamento, coloque seus dedos indicadores através dos orifícios dos dedos a partir do interior (cruzando os braços).

.. Com os polegares, pressione e segure as abas laranja na parte superior dos mecanismos de travamento.
.. Empurre suavemente para a frente para colocar as travas sobre o batente.
.. Solte os polegares da parte superior dos mecanismos de travamento e, em seguida, continue empurrando até que os mecanismos de travamento se encaixem no lugar.
+
O módulo NSM deve ser totalmente inserido na prateleira e nivelado com as bordas da prateleira.



. Reconecte o cabeamento ao módulo NSM:
+
.. Reconecte o cabeamento de storage às mesmas duas portas de módulo NSM.
+
Os cabos são inseridos com a presilha do conetor voltada para cima. Quando um cabo é inserido corretamente, ele clica no lugar.

.. Volte a ligar o cabo de alimentação à fonte de alimentação e, em seguida, fixe o cabo de alimentação com o fixador do cabo de alimentação, se for uma fonte de alimentação CA, ou aperte os dois parafusos de orelhas se for uma fonte de alimentação CC.
+
Quando estiver a funcionar corretamente, o LED bicolor de uma fonte de alimentação acende-se a verde.

+
Além disso, ambos os LEDs LNK (verde) da porta do módulo NSM acendem-se. Se um LED LNK não acender, recoloque o cabo.



. Verifique se os LEDs atenção (âmbar) no módulo NSM que contém o DIMM com falha e o painel de exibição do operador da prateleira não estão mais iluminados.
+
Os LEDs de atenção do módulo NSM desligam-se depois que o módulo NSM reinicia e não deteta mais um problema de DIMM. Isso pode levar de três a cinco minutos.

. Verifique se o módulo NSM está cabeado corretamente, executando o Active IQ Config Advisor.
+
Se forem gerados erros de cabeamento, siga as ações corretivas fornecidas.

+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp Downloads: Config Advisor"^]


