---
permalink: fas8300/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: fas8300, fas8700, how to recable the system, how to reassign disks 
summary: Você deve remarcar o armazenamento e confirmar a reatribuição do disco. 
---
= Recable o sistema e reatribuir discos - FAS8300 e FAS8700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve concluir uma série de tarefas antes de restaurar o sistema para a operação completa.



== Passo 1: Recable o sistema

Verifique as conexões de rede e armazenamento do módulo do controlador.

.Passos
. Verifique se o cabeamento está correto usando https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"]o .
+
.. Baixe e instale o Config Advisor.
.. Insira as informações do sistema de destino e clique em coletar dados.
.. Clique na guia cabeamento e examine a saída. Certifique-se de que todos os compartimentos de disco sejam exibidos e todos os discos apareçam na saída, corrigindo quaisquer problemas de cabeamento encontrados.
.. Verifique outro cabeamento clicando na guia apropriada e, em seguida, examinando a saída do Config Advisor.






== Etapa 2: Reatribuir discos

Se o sistema de storage estiver em um par de HA, a ID do sistema do novo módulo de controladora será automaticamente atribuída aos discos quando o giveback ocorrer no final do procedimento. Em um sistema autônomo, você deve reatribuir manualmente a ID aos discos.

Tem de utilizar o procedimento correto para a sua configuração:

[cols="1,2"]
|===
| Redundância de controladora | Em seguida, use este procedimento... 


 a| 
Par de HA
 a| 
<<Opção 1: Verifique a alteração da ID do sistema em um sistema HA>>]



 a| 
Configuração de MetroCluster de dois nós
 a| 
<<Opção 2: Reatribuir manualmente a ID do sistema em sistemas em uma configuração MetroCluster de dois nós>>

|===


=== Opção 1: Verifique a alteração da ID do sistema em um sistema HA

Você deve confirmar a alteração do ID do sistema quando você inicializar o controlador _replacement_ e, em seguida, verificar se a alteração foi implementada.

Este procedimento aplica-se apenas a sistemas que executam o ONTAP em um par de HA.

. Se o controlador _replacement_ estiver no modo Manutenção (mostrando o `*>` prompt, saia do modo Manutenção e vá para o prompt Loader: `halt`
. A partir do prompt Loader no controlador _replacement_, inicialize o controlador, inserindo `y` se for solicitado a substituir o ID do sistema devido a uma incompatibilidade de ID do sistema:
. Aguarde até que a `Waiting for giveback...` mensagem seja exibida no console do controlador _replacement_ e, em seguida, a partir do controlador saudável, verifique se o novo ID do sistema do parceiro foi atribuído automaticamente: `storage failover show`
+
Na saída do comando, você verá uma mensagem informando que a ID do sistema foi alterada no controlador prejudicado, mostrando as IDs antigas e novas corretas. No exemplo a seguir, o node2 foi substituído e tem um novo ID de sistema de 151759706.

+
[listing]
----
node1> `storage failover show`
                                    Takeover
Node              Partner           Possible     State Description
------------      ------------      --------     -------------------------------------
node1             node2             false        System ID changed on partner (Old:
                                                  151759755, New: 151759706), In takeover
node2             node1             -            Waiting for giveback (HA mailboxes)
----
. A partir do controlador saudável, verifique se todos os coredumps são salvos:
+
.. Mude para o nível de privilégio avançado: `set -privilege advanced`
+
Você pode responder `Y` quando solicitado a continuar no modo avançado. O prompt do modo avançado é exibido (*>).

.. Salve quaisquer coredumps: `system node run -node _local-node-name_ partner savecore`
.. Aguarde que o comando "avecore" seja concluído antes de emitir o giveback.
+
Você pode inserir o seguinte comando para monitorar o progresso do comando savecore: `system node run -node _local-node-name_ partner savecore -s`

.. Voltar ao nível de privilégio de administrador: `set -privilege admin`


. Se o sistema de storage tiver o Storage ou o volume Encryption configurado, você deverá restaurar a funcionalidade Storage ou volume Encryption usando um dos procedimentos a seguir, dependendo se você estiver usando o gerenciamento de chaves integrado ou externo:
+
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html["Restaurar chaves de criptografia integradas de gerenciamento de chaves"^]
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-external-encryption-keys-93-later-task.html["Restaurar chaves de criptografia de gerenciamento de chaves externas"^]


. Devolver o controlador:
+
.. A partir do controlador saudável, devolva o armazenamento do controlador substituído: `storage failover giveback -ofnode _replacement_node_name_`
+
O controlador _replacement_ recupera seu armazenamento e completa a inicialização.

+
Se você for solicitado a substituir a ID do sistema devido a uma incompatibilidade de ID do sistema, `y` digite .

+

NOTE: Se o giveback for vetado, você pode considerar substituir os vetos.

+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["Encontre o Guia de Configuração de alta disponibilidade para a sua versão do ONTAP 9"]

.. Após a conclusão do giveback, confirme que o par de HA está saudável e que a aquisição é possível: `storage failover show`
+
A saída do `storage failover show` comando não deve incluir a ID do sistema alterada na mensagem do parceiro.



. Verifique se os discos foram atribuídos corretamente: `storage disk show -ownership`
+
Os discos pertencentes ao controlador _replacement_ devem mostrar o novo ID do sistema. No exemplo a seguir, os discos de propriedade de node1 agora mostram o novo ID do sistema, 1873775277:

+
[listing]
----
node1> `storage disk show -ownership`

Disk  Aggregate Home  Owner  DR Home  Home ID    Owner ID  DR Home ID Reserver  Pool
----- ------    ----- ------ -------- -------    -------    -------  ---------  ---
1.0.0  aggr0_1  node1 node1  -        1873775277 1873775277  -       1873775277 Pool0
1.0.1  aggr0_1  node1 node1           1873775277 1873775277  -       1873775277 Pool0
.
.
.
----




=== Opção 2: Reatribuir manualmente a ID do sistema em sistemas em uma configuração MetroCluster de dois nós

Em uma configuração MetroCluster de dois nós executando o ONTAP, você deve reatribuir manualmente os discos à ID do sistema da nova controladora antes de retornar o sistema à condição operacional normal.

.Sobre esta tarefa
Este procedimento aplica-se apenas a sistemas em uma configuração de MetroCluster de dois nós executando o ONTAP.

Você deve ter certeza de emitir os comandos neste procedimento no nó correto:

* O nó _prejudicado_ é o nó no qual você está realizando a manutenção.
* O nó _replacement_ é o novo nó que substituiu o nó prejudicado como parte deste procedimento.
* O nó _Healthy_ é o parceiro de DR do nó prejudicado.


.Passos
. Se ainda não o tiver feito, reinicie o nó _replacement_, interrompa o processo de inicialização entrando `Ctrl-C`e selecione a opção para inicializar no modo Manutenção no menu exibido.
+
Você deve digitar `Y` quando solicitado para substituir a ID do sistema devido a uma incompatibilidade de ID do sistema.

. Veja os IDs de sistema antigos a partir do nó saudável: ``metrocluster node show -fields node-systemid`,dr-Partner-systemid'
+
Neste exemplo, o Node_B_1 é o nó antigo, com o ID do sistema antigo de 118073209:

+
[listing]
----
dr-group-id cluster         node                 node-systemid dr-partner-systemid
 ----------- --------------------- -------------------- ------------- -------------------
 1           Cluster_A             Node_A_1             536872914     118073209
 1           Cluster_B             Node_B_1             118073209     536872914
 2 entries were displayed.
----
. Veja a nova ID do sistema no prompt do modo de manutenção no nó prejudicado: `disk show`
+
Neste exemplo, o novo ID do sistema é 118065481:

+
[listing]
----
Local System ID: 118065481
    ...
    ...
----
. Reatribua a propriedade do disco (para sistemas FAS), usando as informações de ID do sistema obtidas do comando disk show: `disk reassign -s old system ID`
+
No caso do exemplo anterior, o comando é: `disk reassign -s 118073209`

+
Você pode responder `Y` quando solicitado a continuar.

. Verifique se os discos foram atribuídos corretamente: `disk show -a`
+
Verifique se os discos pertencentes ao nó _replacement_ mostram o novo ID do sistema para o nó _replacement_. No exemplo a seguir, os discos pertencentes ao System-1 agora mostram a nova ID do sistema, 118065481:

+
[listing]
----
*> disk show -a
Local System ID: 118065481

  DISK     OWNER                 POOL   SERIAL NUMBER  HOME
-------    -------------         -----  -------------  -------------
disk_name   system-1  (118065481) Pool0  J8Y0TDZC       system-1  (118065481)
disk_name   system-1  (118065481) Pool0  J8Y09DXC       system-1  (118065481)
.
.
.
----
. A partir do nó saudável, verifique se todos os coredumps são salvos:
+
.. Mude para o nível de privilégio avançado: `set -privilege advanced`
+
Você pode responder `Y` quando solicitado a continuar no modo avançado. O prompt do modo avançado é exibido (*>).

.. Verifique se os coredumps estão salvos: `system node run -node _local-node-name_ partner savecore`
+
Se o comando output indicar que o savecore está em andamento, aguarde que o savecore seja concluído antes de emitir o giveback. Você pode monitorar o progresso do savecore usando o `system node run -node _local-node-name_ partner savecore -s command` .</info>.

.. Voltar ao nível de privilégio de administrador: `set -privilege admin`


. Se o nó _replacement_ estiver no modo Manutenção (mostrando o prompt *>), saia do modo Manutenção e vá para o prompt Loader: `halt`
. Inicialize o nó _replacement_: `boot_ontap`
. Após o nó _replacement_ ter sido totalmente inicializado, execute um switchback: `metrocluster switchback`
. Verifique a configuração do MetroCluster: `metrocluster node show - fields configuration-state`
+
[listing]
----
node1_siteA::> metrocluster node show -fields configuration-state

dr-group-id            cluster node           configuration-state
-----------            ---------------------- -------------- -------------------
1 node1_siteA          node1mcc-001           configured
1 node1_siteA          node1mcc-002           configured
1 node1_siteB          node1mcc-003           configured
1 node1_siteB          node1mcc-004           configured

4 entries were displayed.
----
. Verifique a operação da configuração do MetroCluster no Data ONTAP:
+
.. Verifique se há alertas de integridade em ambos os clusters: `system health alert show`
.. Confirme se o MetroCluster está configurado e no modo normal: `metrocluster show`
.. Execute uma verificação MetroCluster: `metrocluster check run`
.. Apresentar os resultados da verificação MetroCluster: `metrocluster check show`
.. Execute o Config Advisor. Vá para a página Config Advisor no site de suporte da NetApp em https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor/["Support.NetApp.com/NOW/download/Tools/config_ADVISOR/"].
+
Depois de executar o Config Advisor, revise a saída da ferramenta e siga as recomendações na saída para resolver quaisquer problemas descobertos.



. Simular uma operação de comutação:
+
.. A partir do prompt de qualquer nó, altere para o nível de privilégio avançado: `set -privilege advanced`
+
Você precisa responder com `y` quando solicitado para continuar no modo avançado e ver o prompt do modo avançado (*>).

.. Execute a operação de switchback com o parâmetro -simule: `metrocluster switchover -simulate`
.. Voltar ao nível de privilégio de administrador: `set -privilege admin`



