---
permalink: a700s/chassis-replace-overview.html 
sidebar: sidebar 
keywords: aff a700s, replace the chassis 
summary: Substituir um chassis com deficiência o novo chassis do mesmo modelo que o chassis com deficiência. 
---
= Analise os requisitos antes de substituir o chassi AFF A700s
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de substituir o chassi do seu sistema AFF A700s, revise os requisitos para uma substituição bem-sucedida. O procedimento de substituição do chassi move os módulos controladores e as unidades SSD do chassi com problema para o chassi de substituição e é um processo disruptivo.

Todos os outros componentes do sistema devem estar funcionando corretamente; caso contrário, você deve entrar em Contato com o suporte técnico.

* Pode utilizar este procedimento com todas as versões do ONTAP suportadas pelo seu sistema.
* Este procedimento é escrito com a suposição de que você está movendo os SSDs e os módulos do controlador para o novo chassi e que o chassi de substituição é um novo componente do NetApp.
* Este procedimento é disruptivo. Para um cluster de dois nós, você terá uma interrupção de serviço completa e uma interrupção parcial em um cluster de vários nós.

