---
permalink: a700s/maintain-overview.html 
sidebar: sidebar 
keywords: a700s maintenance, maintenance, repairing a700s, repairing a700s, replace a700s components, replace a700s components 
summary: Mantenha o hardware AFF A700s 
---
= Manter o hardware do AFF A700s
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para o sistema de armazenamento AFF A700s, pode executar procedimentos de manutenção nos seguintes componentes.



== Suporte de arranque

A Mídia de inicialização armazena um conjunto primário e secundário de arquivos de imagem de inicialização que o sistema usa quando ele é inicializado.



== Chassis

O chassi é o gabinete físico que abriga todos os componentes do controlador, como a unidade controladora/CPU, fonte de alimentação e e/S.



== Controlador

Um controlador consiste em uma placa, firmware e software. Controla as unidades e implementa as funções do ONTAP.



== DIMM

Você deve substituir um DIMM (módulo de memória dual in-line) quando houver uma incompatibilidade de memória ou se tiver um DIMM com falha.



== Condução

Uma unidade é um dispositivo que fornece a Mídia de armazenamento físico para dados.



== Ventoinha

A ventoinha arrefece o controlador.



== Bateria NVRAM

Uma bateria é incluída com o controlador e fornece a energia de reserva se a energia CA falhar.



== Módulo NVRAM

O módulo NVRAM (memória de acesso aleatório não volátil) preserva os dados armazenados em cache se a energia falhar.



== Placa PCIe

Uma placa PCIe (Peripheral Component Interconnect Express) é uma placa de expansão que se coneta ao slot PCIe da placa-mãe.



== Fonte de alimentação

Uma fonte de alimentação fornece uma fonte de alimentação redundante em um compartimento de controladora.



== Bateria de relógio em tempo real

Uma bateria de relógio em tempo real preserva as informações de data e hora do sistema se a energia estiver desligada.
